// AeroAPI's /flights response only exposes an operator *code* (operator/operator_icao/
// operator_iata, e.g. "QF"), never a display name — confirmed absent from the documented field
// list, and confirmed on FlightAware's own support forum that AeroAPI has no logo/name lookup
// endpoint at all ("logos are not available through FlightXML... our app includes the logos
// within the app itself"). This is a curated lookup covering major global airlines, keyed by
// IATA first (AeroAPI's operator_iata), falling back to ICAO (operator_icao) — good enough to
// cover the large majority of real-world routes without inventing data AeroAPI doesn't supply.
// Airlines not in this table simply keep airline_name = null; the client already renders the
// operator code alone in that case rather than fabricating a name.

const AIRLINE_NAMES_BY_IATA: Record<string, string> = {
  QF: "Qantas",
  JQ: "Jetstar",
  VA: "Virgin Australia",
  NZ: "Air New Zealand",
  SQ: "Singapore Airlines",
  TR: "Scoot",
  MH: "Malaysia Airlines",
  TG: "Thai Airways",
  CX: "Cathay Pacific",
  KA: "Cathay Dragon",
  JL: "Japan Airlines",
  NH: "All Nippon Airways",
  OZ: "Asiana Airlines",
  KE: "Korean Air",
  CI: "China Airlines",
  BR: "EVA Air",
  CA: "Air China",
  MU: "China Eastern",
  CZ: "China Southern",
  HX: "Hong Kong Airlines",
  PR: "Philippine Airlines",
  GA: "Garuda Indonesia",
  VN: "Vietnam Airlines",
  AI: "Air India",
  "6E": "IndiGo",
  UL: "SriLankan Airlines",
  EK: "Emirates",
  EY: "Etihad Airways",
  QR: "Qatar Airways",
  SV: "Saudia",
  TK: "Turkish Airlines",
  LH: "Lufthansa",
  LX: "Swiss International Air Lines",
  OS: "Austrian Airlines",
  SN: "Brussels Airlines",
  BA: "British Airways",
  VS: "Virgin Atlantic",
  AF: "Air France",
  KL: "KLM",
  IB: "Iberia",
  AZ: "ITA Airways",
  SK: "SAS",
  AY: "Finnair",
  LO: "LOT Polish Airlines",
  TP: "TAP Air Portugal",
  EI: "Aer Lingus",
  FR: "Ryanair",
  U2: "easyJet",
  W6: "Wizz Air",
  DY: "Norwegian",
  AA: "American Airlines",
  UA: "United Airlines",
  DL: "Delta Air Lines",
  AS: "Alaska Airlines",
  WN: "Southwest Airlines",
  B6: "JetBlue",
  AC: "Air Canada",
  WS: "WestJet",
  AM: "Aeroméxico",
  LA: "LATAM Airlines",
  AV: "Avianca",
  CM: "Copa Airlines",
  G3: "Gol Linhas Aéreas",
  AD: "Azul Brazilian Airlines",
  ET: "Ethiopian Airlines",
  MS: "EgyptAir",
  SA: "South African Airways",
  KQ: "Kenya Airways",
  RW: "RwandAir",
  FZ: "flydubai",
  WY: "Oman Air",
  GF: "Gulf Air",
  PC: "Pegasus Airlines",
  A3: "Aegean Airlines",
  OK: "Czech Airlines",
  RO: "TAROM",
  JU: "Air Serbia",
  FJ: "Fiji Airways",
  PX: "Air Niugini",
  IE: "Solomon Airlines",
};

const AIRLINE_NAMES_BY_ICAO: Record<string, string> = {
  QFA: "Qantas",
  JST: "Jetstar",
  VOZ: "Virgin Australia",
  ANZ: "Air New Zealand",
  SIA: "Singapore Airlines",
  TGW: "Scoot",
  MAS: "Malaysia Airlines",
  THA: "Thai Airways",
  CPA: "Cathay Pacific",
  JAL: "Japan Airlines",
  ANA: "All Nippon Airways",
  AAR: "Asiana Airlines",
  KAL: "Korean Air",
  CAL: "China Airlines",
  EVA: "EVA Air",
  CCA: "Air China",
  CES: "China Eastern",
  CSN: "China Southern",
  PAL: "Philippine Airlines",
  GIA: "Garuda Indonesia",
  HVN: "Vietnam Airlines",
  AIC: "Air India",
  UAE: "Emirates",
  ETD: "Etihad Airways",
  QTR: "Qatar Airways",
  SVA: "Saudia",
  THY: "Turkish Airlines",
  DLH: "Lufthansa",
  SWR: "Swiss International Air Lines",
  AUA: "Austrian Airlines",
  BAW: "British Airways",
  VIR: "Virgin Atlantic",
  AFR: "Air France",
  KLM: "KLM",
  IBE: "Iberia",
  ITY: "ITA Airways",
  SAS: "SAS",
  FIN: "Finnair",
  AAL: "American Airlines",
  UAL: "United Airlines",
  DAL: "Delta Air Lines",
  ASA: "Alaska Airlines",
  SWA: "Southwest Airlines",
  JBU: "JetBlue",
  ACA: "Air Canada",
  WJA: "WestJet",
  AMX: "Aeroméxico",
  LAN: "LATAM Airlines",
  AVA: "Avianca",
  CMP: "Copa Airlines",
  GLO: "Gol Linhas Aéreas",
  AZU: "Azul Brazilian Airlines",
  ETH: "Ethiopian Airlines",
  MSR: "EgyptAir",
  SAA: "South African Airways",
  KQA: "Kenya Airways",
};

export function lookupAirlineName(operatorIata?: string | null, operatorIcao?: string | null, operator?: string | null): string | null {
  if (operatorIata && AIRLINE_NAMES_BY_IATA[operatorIata]) return AIRLINE_NAMES_BY_IATA[operatorIata];
  if (operatorIcao && AIRLINE_NAMES_BY_ICAO[operatorIcao]) return AIRLINE_NAMES_BY_ICAO[operatorIcao];
  if (operator && AIRLINE_NAMES_BY_IATA[operator]) return AIRLINE_NAMES_BY_IATA[operator];
  if (operator && AIRLINE_NAMES_BY_ICAO[operator]) return AIRLINE_NAMES_BY_ICAO[operator];
  return null;
}
