//
//  WordSearchTheme.swift
//  Twofold
//
//  What the hidden words are about, and which of them a plan includes.
//
//  Themes do the job difficulty does for sudoku: they are the thing you pick before you play, and
//  the thing the tier gates. They are not `game_decks` rows for the same reason sudoku's
//  difficulties are not — a deck exists to select content from a bank, and there is no bank here.
//  The words are in this file and the grid is generated from them on the device.
//
//  ---------------------------------------------------------------------------
//  These lists are a compatibility contract
//  ---------------------------------------------------------------------------
//
//  A grid is generated by shuffling a theme's words with a seed derived from the puzzle's id. That
//  makes the *order* of every list below part of the wire format: inserting a word in the middle
//  changes which words appear in every grid currently in play, and two partners on different app
//  versions would be hunting different words on grids they each believe are shared.
//
//  `WordSearchGeneratorTests` pins this. To add words, append to the end of a list — never insert,
//  never re-sort — and update the pinned counts.
//

import Foundation

enum WordSearchTheme: String, CaseIterable, Codable, Hashable {
    case travel
    case love
    case food
    case nature
    case cities
    case music

    var displayName: String {
        switch self {
        case .travel: "Travel"
        case .love: "Love"
        case .food: "Food & Drink"
        case .nature: "The Outdoors"
        case .cities: "Cities"
        case .music: "Music"
        }
    }

    var blurb: String {
        switch self {
        case .travel: "Departures, arrivals, and everything between."
        case .love: "The words that got you here."
        case .food: "Everything you'd order, everywhere you'd order it."
        case .nature: "Mountains, weather, and the long way round."
        case .cities: "Places you've been and places you're going."
        case .music: "Instruments, genres, and the rest of the band."
        }
    }

    /// Travel and Love are included everywhere. They are the app's own two subjects, so the free
    /// pair is the pair that belongs to Twofold rather than the two that happened to be written
    /// first — and the same split the RPC enforces.
    var requiresPremium: Bool {
        switch self {
        case .travel, .love: false
        case .food, .nature, .cities, .music: true
        }
    }

    /// The pool a grid is drawn from.
    ///
    /// Four to ten letters, so every one of them fits a ten-by-ten grid — ten exactly fills a row,
    /// which is legal and deliberately rare. Uppercase and letters only: the grid holds single
    /// characters, and a space or a hyphen has nowhere to go in it.
    var words: [String] {
        switch self {
        case .travel:
            ["FLIGHT", "AIRPORT", "PASSPORT", "SUITCASE", "DEPARTURE", "ARRIVAL", "BOARDING",
             "TERMINAL", "LUGGAGE", "JOURNEY", "TRANSIT", "VOYAGE", "TICKET", "WINDOW", "AISLE",
             "LAYOVER", "CUSTOMS", "GATE"]
        case .love:
            ["TOGETHER", "MISSING", "LETTERS", "PROMISE", "FOREVER", "DISTANCE", "WAITING",
             "HOMECOMING", "EMBRACE", "DEVOTED", "CHERISH", "LONGING", "REUNION", "TENDER",
             "BELOVED", "KISSES", "ALWAYS"]
        case .food:
            ["NOODLES", "DUMPLING", "PASTRY", "COFFEE", "MARKET", "GELATO", "SEAFOOD", "BRUNCH",
             "PICNIC", "SPICES", "DESSERT", "TASTING", "CHEESE", "BAKERY", "SUPPER", "GARLIC",
             "HONEY", "RAMEN"]
        case .nature:
            ["MOUNTAIN", "VALLEY", "FOREST", "GLACIER", "SUNRISE", "THUNDER", "MEADOW", "CANYON",
             "RIVERS", "ISLAND", "DESERT", "HARBOR", "AURORA", "SUMMIT", "BREEZE", "MONSOON",
             "COAST", "TIDES"]
        case .cities:
            ["LISBON", "TOKYO", "BERLIN", "SYDNEY", "MADRID", "DUBLIN", "SEOUL", "VIENNA",
             "ATHENS", "BOSTON", "OSAKA", "PRAGUE", "CAIRO", "OSLO", "LIMA", "PARIS", "DELHI",
             "QUITO"]
        case .music:
            ["GUITAR", "CHORUS", "MELODY", "RHYTHM", "CONCERT", "ENCORE", "VINYL", "LYRICS",
             "TEMPO", "PIANO", "STRINGS", "HARMONY", "ACOUSTIC", "BALLAD", "DRUMS", "ANTHEM",
             "STAGE", "TUNES"]
        }
    }
}
