//
//  RestorableArchiveTests.swift
//  TwofoldTests
//
//  The offer made when two people who were together before connect again.
//
//  This prompt appears once, at the moment of accepting, and never again — restoring reuses the old
//  couple's id, which is what keeps every storage path and foreign key valid, and once accepting
//  has created a new couple row there is nothing left to reuse. So what it says has to be right the
//  first time: someone deciding whether to bring back three years of photos should not be reading
//  "1 memories".
//

import Testing
import Foundation
@testable import Twofold

struct RestorableArchiveTests {

    private func archive(memories: Int = 0, trips: Int = 0, flights: Int = 0) -> BackendService.RestorableArchive {
        .init(
            coupleID: UUID(),
            dissolvedAt: nil,
            scheduledPurgeAt: nil,
            memoryCount: memories,
            tripCount: trips,
            flightCount: flights
        )
    }

    // MARK: - Whether to ask at all

    /// An archive with nothing in it makes the prompt a question about nothing, and worse, an
    /// interruption at the one moment two people are trying to reconnect.
    @Test("an empty archive is not worth asking about")
    func emptyIsNotOffered() {
        #expect(archive().isEmpty)
        #expect(!archive(memories: 1).isEmpty)
        #expect(!archive(trips: 1).isEmpty)
        #expect(!archive(flights: 1).isEmpty)
    }

    // MARK: - What it says

    @Test("one of something is singular")
    func singular() {
        #expect(archive(memories: 1).summary == "1 memory")
        #expect(archive(trips: 1).summary == "1 trip")
        #expect(archive(flights: 1).summary == "1 flight")
    }

    @Test("several of something is plural")
    func plural() {
        #expect(archive(memories: 12).summary == "12 memories")
        #expect(archive(trips: 3).summary == "3 trips")
    }

    /// Two parts join with "and", three with commas and a final "and". Anything else reads as a
    /// list generated by a program, on a screen that is meant to be about their history.
    @Test("parts are joined the way a person would say them")
    func joining() {
        #expect(archive(memories: 12, trips: 3).summary == "12 memories and 3 trips")
        #expect(archive(memories: 12, trips: 3, flights: 2).summary == "12 memories, 3 trips and 2 flights")
    }

    /// The kinds that are absent are left out entirely — never "0 flights".
    @Test("nothing of a kind is omitted, not written as zero")
    func zeroesAreOmitted() {
        let summary = archive(memories: 5, trips: 0, flights: 2).summary
        #expect(summary == "5 memories and 2 flights")
        #expect(!summary.contains("0"))
    }

    /// `summary` is only ever shown when `isEmpty` is false, but it must not produce a broken
    /// sentence if that ever stops being true — an empty list would otherwise crash on the
    /// `popLast`.
    @Test("an empty summary is a word, not a crash")
    func emptySummaryIsSafe() {
        #expect(archive().summary == "nothing")
    }

    // MARK: - Decoding

    /// Straight from the RPC, snake_case. Wrong keys here would silently produce zero counts,
    /// which reads as "an empty archive" and means the prompt never appears at all.
    @Test("the RPC's row decodes")
    func decodes() throws {
        let json = #"""
        {"couple_id":"5A1E6C7E-0000-0000-0000-00000000000A","dissolved_at":null,
         "scheduled_purge_at":null,"memory_count":12,"trip_count":3,"flight_count":2}
        """#
        let decoded = try JSONDecoder().decode(
            BackendService.RestorableArchive.self, from: Data(json.utf8)
        )
        #expect(decoded.memoryCount == 12)
        #expect(decoded.tripCount == 3)
        #expect(decoded.flightCount == 2)
        #expect(!decoded.isEmpty)
    }
}
