-- Plus-tier content expansion for This or That, covering all 10 shared topic categories.

insert into public.this_or_that_prompts (option_a, option_b, category, tier) values
  ('Coffee', 'Tea', 'Starters', 'plus'),
  ('Morning person', 'Night owl', 'Starters', 'plus'),
  ('Sweet snacks', 'Salty snacks', 'Starters', 'plus'),
  ('Dogs', 'Cats', 'Starters', 'plus'),
  ('Summer', 'Winter', 'Starters', 'plus'),
  ('Books', 'Movies', 'Starters', 'plus'),
  ('Pizza night', 'Taco night', 'Starters', 'plus'),
  ('Pool day', 'Beach day', 'Starters', 'plus'),
  ('Text message', 'Phone call', 'Starters', 'plus'),
  ('Pancakes', 'Waffles', 'Starters', 'plus'),
  ('Rainy day', 'Sunny day', 'Starters', 'plus'),
  ('Home-cooked meal', 'Takeout', 'Starters', 'plus'),
  ('Karaoke night', 'Trivia night', 'Starters', 'plus'),
  ('Board games', 'Video games', 'Starters', 'plus'),
  ('Introvert energy', 'Extrovert energy', 'Get to Know Each Other', 'plus'),
  ('Planner', 'Go-with-the-flow', 'Get to Know Each Other', 'plus'),
  ('Big group hangouts', 'One-on-one time', 'Get to Know Each Other', 'plus'),
  ('Quiet weekend', 'Packed weekend', 'Get to Know Each Other', 'plus'),
  ('Neat and tidy', 'Relaxed about mess', 'Get to Know Each Other', 'plus'),
  ('Optimist', 'Realist', 'Get to Know Each Other', 'plus'),
  ('Big picture thinker', 'Detail-oriented', 'Get to Know Each Other', 'plus'),
  ('Rules follower', 'Rule bender', 'Get to Know Each Other', 'plus'),
  ('Big dreamer', 'Practical thinker', 'Get to Know Each Other', 'plus'),
  ('Competitive', 'Laid-back', 'Get to Know Each Other', 'plus'),
  ('Deep thinker', 'Quick decider', 'Get to Know Each Other', 'plus'),
  ('Homebody', 'Always out and about', 'Get to Know Each Other', 'plus'),
  ('List maker', 'Mental note taker', 'Get to Know Each Other', 'plus'),
  ('Say what''s on your mind', 'Keep some things private', 'Get to Know Each Other', 'plus'),
  ('Big wedding', 'Small elopement', 'Relationship', 'plus'),
  ('Text throughout the day', 'Catch up in the evening', 'Relationship', 'plus'),
  ('Surprise gestures', 'Planned dates', 'Relationship', 'plus'),
  ('Matching outfits', 'Individual style', 'Relationship', 'plus'),
  ('Public displays of affection', 'Private affection', 'Relationship', 'plus'),
  ('Nicknames', 'First names', 'Relationship', 'plus'),
  ('Weekly date night', 'Spontaneous dates', 'Relationship', 'plus'),
  ('Cuddle on the couch', 'Adventure together', 'Relationship', 'plus'),
  ('Give gifts', 'Give experiences', 'Relationship', 'plus'),
  ('Say sorry first', 'Talk it through calmly', 'Relationship', 'plus'),
  ('Celebrate anniversaries big', 'Keep it low-key', 'Relationship', 'plus'),
  ('Shared hobbies', 'Separate hobbies', 'Relationship', 'plus'),
  ('Long engagement', 'Short engagement', 'Relationship', 'plus'),
  ('Love letters', 'Love in actions', 'Relationship', 'plus'),
  ('Backpacking', 'Luxury resort', 'Travel', 'plus'),
  ('New destination', 'Favourite return spot', 'Travel', 'plus'),
  ('Guided tour', 'Explore on your own', 'Travel', 'plus'),
  ('Souvenirs', 'Photos', 'Travel', 'plus'),
  ('Camping under the stars', 'Cosy cabin', 'Travel', 'plus'),
  ('Theme park', 'National park', 'Travel', 'plus'),
  ('Cruise', 'Countryside drive', 'Travel', 'plus'),
  ('Big city skyline', 'Small town charm', 'Travel', 'plus'),
  ('Travel light', 'Pack for every occasion', 'Travel', 'plus'),
  ('Local market', 'Shopping mall', 'Travel', 'plus'),
  ('Train journey', 'Ferry ride', 'Travel', 'plus'),
  ('Island hopping', 'One destination, deep dive', 'Travel', 'plus'),
  ('Group tour', 'Just the two of us', 'Travel', 'plus'),
  ('Bucket list landmark', 'Hidden gem off the map', 'Travel', 'plus'),
  ('Spicy food', 'Mild food', 'Food & Culture', 'plus'),
  ('Cook together', 'Order in', 'Food & Culture', 'plus'),
  ('Try new cuisine', 'Stick to favourites', 'Food & Culture', 'plus'),
  ('Wine', 'Cocktails', 'Food & Culture', 'plus'),
  ('Buffet', 'Set menu', 'Food & Culture', 'plus'),
  ('Breakfast for dinner', 'Dinner for breakfast', 'Food & Culture', 'plus'),
  ('Food truck', 'Sit-down restaurant', 'Food & Culture', 'plus'),
  ('Dessert first', 'Dessert last', 'Food & Culture', 'plus'),
  ('Chopsticks', 'Fork and knife', 'Food & Culture', 'plus'),
  ('Home bakery', 'Store-bought treats', 'Food & Culture', 'plus'),
  ('Farmers market', 'Grocery store', 'Food & Culture', 'plus'),
  ('Live music with dinner', 'Quiet dinner conversation', 'Food & Culture', 'plus'),
  ('Tasting menu', 'Comfort food classics', 'Food & Culture', 'plus'),
  ('Grill outdoors', 'Cook indoors', 'Food & Culture', 'plus'),
  ('Big family gatherings', 'Small intimate ones', 'Family', 'plus'),
  ('Family game night', 'Family movie night', 'Family', 'plus'),
  ('Live near family', 'Live far from family', 'Family', 'plus'),
  ('Family traditions', 'Making our own new ones', 'Family', 'plus'),
  ('Holidays with both families', 'Holidays just the two of us', 'Family', 'plus'),
  ('Family group chat', 'One-on-one calls', 'Family', 'plus'),
  ('Big family reunion trip', 'Quiet family visit', 'Family', 'plus'),
  ('Inherited family recipes', 'New recipes together', 'Family', 'plus'),
  ('Family photos on the wall', 'Digital photo albums', 'Family', 'plus'),
  ('Sunday family dinners', 'Casual family catch-ups', 'Family', 'plus'),
  ('Family road trip', 'Family staycation', 'Family', 'plus'),
  ('Hosting the family', 'Being a guest', 'Family', 'plus'),
  ('Family stories at the table', 'Quiet family time', 'Family', 'plus'),
  ('Save for something big', 'Spend on little joys', 'Money & Finances', 'plus'),
  ('Joint budget spreadsheet', 'Loose mental tracking', 'Money & Finances', 'plus'),
  ('Splurge on experiences', 'Splurge on things', 'Money & Finances', 'plus'),
  ('Invest for the future', 'Enjoy the money now', 'Money & Finances', 'plus'),
  ('Generic brand', 'Name brand', 'Money & Finances', 'plus'),
  ('Treat yourself often', 'Save for a rainy day', 'Money & Finances', 'plus'),
  ('Track every expense', 'Go with the flow', 'Money & Finances', 'plus'),
  ('Discount hunting', 'Convenience over price', 'Money & Finances', 'plus'),
  ('Big purchase all at once', 'Save up gradually', 'Money & Finances', 'plus'),
  ('Splitting bills evenly', 'One person handles it', 'Money & Finances', 'plus'),
  ('Emergency fund first', 'Pay off debt first', 'Money & Finances', 'plus'),
  ('Cash', 'Card', 'Money & Finances', 'plus'),
  ('Budget vacation', 'Splurge vacation', 'Money & Finances', 'plus'),
  ('Brutal honesty', 'Gentle diplomacy', 'Moral Values', 'plus'),
  ('Rules are rules', 'Depends on the situation', 'Moral Values', 'plus'),
  ('Forgive and forget', 'Forgive but remember', 'Moral Values', 'plus'),
  ('Speak up', 'Pick your battles', 'Moral Values', 'plus'),
  ('Loyalty above all', 'Honesty above all', 'Moral Values', 'plus'),
  ('Give the benefit of the doubt', 'Wait and see', 'Moral Values', 'plus'),
  ('Fairness for everyone', 'Loyalty to your own', 'Moral Values', 'plus'),
  ('Apologise first', 'Wait for the right moment', 'Moral Values', 'plus'),
  ('Stand your ground', 'Compromise quickly', 'Moral Values', 'plus'),
  ('Justice', 'Mercy', 'Moral Values', 'plus'),
  ('Say no clearly', 'Soften the no', 'Moral Values', 'plus'),
  ('Keep promises no matter what', 'Adjust when circumstances change', 'Moral Values', 'plus'),
  ('Lead by example', 'Lead by encouragement', 'Moral Values', 'plus'),
  ('Trust easily', 'Trust gradually', 'Moral Values', 'plus'),
  ('Gym workout', 'Outdoor run', 'Hobbies & Lifestyle', 'plus'),
  ('Reading a book', 'Binge-watching a show', 'Hobbies & Lifestyle', 'plus'),
  ('Gardening', 'DIY projects', 'Hobbies & Lifestyle', 'plus'),
  ('Painting', 'Photography', 'Hobbies & Lifestyle', 'plus'),
  ('Yoga', 'High-intensity workout', 'Hobbies & Lifestyle', 'plus'),
  ('Solo hobby time', 'Shared hobby time', 'Hobbies & Lifestyle', 'plus'),
  ('Learning an instrument', 'Learning a language', 'Hobbies & Lifestyle', 'plus'),
  ('Puzzle night', 'Game night', 'Hobbies & Lifestyle', 'plus'),
  ('Early morning workout', 'Evening workout', 'Hobbies & Lifestyle', 'plus'),
  ('Cooking as a hobby', 'Baking as a hobby', 'Hobbies & Lifestyle', 'plus'),
  ('Hiking', 'Cycling', 'Hobbies & Lifestyle', 'plus'),
  ('Collecting something', 'Decluttering everything', 'Hobbies & Lifestyle', 'plus'),
  ('Journaling', 'Podcasts', 'Hobbies & Lifestyle', 'plus'),
  ('Dance class', 'Cooking class', 'Hobbies & Lifestyle', 'plus'),
  ('Talk it out immediately', 'Take time to process first', 'Deep Conversations', 'plus'),
  ('Share every thought', 'Keep some thoughts private', 'Deep Conversations', 'plus'),
  ('Plan for the future', 'Live fully in the present', 'Deep Conversations', 'plus'),
  ('Face fears head-on', 'Ease into them slowly', 'Deep Conversations', 'plus'),
  ('Big life questions', 'Small daily moments', 'Deep Conversations', 'plus'),
  ('Vulnerable and open', 'Reserved and steady', 'Deep Conversations', 'plus'),
  ('Learn from the past', 'Focus on what''s ahead', 'Deep Conversations', 'plus'),
  ('Ask deep questions', 'Let conversations unfold naturally', 'Deep Conversations', 'plus'),
  ('Talk through logic', 'Talk through feelings', 'Deep Conversations', 'plus'),
  ('Seek advice from others', 'Work it out together', 'Deep Conversations', 'plus'),
  ('Revisit old memories', 'Create new ones', 'Deep Conversations', 'plus'),
  ('Comfortable silence', 'Conversation fills the space', 'Deep Conversations', 'plus'),
  ('Change is exciting', 'Stability is comforting', 'Deep Conversations', 'plus'),
  ('Dream big out loud', 'Keep dreams close to the heart', 'Deep Conversations', 'plus');
