-- Adds 52 new Plus-tier "Discuss Before Travelling" / Daily Activity discussion prompts spread across the 10 shared topic categories.

insert into public.discussion_topics (topic, category, tier) values
  ('What''s a small daily habit of mine you''ve come to love?', 'Starters', 'plus'),
  ('What''s something simple that instantly puts you in a good mood?', 'Starters', 'plus'),
  ('What''s a little tradition, just between us, that means more than it might seem?', 'Starters', 'plus'),
  ('What''s your favorite way for us to spend a lazy day together?', 'Starters', 'plus'),
  ('What''s something I do that makes you feel appreciated without me even realizing it?', 'Starters', 'plus'),
  ('What''s a belief or opinion you held strongly years ago that has since changed?', 'Get to Know Each Other', 'plus'),
  ('What''s a moment from your childhood that still shapes how you see the world?', 'Get to Know Each Other', 'plus'),
  ('What''s something about yourself you think people misunderstand at first?', 'Get to Know Each Other', 'plus'),
  ('What''s a skill or talent you wish you''d had more time to develop?', 'Get to Know Each Other', 'plus'),
  ('What''s a story from your life you don''t think you''ve fully told me yet?', 'Get to Know Each Other', 'plus'),
  ('What does feeling truly heard by me look like for you?', 'Relationship', 'plus'),
  ('How do we each prefer to reconnect after a disagreement?', 'Relationship', 'plus'),
  ('What''s something I could do that would make you feel more supported day to day?', 'Relationship', 'plus'),
  ('How do our love languages differ, and how have we learned to meet in the middle?', 'Relationship', 'plus'),
  ('What does a healthy amount of independence within our relationship look like to you?', 'Relationship', 'plus'),
  ('How do we want to handle it when one of us is stressed and the other isn''t sure how to help?', 'Relationship', 'plus'),
  ('What''s a place neither of us has been that you''d love to discover together?', 'Travel', 'plus'),
  ('What does your ideal balance between adventure and relaxation look like on a trip?', 'Travel', 'plus'),
  ('What''s a travel memory, with me or otherwise, that changed how you see the world?', 'Travel', 'plus'),
  ('How do you feel travel has changed you, and how do you hope it keeps shaping us?', 'Travel', 'plus'),
  ('What''s a kind of trip we haven''t tried yet that you''d want to experience together?', 'Travel', 'plus'),
  ('What''s a meal or dish that instantly brings back a strong memory for you?', 'Food & Culture', 'plus'),
  ('What''s a family recipe or food tradition you''d want to carry into our future?', 'Food & Culture', 'plus'),
  ('What''s a cultural tradition, yours or mine, that you''ve come to appreciate more over time?', 'Food & Culture', 'plus'),
  ('What''s a cuisine or style of cooking you''d love for us to learn together?', 'Food & Culture', 'plus'),
  ('What does sharing a meal together mean to you beyond just eating?', 'Food & Culture', 'plus'),
  ('What''s a value from your family growing up that you''d want to carry forward with me?', 'Family', 'plus'),
  ('How do you picture our relationship with each other''s families evolving over time?', 'Family', 'plus'),
  ('What does "family" mean to you beyond blood relatives?', 'Family', 'plus'),
  ('What''s something you learned from watching the relationships in your family growing up?', 'Family', 'plus'),
  ('How do we want to navigate differences in how our families express love or handle conflict?', 'Family', 'plus'),
  ('What does financial security actually feel like to you, beyond a number?', 'Money & Finances', 'plus'),
  ('How did the way money was talked about in your childhood home shape how you handle it now?', 'Money & Finances', 'plus'),
  ('What''s a financial goal you''d love for us to work toward together?', 'Money & Finances', 'plus'),
  ('How comfortable are we with each other knowing the full picture of our finances?', 'Money & Finances', 'plus'),
  ('What does generosity with money look like to you, and where do you draw the line?', 'Money & Finances', 'plus'),
  ('What''s a value you''d never want to compromise on, even under pressure?', 'Moral Values', 'plus'),
  ('How do you decide what feels "right" when a situation feels morally gray?', 'Moral Values', 'plus'),
  ('What''s a cause or issue you feel strongly about, and why does it matter to you?', 'Moral Values', 'plus'),
  ('How do you want us to handle it when we disagree on something we both feel strongly about?', 'Moral Values', 'plus'),
  ('What''s something you believe strongly today that surprises even you?', 'Moral Values', 'plus'),
  ('What''s a hobby of mine you''ve come to genuinely enjoy because of me?', 'Hobbies & Lifestyle', 'plus'),
  ('How do we strike the right balance between together-time and doing our own thing?', 'Hobbies & Lifestyle', 'plus'),
  ('What''s something you''ve always wanted to try but haven''t gotten around to yet?', 'Hobbies & Lifestyle', 'plus'),
  ('What does an ideal, ordinary week look like for you?', 'Hobbies & Lifestyle', 'plus'),
  ('What''s a way we could grow closer through something we do together regularly?', 'Hobbies & Lifestyle', 'plus'),
  ('What''s something about yourself you''re still working to understand?', 'Deep Conversations', 'plus'),
  ('What does growing old together actually look like in your imagination?', 'Deep Conversations', 'plus'),
  ('What''s a fear you don''t talk about often, and how can I help you carry it?', 'Deep Conversations', 'plus'),
  ('What''s something you''ve changed your mind about because of me?', 'Deep Conversations', 'plus'),
  ('What do you think we do best as a couple that we don''t give ourselves credit for?', 'Deep Conversations', 'plus'),
  ('What''s something you hope people say about us, as a couple, years from now?', 'Deep Conversations', 'plus');
