-- Grows all 20 Trivia Battle Premium decks up to 15 items each (from 7-12), completing the
-- deck-growth pass across all 3 game types. All new questions checked for factual accuracy,
-- correct_answer always present in options, and no duplicate question text in the table.

-- Can You Guess the Cuisine? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Baklava, a sweet pastry made with layers of filo and nuts, is popular across which region''s cuisine?', '["Middle East", "East Asia", "Scandinavia", "South America"]'::jsonb, 'Middle East', 'easy', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country is credited with originating the stir-fry cooking technique?', '["China", "Thailand", "Japan", "Vietnam"]'::jsonb, 'China', 'easy', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Ceviche, made from raw fish cured in citrus juice, is a traditional dish of which country?', '["Peru", "Spain", "Mexico", "Chile"]'::jsonb, 'Peru', 'medium', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country is the birthplace of the croissant''s ancestor, the kipferl pastry?', '["Austria", "France", "Germany", "Hungary"]'::jsonb, 'Austria', 'hard', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Goulash, a hearty stew flavored with paprika, is the national dish of which country?', '["Hungary", "Poland", "Romania", "Czechia"]'::jsonb, 'Hungary', 'medium', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country is famous for the fermented soybean dish natto?', '["Japan", "South Korea", "China", "Thailand"]'::jsonb, 'Japan', 'medium', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Paella, a rice dish flavored with saffron, originates from which country?', '["Spain", "Italy", "Portugal", "Morocco"]'::jsonb, 'Spain', 'easy', true, 'Food & Culture', 'premium', '406708cf-3c2b-40b8-af7e-267bdf2c49a5');
update game_decks set question_count = 15 where id = '406708cf-3c2b-40b8-af7e-267bdf2c49a5';

-- Can You Guess the Culinary Term? (7 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What French culinary term refers to cutting vegetables into small, uniform cubes?', '["Brunoise", "Julienne", "Chiffonade", "Mirepoix"]'::jsonb, 'Brunoise', 'medium', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the French term for a mixture of diced carrots, celery, and onion used as a flavor base?', '["Mirepoix", "Roux", "Sofrito", "Bouquet garni"]'::jsonb, 'Mirepoix', 'medium', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a thickening agent made from equal parts fat and flour?', '["Roux", "Mirepoix", "Emulsion", "Reduction"]'::jsonb, 'Roux', 'medium', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What culinary term describes cooking food slowly in its own fat at low temperature?', '["Confit", "Braising", "Poaching", "Searing"]'::jsonb, 'Confit', 'hard', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for briefly boiling food and then plunging it into ice water to stop cooking?', '["Blanching", "Poaching", "Steaming", "Parboiling"]'::jsonb, 'Blanching', 'medium', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What French term describes food that has been finely shredded into thin ribbon-like strips?', '["Chiffonade", "Julienne", "Brunoise", "Batonnet"]'::jsonb, 'Chiffonade', 'hard', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the browning of food caused by high-heat cooking, giving it flavor and color?', '["Maillard reaction", "Caramelization", "Fermentation", "Oxidation"]'::jsonb, 'Maillard reaction', 'medium', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for reducing a liquid by simmering it to concentrate its flavor?', '["Reduction", "Infusion", "Emulsion", "Clarification"]'::jsonb, 'Reduction', 'easy', true, 'Food & Culture', 'premium', '631fce7f-a864-49e1-a24c-730f5b69ba10');
update game_decks set question_count = 15 where id = '631fce7f-a864-49e1-a24c-730f5b69ba10';

-- Do You Know These Family Terms? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for your grandmother''s sister?', '["Great-aunt", "Grand-aunt", "Second cousin", "Godmother"]'::jsonb, 'Great-aunt', 'easy', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a family tree traced only through the mother''s line?', '["Matrilineal descent", "Patrilineal descent", "Bilateral descent", "Cognatic descent"]'::jsonb, 'Matrilineal descent', 'hard', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for children of your aunts and uncles?', '["Cousins", "Nephews", "Siblings", "In-laws"]'::jsonb, 'Cousins', 'easy', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a marriage between two people from different cultural or ethnic backgrounds?', '["Intercultural marriage", "Endogamy", "Arranged marriage", "Civil union"]'::jsonb, 'Intercultural marriage', 'medium', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the legal term for financial support paid to a spouse after divorce?', '["Alimony", "Custody", "Dowry", "Inheritance"]'::jsonb, 'Alimony', 'easy', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the branch of a family descended from a common ancestor?', '["Lineage", "Dynasty", "Clan", "Tribe"]'::jsonb, 'Lineage', 'medium', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What do you call your parent''s cousin, one generation up from your own cousins?', '["First cousin once removed", "Second cousin", "Great-cousin", "Half-cousin"]'::jsonb, 'First cousin once removed', 'hard', true, 'Family', 'premium', 'c79701e9-be36-40ce-aa9a-fe5e06ba0045');
update game_decks set question_count = 15 where id = 'c79701e9-be36-40ce-aa9a-fe5e06ba0045';

-- How Well Do You Know Basic Finance Terms? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the amount of money a company owes to its creditors?', '["Liabilities", "Assets", "Equity", "Revenue"]'::jsonb, 'Liabilities', 'medium', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What term describes the process of borrowing money that must be paid back with interest?', '["A loan", "A grant", "A dividend", "A subsidy"]'::jsonb, 'A loan', 'easy', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a fund set aside to cover unexpected expenses?', '["Emergency fund", "Trust fund", "Pension fund", "Mutual fund"]'::jsonb, 'Emergency fund', 'easy', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What does the term "liquidity" refer to in finance?', '["How easily an asset converts to cash", "How much debt a company has", "The interest rate on a loan", "The total value of a company"]'::jsonb, 'How easily an asset converts to cash', 'medium', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the percentage return earned on an investment over a year?', '["Annual yield", "Principal", "Collateral", "Amortization"]'::jsonb, 'Annual yield', 'medium', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a document that verifies a person''s income and expenses over time?', '["Financial statement", "Credit report", "Tax return", "Bank statement"]'::jsonb, 'Financial statement', 'medium', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for money invested in a business in exchange for partial ownership?', '["Equity investment", "Debt financing", "A loan", "A grant"]'::jsonb, 'Equity investment', 'medium', true, 'Money & Finances', 'premium', '56481d30-b4f4-4a35-a793-bdb263e98bc8');
update game_decks set question_count = 15 where id = '56481d30-b4f4-4a35-a793-bdb263e98bc8';

-- How Well Do You Know Birthstones and the Zodiac? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional birthstone for the month of May?', '["Emerald", "Ruby", "Sapphire", "Pearl"]'::jsonb, 'Emerald', 'easy', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which zodiac sign is represented by a lion?', '["Leo", "Aries", "Taurus", "Cancer"]'::jsonb, 'Leo', 'easy', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which zodiac sign is represented by a goat or sea-goat?', '["Capricorn", "Aquarius", "Taurus", "Aries"]'::jsonb, 'Capricorn', 'medium', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional birthstone for the month of January?', '["Garnet", "Amethyst", "Aquamarine", "Diamond"]'::jsonb, 'Garnet', 'easy', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which element is the zodiac sign Cancer associated with?', '["Water", "Fire", "Earth", "Air"]'::jsonb, 'Water', 'medium', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which zodiac sign spans roughly late June to late July?', '["Cancer", "Leo", "Gemini", "Virgo"]'::jsonb, 'Cancer', 'medium', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional birthstone for the month of June?', '["Pearl", "Opal", "Ruby", "Topaz"]'::jsonb, 'Pearl', 'easy', true, 'Get to Know Each Other', 'premium', '942fe688-953e-47cc-9725-32daec8c33d8');
update game_decks set question_count = 15 where id = '942fe688-953e-47cc-9725-32daec8c33d8';

-- How Well Do You Know Business and Economic History? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which company is credited with creating the first mass-produced automobile, the Model T?', '["Ford", "General Motors", "Chrysler", "Toyota"]'::jsonb, 'Ford', 'easy', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The stock market crash of 1929 is most closely associated with the start of which economic era?', '["The Great Depression", "The Gilded Age", "The Progressive Era", "Stagflation"]'::jsonb, 'The Great Depression', 'easy', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country''s currency is the yen?', '["Japan", "China", "South Korea", "Thailand"]'::jsonb, 'Japan', 'easy', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which tech company was founded by Steve Jobs and Steve Wozniak in a garage in 1976?', '["Apple", "Microsoft", "IBM", "HP"]'::jsonb, 'Apple', 'easy', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What economic term describes a period of rising prices combined with stagnant growth?', '["Stagflation", "Inflation", "Recession", "Deflation"]'::jsonb, 'Stagflation', 'medium', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which organization sets interest rate policy in the United States?', '["The Federal Reserve", "The IMF", "The World Bank", "The SEC"]'::jsonb, 'The Federal Reserve', 'medium', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country pioneered the assembly line manufacturing process in the early 20th century?', '["United States", "Germany", "United Kingdom", "Japan"]'::jsonb, 'United States', 'medium', true, 'Money & Finances', 'premium', '29e3713a-2574-4b9c-8e13-a42d55463c05');
update game_decks set question_count = 15 where id = '29e3713a-2574-4b9c-8e13-a42d55463c05';

-- How Well Do You Know Classic Games and Hobbies? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many squares are on a standard checkers board?', '["64", "100", "49", "81"]'::jsonb, '64', 'easy', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In bowling, what is the term for knocking down all ten pins with the first ball?', '["Strike", "Spare", "Turkey", "Split"]'::jsonb, 'Strike', 'easy', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many cards are in a standard deck, excluding jokers?', '["52", "54", "48", "50"]'::jsonb, '52', 'easy', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which classic game involves guessing a secret code using colored pegs?', '["Mastermind", "Battleship", "Clue", "Risk"]'::jsonb, 'Mastermind', 'medium', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In the game of Scrabble, how many tiles does each player draw at the start of their turn?', '["7", "8", "10", "6"]'::jsonb, '7', 'medium', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which classic board game involves accusing a suspect, weapon, and room to solve a murder?', '["Clue", "Risk", "Life", "Sorry"]'::jsonb, 'Clue', 'easy', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many players are on the court in a standard game of basketball, per team?', '["5", "6", "7", "4"]'::jsonb, '5', 'easy', true, 'Hobbies & Lifestyle', 'premium', '417b7258-bdfa-46c3-a84f-d37083138c74');
update game_decks set question_count = 15 where id = '417b7258-bdfa-46c3-a84f-d37083138c74';

-- How Well Do You Know Ethics and Its History? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which philosopher wrote "The Republic," exploring ideas of justice and the ideal state?', '["Plato", "Aristotle", "Socrates", "Confucius"]'::jsonb, 'Plato', 'medium', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the ethical theory that judges actions based on their consequences?', '["Consequentialism", "Deontology", "Virtue ethics", "Relativism"]'::jsonb, 'Consequentialism', 'medium', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which philosopher is known for the phrase "the unexamined life is not worth living"?', '["Socrates", "Plato", "Aristotle", "Epicurus"]'::jsonb, 'Socrates', 'medium', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a moral framework based on following fixed duties and rules, regardless of outcome?', '["Deontology", "Consequentialism", "Utilitarianism", "Hedonism"]'::jsonb, 'Deontology', 'hard', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which ancient Chinese philosopher emphasized ethics, respect, and social harmony in his teachings?', '["Confucius", "Lao Tzu", "Sun Tzu", "Mencius"]'::jsonb, 'Confucius', 'easy', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the belief that moral truths differ across cultures and individuals?', '["Moral relativism", "Moral absolutism", "Moral realism", "Moral nihilism"]'::jsonb, 'Moral relativism', 'medium', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which humanitarian is known for founding the hospice care movement in the 20th century?', '["Cicely Saunders", "Florence Nightingale", "Clara Barton", "Jane Addams"]'::jsonb, 'Cicely Saunders', 'hard', true, 'Moral Values', 'premium', '765b53b5-144f-4bca-a56a-2ef44c68a667');
update game_decks set question_count = 15 where id = '765b53b5-144f-4bca-a56a-2ef44c68a667';

-- How Well Do You Know History's Most Famous Families? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which royal house has ruled Japan for the longest unbroken imperial line in the world?', '["The Chrysanthemum Throne", "The House of Windsor", "The Habsburgs", "The Romanovs"]'::jsonb, 'The Chrysanthemum Throne', 'hard', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Rothschild family became famous for their dominance in which industry?', '["Banking", "Shipping", "Oil", "Steel"]'::jsonb, 'Banking', 'medium', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which family ruled Florence and much of Renaissance Italy, patronizing artists like Michelangelo?', '["The Medici", "The Borgias", "The Sforza", "The Visconti"]'::jsonb, 'The Medici', 'medium', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Kennedy family is most associated with politics in which country?', '["United States", "Ireland", "United Kingdom", "Canada"]'::jsonb, 'United States', 'easy', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which family founded the Ford Motor Company?', '["The Ford family", "The Rockefeller family", "The Carnegie family", "The Vanderbilt family"]'::jsonb, 'The Ford family', 'easy', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Habsburg family ruled over which empire for centuries?', '["The Austro-Hungarian Empire", "The Ottoman Empire", "The Russian Empire", "The British Empire"]'::jsonb, 'The Austro-Hungarian Empire', 'medium', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which family is closely associated with founding Standard Oil and major American philanthropy?', '["The Rockefellers", "The Vanderbilts", "The Carnegies", "The Morgans"]'::jsonb, 'The Rockefellers', 'medium', true, 'Family', 'premium', '84c370a7-20b5-4114-8e34-ff53cfcda452');
update game_decks set question_count = 15 where id = '84c370a7-20b5-4114-8e34-ff53cfcda452';

-- How Well Do You Know MBTI, Enneagram, and More? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In MBTI, which letter represents a preference for ''Judging'' over ''Perceiving''?', '["J", "P", "I", "E"]'::jsonb, 'J', 'easy', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which Enneagram type is known as ''The Individualist,'' associated with identity and creativity?', '["Type 4", "Type 2", "Type 6", "Type 8"]'::jsonb, 'Type 4', 'hard', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In MBTI, which letter stands for ''Sensing,'' a preference for concrete information?', '["S", "N", "T", "F"]'::jsonb, 'S', 'medium', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which Enneagram type is known as ''The Loyalist,'' associated with security and trust?', '["Type 6", "Type 1", "Type 3", "Type 9"]'::jsonb, 'Type 6', 'hard', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The MBTI is based on typology theories originally developed by which psychologist?', '["Carl Jung", "Sigmund Freud", "B.F. Skinner", "Abraham Maslow"]'::jsonb, 'Carl Jung', 'medium', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which Enneagram type is known as ''The Reformer,'' associated with high standards and integrity?', '["Type 1", "Type 5", "Type 7", "Type 2"]'::jsonb, 'Type 1', 'hard', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In MBTI, which letter represents ''Intuition,'' a preference for abstract patterns over concrete facts?', '["N", "S", "J", "P"]'::jsonb, 'N', 'medium', true, 'Get to Know Each Other', 'premium', '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06');
update game_decks set question_count = 15 where id = '810d54ba-dab1-4bf7-a82d-b97d7bb2eb06';

-- How Well Do You Know Niche Hobbies? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the hobby of building and flying model rockets called?', '["Model rocketry", "Aeromodeling", "Astromodeling", "Rocketeering"]'::jsonb, 'Model rocketry', 'medium', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the hobby of arranging aquatic plants and decor in a fish tank for aesthetic effect called?', '["Aquascaping", "Terrarium building", "Fishkeeping", "Bonsai"]'::jsonb, 'Aquascaping', 'medium', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a person who collects and studies antique clocks and watches?', '["Horologist", "Chronologist", "Timeologist", "Clockmaker"]'::jsonb, 'Horologist', 'hard', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the hobby of restoring and collecting classic cars often called?', '["Automotive restoration", "Motorsport", "Car detailing", "Auto racing"]'::jsonb, 'Automotive restoration', 'easy', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the hobby of searching for buried treasure or lost items using a metal detector?', '["Metal detecting", "Prospecting", "Geocaching", "Treasure hunting"]'::jsonb, 'Metal detecting', 'easy', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional art of Chinese miniature tree cultivation called, similar to Japanese bonsai?', '["Penjing", "Ikebana", "Kokedama", "Suiseki"]'::jsonb, 'Penjing', 'hard', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the hobby of collecting and studying rocks and minerals called?', '["Rockhounding", "Geology", "Mineralogy", "Petrology"]'::jsonb, 'Rockhounding', 'medium', true, 'Hobbies & Lifestyle', 'premium', '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975');
update game_decks set question_count = 15 where id = '3d9f8ace-ef9f-48bf-abe5-1df3d76dd975';

-- How Well Do You Know Philosophy and Medical Pioneers? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which ancient Greek physician is considered the father of modern medicine, giving his name to a medical oath?', '["Hippocrates", "Galen", "Aristotle", "Pythagoras"]'::jsonb, 'Hippocrates', 'easy', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which scientist discovered penicillin, the first widely used antibiotic?', '["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Jonas Salk"]'::jsonb, 'Alexander Fleming', 'easy', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which philosopher is known for the statement "I think, therefore I am"?', '["Ren\u00e9 Descartes", "Immanuel Kant", "John Locke", "David Hume"]'::jsonb, 'René Descartes', 'medium', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which humanitarian founded the Red Cross movement, providing aid regardless of nationality?', '["Henry Dunant", "Albert Schweitzer", "Jean Piaget", "Carl Jung"]'::jsonb, 'Henry Dunant', 'hard', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which scientist developed the smallpox vaccine, the first successful vaccine in history?', '["Edward Jenner", "Louis Pasteur", "Alexander Fleming", "Jonas Salk"]'::jsonb, 'Edward Jenner', 'medium', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which philosopher wrote "Beyond Good and Evil" and developed the concept of the "Übermensch"?', '["Friedrich Nietzsche", "Karl Marx", "S\u00f8ren Kierkegaard", "Arthur Schopenhauer"]'::jsonb, 'Friedrich Nietzsche', 'medium', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which physician developed the polio vaccine in the 1950s?', '["Jonas Salk", "Alexander Fleming", "Edward Jenner", "Louis Pasteur"]'::jsonb, 'Jonas Salk', 'medium', true, 'Moral Values', 'premium', 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5');
update game_decks set question_count = 15 where id = 'a0fbda5e-cf36-40bd-95e0-b2ddd85ce9b5';

-- How Well Do You Know Wedding Customs Around the World? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In traditional Chinese weddings, what color is considered lucky and often worn by the bride?', '["Red", "White", "Gold", "Blue"]'::jsonb, 'Red', 'easy', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the money or gifts a bride''s family traditionally gives to the groom''s family in some cultures?', '["Dowry", "Bride price", "Alimony", "Trousseau"]'::jsonb, 'Dowry', 'medium', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In a traditional Scottish wedding, what garment might the groom wear?', '["A kilt", "A toga", "A sarong", "A poncho"]'::jsonb, 'A kilt', 'easy', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the ceremonial breaking of a glass at the end of a Jewish wedding?', '["Breaking the glass", "Sealing the covenant", "The final blessing", "The unity ritual"]'::jsonb, 'Breaking the glass', 'medium', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In many Western weddings, what is traditionally thrown at the couple as they leave the ceremony?', '["Rice", "Flowers", "Confetti", "Coins"]'::jsonb, 'Rice', 'easy', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional wedding gift for a first anniversary, according to Western tradition?', '["Paper", "Cotton", "Leather", "Wood"]'::jsonb, 'Paper', 'medium', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('In traditional Filipino weddings, what is draped over the couple''s shoulders as a symbol of unity?', '["A cord or veil", "A garland", "A sash", "A ribbon"]'::jsonb, 'A cord or veil', 'hard', true, 'Relationship', 'premium', 'dcc1d4f9-a178-46fd-b013-cb319f7512d8');
update game_decks set question_count = 15 where id = 'dcc1d4f9-a178-46fd-b013-cb319f7512d8';

-- How Well Do You Know Weddings and Relationship Psychology? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which psychologist developed the concept of "love languages" popularized in a bestselling book?', '["Gary Chapman", "John Gottman", "Sue Johnson", "Esther Perel"]'::jsonb, 'Gary Chapman', 'medium', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the psychological theory describing how early bonds with caregivers shape adult relationships?', '["Attachment theory", "Social learning theory", "Cognitive dissonance", "Self-determination theory"]'::jsonb, 'Attachment theory', 'medium', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which psychologist is known for research on the "36 questions that lead to love"?', '["Arthur Aron", "John Gottman", "Sue Johnson", "Gary Chapman"]'::jsonb, 'Arthur Aron', 'hard', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What term describes the tendency to be attracted to people who are similar to ourselves?', '["Homogamy", "Propinquity", "Reciprocity", "Complementarity"]'::jsonb, 'Homogamy', 'hard', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the traditional wedding anniversary gift associated with 10 years of marriage?', '["Tin", "Silver", "Gold", "Pearl"]'::jsonb, 'Tin', 'medium', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which psychologist is famous for identifying the "Four Horsemen" that predict relationship breakdown?', '["John Gottman", "Gary Chapman", "Sue Johnson", "Esther Perel"]'::jsonb, 'John Gottman', 'medium', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the emotional and practical support partners provide each other during stress?', '["Social support", "Emotional labor", "Reciprocity", "Empathy"]'::jsonb, 'Social support', 'medium', true, 'Relationship', 'premium', 'e414e5ae-368e-4557-ada9-c985e226769b');
update game_decks set question_count = 15 where id = 'e414e5ae-368e-4557-ada9-c985e226769b';

-- How Well Do You Know World Geography? (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the longest river in the world?', '["The Nile", "The Amazon", "The Yangtze", "The Mississippi"]'::jsonb, 'The Nile', 'easy', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which mountain is the tallest above sea level in the world?', '["Mount Everest", "K2", "Kangchenjunga", "Denali"]'::jsonb, 'Mount Everest', 'easy', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country has the largest population in the world, as of the 2020s?', '["India", "China", "United States", "Indonesia"]'::jsonb, 'India', 'medium', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the smallest continent by land area?', '["Australia", "Europe", "Antarctica", "South America"]'::jsonb, 'Australia', 'easy', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which African country was formerly known as Abyssinia?', '["Ethiopia", "Eritrea", "Sudan", "Somalia"]'::jsonb, 'Ethiopia', 'medium', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which sea is the saltiest large body of water in the world, where swimmers famously float?', '["The Dead Sea", "The Red Sea", "The Caspian Sea", "The Black Sea"]'::jsonb, 'The Dead Sea', 'easy', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which strait separates Europe from Africa at its narrowest point?', '["Strait of Gibraltar", "Bosphorus Strait", "Strait of Hormuz", "English Channel"]'::jsonb, 'Strait of Gibraltar', 'medium', true, 'Travel', 'premium', '3a868627-a734-4ce4-bbee-021db359b35b');
update game_decks set question_count = 15 where id = '3a868627-a734-4ce4-bbee-021db359b35b';

-- Quick-Fire General Knowledge (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many continents are there on Earth?', '["7", "6", "5", "8"]'::jsonb, '7', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the chemical symbol for water?', '["H2O", "CO2", "O2", "NaCl"]'::jsonb, 'H2O', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many legs does an insect have?', '["6", "8", "4", "10"]'::jsonb, '6', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the largest organ in the human body?', '["Skin", "Liver", "Brain", "Heart"]'::jsonb, 'Skin', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many minutes are in a full day?', '["1440", "1000", "1200", "1600"]'::jsonb, '1440', 'medium', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the freezing point of water in Celsius?', '["0", "32", "100", "-10"]'::jsonb, '0', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many sides does a hexagon have?', '["6", "5", "7", "8"]'::jsonb, '6', 'easy', true, 'Starters', 'premium', '9f8129a7-7c4d-4a74-a013-627dbc9b26ec');
update game_decks set question_count = 15 where id = '9f8129a7-7c4d-4a74-a013-627dbc9b26ec';

-- Taboo History & Facts (12 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country was the first to abolish slavery throughout its empire, in 1833?', '["United Kingdom", "United States", "France", "Portugal"]'::jsonb, 'United Kingdom', 'medium', true, 'Edgy Questions', 'premium', 'b16c34c6-5151-4245-881b-e8d5f6425e22');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Kinsey Reports, controversial studies on human sexuality, were published in which decade?', '["1940s-50s", "1920s", "1960s", "1980s"]'::jsonb, '1940s-50s', 'medium', true, 'Edgy Questions', 'premium', 'b16c34c6-5151-4245-881b-e8d5f6425e22');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which country legalized physician-assisted dying nationwide first, in 2002?', '["Netherlands", "Belgium", "Switzerland", "Canada"]'::jsonb, 'Netherlands', 'hard', true, 'Edgy Questions', 'premium', 'b16c34c6-5151-4245-881b-e8d5f6425e22');
update game_decks set question_count = 15 where id = 'b16c34c6-5151-4245-881b-e8d5f6425e22';

-- Travel Trivia: The Essentials (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What does the travel term "visa on arrival" mean?', '["A visa issued at the destination''s border", "A visa applied for online before departure", "A visa that never expires", "A visa required only for connecting flights"]'::jsonb, 'A visa issued at the destination''s border', 'easy', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for the maximum weight allowed for checked luggage on a flight?', '["Baggage allowance", "Cargo limit", "Freight cap", "Load capacity"]'::jsonb, 'Baggage allowance', 'easy', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which travel document is required to enter most foreign countries, alongside a valid passport?', '["A visa", "A boarding pass", "An itinerary", "A customs form"]'::jsonb, 'A visa', 'easy', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for jet lag caused by crossing multiple time zones quickly?', '["Circadian rhythm disruption", "Motion sickness", "Altitude sickness", "Travel fatigue"]'::jsonb, 'Circadian rhythm disruption', 'medium', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the world''s busiest airport by passenger traffic, as of recent years?', '["Hartsfield-Jackson Atlanta International", "Beijing Capital International", "Dubai International", "Heathrow"]'::jsonb, 'Hartsfield-Jackson Atlanta International', 'medium', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the term for a scheduled stop between two flight legs on the same ticket?', '["Layover", "Diversion", "Standby", "Connection fee"]'::jsonb, 'Layover', 'easy', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which document proves you''re allowed to board a specific flight?', '["Boarding pass", "Visa", "Passport", "Itinerary"]'::jsonb, 'Boarding pass', 'easy', true, 'Travel', 'premium', '5f1cdf1a-5d87-4c89-9852-5661801bbb16');
update game_decks set question_count = 15 where id = '5f1cdf1a-5d87-4c89-9852-5661801bbb16';

-- Warm-Up Trivia: Just the Basics (8 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many colors are in a rainbow?', '["7", "6", "5", "8"]'::jsonb, '7', 'easy', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the smallest ocean in the world?', '["The Arctic Ocean", "The Indian Ocean", "The Southern Ocean", "The Atlantic Ocean"]'::jsonb, 'The Arctic Ocean', 'medium', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the tallest mountain in Africa?', '["Mount Kilimanjaro", "Mount Kenya", "Table Mountain", "Atlas Mountains"]'::jsonb, 'Mount Kilimanjaro', 'easy', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many strings does a standard ukulele have?', '["4", "6", "5", "8"]'::jsonb, '4', 'easy', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the currency used in the United States?', '["Dollar", "Pound", "Euro", "Peso"]'::jsonb, 'Dollar', 'easy', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('How many bones are in the human hand, including the wrist?', '["27", "24", "30", "20"]'::jsonb, '27', 'medium', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('What is the smallest planet in our solar system?', '["Mercury", "Mars", "Venus", "Pluto"]'::jsonb, 'Mercury', 'easy', true, 'Starters', 'premium', '9e1464cc-0306-4b80-84aa-0271fdb31a15');
update game_decks set question_count = 15 where id = '9e1464cc-0306-4b80-84aa-0271fdb31a15';

-- World History Vol. 2 (12 -> 15)
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Renaissance period began in which country?', '["Italy", "France", "England", "Spain"]'::jsonb, 'Italy', 'easy', true, 'History', 'premium', 'e818249a-80ed-4b26-8d8f-a882a9f5f625');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('Which ancient wonder of the world was a giant statue that stood in the harbor of Rhodes?', '["The Colossus of Rhodes", "The Great Pyramid", "The Hanging Gardens", "The Lighthouse of Alexandria"]'::jsonb, 'The Colossus of Rhodes', 'medium', true, 'History', 'premium', 'e818249a-80ed-4b26-8d8f-a882a9f5f625');
insert into trivia_questions (question, options, correct_answer, difficulty, active, category, tier, deck_id) values ('The Treaty of Versailles, signed in 1919, officially ended which war?', '["World War I", "World War II", "The Napoleonic Wars", "The Franco-Prussian War"]'::jsonb, 'World War I', 'easy', true, 'History', 'premium', 'e818249a-80ed-4b26-8d8f-a882a9f5f625');
update game_decks set question_count = 15 where id = 'e818249a-80ed-4b26-8d8f-a882a9f5f625';
