-- ---------------------------------------------------------------------------
-- airports: correct the timezones that are wrong, and fill in the ones that are missing
-- ---------------------------------------------------------------------------
--
-- Found while tracking down why UA60 out of SFO displayed at the wrong hour (see
-- 20260928000000_backfill_flight_airport_timezones.sql, which teaches flights to take their
-- timezone from this table). If flights now trust `airports.timezone`, the values in it have to be
-- right, and 616 of them were not.
--
-- Every value below was derived by looking up each airport's own latitude and longitude against the
-- IANA timezone boundary shapefiles, then compared against what the table already held. That
-- comparison flagged 708 rows. Most are harmless and are deliberately NOT touched here — see the
-- bottom of this file. These are the ones that matter.
--
-- ---------------------------------------------------------------------------
-- 1. Victoria and Tasmania are swapped
-- ---------------------------------------------------------------------------
--
-- Every Victorian airport was recorded as Australia/Hobart and every Tasmanian one as
-- Australia/Melbourne — including MEL itself, which is the busiest airport in this app.
--
-- Nothing displays wrong today: the two zones have kept identical offsets and identical DST
-- transitions since 2008. But they were different before that (Tasmania used to start daylight
-- saving in early October, Victoria in late October), they are separate entries precisely because
-- the two states legislate their own DST independently, and either one can diverge again. A stored
-- timezone is not a stored offset; it is a promise about which jurisdiction's future rules to
-- follow, and this promise pointed at the wrong state.

update public.airports as a set timezone = v.tz
from (values
  ('AVV', 'Australia/Melbourne'),
  ('BSJ', 'Australia/Melbourne'),
  ('BWT', 'Australia/Hobart'),
  ('BXG', 'Australia/Melbourne'),
  ('DPO', 'Australia/Hobart'),
  ('FLS', 'Australia/Hobart'),
  ('GEX', 'Australia/Melbourne'),
  ('HBA', 'Australia/Hobart'),
  ('HLT', 'Australia/Melbourne'),
  ('KNS', 'Australia/Hobart'),
  ('LST', 'Australia/Hobart'),
  ('MBW', 'Australia/Melbourne'),
  ('MEB', 'Australia/Melbourne'),
  ('MEL', 'Australia/Melbourne'),
  ('MHU', 'Australia/Melbourne'),
  ('MQL', 'Australia/Melbourne'),
  ('PTJ', 'Australia/Melbourne'),
  ('SHT', 'Australia/Melbourne'),
  ('SRN', 'Australia/Hobart'),
  ('XMC', 'Australia/Melbourne')
) as v(iata, tz)
where a.iata = v.iata;

-- ---------------------------------------------------------------------------
-- 2. Airports that show the wrong time right now
-- ---------------------------------------------------------------------------
--
-- These are not latent. Each of these is displaying an hour that is currently, visibly wrong:
--
--   * Yukon (YXY, YDA, YZW, ZFA, YQH, YDB, YOC) and Fort Nelson sat on America/Vancouver. Yukon
--     stopped observing DST in 2020 and is now UTC-7 year round, so they read an hour out for
--     half the year.
--   * Mexican border airports (MAM, REX, NLD, PDS, ACN, CJS, CUU, NCG) sat on Mexico_City or
--     Mazatlan. Mexico abolished DST in 2022 but the border strip kept it to stay aligned with the
--     United States, so these read an hour out for half the year.
--   * Chilean Patagonia (PUQ, PNT, WPR, WPU) and Aysen (GXQ, BBA, CCH) sat on America/Santiago.
--     Magallanes stays UTC-3 year round and Aysen was given its own zone in 2025.
--   * AWK Wake Island was on Pacific/Johnston: UTC-10 for an airfield that is UTC+12. Twenty-two
--     hours out, and on the wrong side of the date line.
--   * Plus Saratov, Bougainville, Fernando de Noronha, Eirunepe, Tabatinga, Akrotiri, and a
--     handful of remote Canadian strips.

update public.airports as a set timezone = v.tz
from (values
  ('ACN', 'America/Matamoros'),
  ('AKT', 'Asia/Nicosia'),
  ('AWK', 'Pacific/Wake'),
  ('BBA', 'America/Coyhaique'),
  ('BUA', 'Pacific/Bougainville'),
  ('BWO', 'Europe/Saratov'),
  ('CCH', 'America/Coyhaique'),
  ('CJS', 'America/Ciudad_Juarez'),
  ('CUU', 'America/Chihuahua'),
  ('ERN', 'America/Eirunepe'),
  ('FEN', 'America/Noronha'),
  ('GXQ', 'America/Coyhaique'),
  ('KIF', 'America/Winnipeg'),
  ('MAM', 'America/Matamoros'),
  ('NCG', 'America/Chihuahua'),
  ('NLD', 'America/Matamoros'),
  ('PDS', 'America/Matamoros'),
  ('PNT', 'America/Punta_Arenas'),
  ('PUQ', 'America/Punta_Arenas'),
  ('REX', 'America/Matamoros'),
  ('RTW', 'Europe/Saratov'),
  ('TBT', 'America/Eirunepe'),
  ('TNM', 'America/Punta_Arenas'),
  ('WNN', 'America/Winnipeg'),
  ('WPR', 'America/Punta_Arenas'),
  ('WPU', 'America/Punta_Arenas'),
  ('XKS', 'America/Winnipeg'),
  ('YBI', 'America/St_Johns'),
  ('YDA', 'America/Dawson'),
  ('YDB', 'America/Dawson'),
  ('YGR', 'America/Halifax'),
  ('YMA', 'America/Whitehorse'),
  ('YNA', 'America/Blanc-Sablon'),
  ('YOC', 'America/Dawson'),
  ('YQH', 'America/Whitehorse'),
  ('YXY', 'America/Whitehorse'),
  ('YYE', 'America/Fort_Nelson'),
  ('YZW', 'America/Whitehorse'),
  ('ZFA', 'America/Whitehorse')
) as v(iata, tz)
where a.iata = v.iata;

-- ---------------------------------------------------------------------------
-- 3. The 557 airports with no timezone at all
-- ---------------------------------------------------------------------------
--
-- These are the rows that make the app guess. A flight through an airport with no timezone renders
-- in whatever fallback the screen happens to use, which is how the same departure could read
-- 4:20pm on one screen and 8:20am on another. Every one of them resolves cleanly from its own
-- coordinates.

update public.airports as a set timezone = v.tz
from (values
  ('AAK', 'Pacific/Tarawa'),
  ('AAV', 'Asia/Manila'),
  ('ABH', 'Australia/Brisbane'),
  ('ACS', 'Asia/Krasnoyarsk'),
  ('ADI', 'Africa/Windhoek'),
  ('AEI', 'Europe/Madrid'),
  ('AHJ', 'Asia/Shanghai'),
  ('AID', 'America/Indiana/Indianapolis'),
  ('AIP', 'Asia/Kolkata'),
  ('AIR', 'America/Cuiaba'),
  ('ALE', 'America/Chicago'),
  ('ALN', 'America/Chicago'),
  ('ALX', 'America/Chicago'),
  ('AMN', 'America/Detroit'),
  ('AMT', 'Australia/Adelaide'),
  ('AOU', 'Asia/Vientiane'),
  ('API', 'America/Bogota'),
  ('APQ', 'America/Maceio'),
  ('APT', 'America/Chicago'),
  ('ARY', 'Australia/Melbourne'),
  ('ASN', 'America/Chicago'),
  ('ASS', 'Africa/Johannesburg'),
  ('ATG', 'Asia/Karachi'),
  ('ATI', 'America/Montevideo'),
  ('AXF', 'Asia/Shanghai'),
  ('AXN', 'America/Chicago'),
  ('AYS', 'America/New_York'),
  ('AYW', 'Asia/Jayapura'),
  ('BAR', 'Asia/Shanghai'),
  ('BAT', 'America/Sao_Paulo'),
  ('BBC', 'America/Chicago'),
  ('BBD', 'America/Chicago'),
  ('BCU', 'Africa/Lagos'),
  ('BDI', 'Indian/Mahe'),
  ('BFU', 'Asia/Shanghai'),
  ('BGD', 'America/Chicago'),
  ('BGL', 'Asia/Kathmandu'),
  ('BGN', 'Asia/Srednekolymsk'),
  ('BIB', 'Africa/Mogadishu'),
  ('BIH', 'America/Los_Angeles'),
  ('BJW', 'Asia/Makassar'),
  ('BJY', 'Europe/Belgrade'),
  ('BKE', 'America/Los_Angeles'),
  ('BLN', 'Australia/Melbourne'),
  ('BMB', 'Africa/Kinshasa'),
  ('BMR', 'Europe/Berlin'),
  ('BNB', 'Africa/Kinshasa'),
  ('BNC', 'Africa/Lubumbashi'),
  ('BNG', 'America/Los_Angeles'),
  ('BNJ', 'Europe/Berlin'),
  ('BNM', 'Pacific/Port_Moresby'),
  ('BOX', 'Australia/Darwin'),
  ('BPH', 'Asia/Manila'),
  ('BPI', 'America/Denver'),
  ('BPL', 'Asia/Shanghai'),
  ('BQE', 'Africa/Bissau'),
  ('BQG', 'Asia/Vladivostok'),
  ('BSO', 'Asia/Manila'),
  ('BTL', 'America/Detroit'),
  ('BUL', 'Pacific/Port_Moresby'),
  ('BUT', 'Asia/Thimphu'),
  ('BUU', 'Asia/Jakarta'),
  ('BUW', 'Asia/Makassar'),
  ('BUY', 'Australia/Perth'),
  ('BWQ', 'Australia/Sydney'),
  ('BWW', 'America/Havana'),
  ('BWX', 'Asia/Jakarta'),
  ('BXP', 'Europe/Warsaw'),
  ('BYI', 'America/Boise'),
  ('BYP', 'Australia/Perth'),
  ('BYQ', 'Asia/Makassar'),
  ('BZC', 'America/Sao_Paulo'),
  ('BZD', 'Australia/Sydney'),
  ('CBF', 'America/Chicago'),
  ('CCB', 'America/Los_Angeles'),
  ('CCX', 'America/Cuiaba'),
  ('CCY', 'America/Chicago'),
  ('CDE', 'Asia/Shanghai'),
  ('CDT', 'Europe/Madrid'),
  ('CFV', 'America/Chicago'),
  ('CGY', 'Asia/Manila'),
  ('CJF', 'Australia/Perth'),
  ('CKI', 'Australia/Darwin'),
  ('CLP', 'America/Anchorage'),
  ('CLU', 'America/Indiana/Indianapolis'),
  ('CMD', 'Australia/Sydney'),
  ('CMQ', 'Australia/Brisbane'),
  ('CNN', 'Asia/Kolkata'),
  ('CNO', 'America/Los_Angeles'),
  ('CNR', 'America/Santiago'),
  ('CNU', 'America/Chicago'),
  ('CPO', 'America/Santiago'),
  ('CQA', 'America/Cuiaba'),
  ('CQS', 'America/Porto_Velho'),
  ('CRG', 'America/New_York'),
  ('CSV', 'America/Chicago'),
  ('CUB', 'America/New_York'),
  ('CUD', 'Australia/Brisbane'),
  ('CVC', 'Australia/Adelaide'),
  ('CVE', 'America/Bogota'),
  ('CWJ', 'Asia/Shanghai'),
  ('CWW', 'Australia/Sydney'),
  ('CXI', 'Pacific/Kiritimati'),
  ('CYG', 'Australia/Melbourne'),
  ('DAA', 'America/New_York'),
  ('DAG', 'America/Los_Angeles'),
  ('DBC', 'Asia/Shanghai'),
  ('DCN', 'Australia/Perth'),
  ('DCU', 'America/Chicago'),
  ('DEE', 'Asia/Magadan'),
  ('DEX', 'Asia/Jayapura'),
  ('DGP', 'Europe/Riga'),
  ('DIQ', 'America/Sao_Paulo'),
  ('DKV', 'Australia/Darwin'),
  ('DLK', 'Australia/Adelaide'),
  ('DMN', 'America/Denver'),
  ('DNQ', 'Australia/Sydney'),
  ('DOB', 'Asia/Jayapura'),
  ('DOH', 'Asia/Qatar'),
  ('DQM', 'Asia/Muscat'),
  ('DRA', 'America/Los_Angeles'),
  ('DRN', 'Australia/Brisbane'),
  ('DRV', 'Indian/Maldives'),
  ('DSS', 'Africa/Dakar'),
  ('DTU', 'Asia/Shanghai'),
  ('DU9', 'America/Toronto'),
  ('DWA', 'Africa/Blantyre'),
  ('DWD', 'Asia/Riyadh'),
  ('DYA', 'Australia/Brisbane'),
  ('EBH', 'Africa/Algiers'),
  ('ECH', 'Australia/Melbourne'),
  ('ECI', 'America/Managua'),
  ('ECV', 'Europe/Madrid'),
  ('EDD', 'Australia/Darwin'),
  ('EED', 'America/Los_Angeles'),
  ('EFG', 'Pacific/Port_Moresby'),
  ('EGI', 'America/Chicago'),
  ('EJN', 'Asia/Shanghai'),
  ('EKA', 'America/Los_Angeles'),
  ('EKI', 'America/Indiana/Indianapolis'),
  ('EKS', 'Asia/Sakhalin'),
  ('EMT', 'America/Los_Angeles'),
  ('ENN', 'America/Anchorage'),
  ('ENO', 'America/Asuncion'),
  ('ERD', 'Europe/Kyiv'),
  ('ERL', 'Asia/Shanghai'),
  ('ETB', 'America/Chicago'),
  ('ETM', 'Asia/Jerusalem'),
  ('ETS', 'America/Chicago'),
  ('FAC', 'Pacific/Tahiti'),
  ('FAH', 'Asia/Kabul'),
  ('FET', 'America/Chicago'),
  ('FIK', 'Australia/Darwin'),
  ('FLB', 'America/Fortaleza'),
  ('FLP', 'America/Chicago'),
  ('FNB', 'Europe/Berlin'),
  ('FRB', 'Australia/Sydney'),
  ('FSS', 'Europe/London'),
  ('FYJ', 'Asia/Shanghai'),
  ('FYN', 'Asia/Shanghai'),
  ('GBG', 'America/Chicago'),
  ('GDC', 'America/New_York'),
  ('GEC', 'Asia/Famagusta'),
  ('GID', 'Africa/Bujumbura'),
  ('GII', 'Africa/Conakry'),
  ('GIT', 'Africa/Dar_es_Salaam'),
  ('GLR', 'America/Detroit'),
  ('GLU', 'Asia/Thimphu'),
  ('GLW', 'America/Chicago'),
  ('GMO', 'Africa/Lagos'),
  ('GMQ', 'Asia/Shanghai'),
  ('GMU', 'America/New_York'),
  ('GOO', 'Australia/Brisbane'),
  ('GPN', 'Australia/Darwin'),
  ('GUH', 'Australia/Sydney'),
  ('GUU', 'Atlantic/Reykjavik'),
  ('GUY', 'America/Chicago'),
  ('GUZ', 'America/Sao_Paulo'),
  ('GVN', 'Asia/Vladivostok'),
  ('GXY', 'America/Denver'),
  ('GZI', 'Asia/Kabul'),
  ('HAF', 'America/Los_Angeles'),
  ('HCJ', 'Asia/Shanghai'),
  ('HDE', 'America/Chicago'),
  ('HGI', 'Africa/Juba'),
  ('HHZ', 'Pacific/Tahiti'),
  ('HIM', 'Asia/Colombo'),
  ('HLE', 'Atlantic/St_Helena'),
  ('HLI', 'America/Los_Angeles'),
  ('HMG', 'Australia/Darwin'),
  ('HMY', 'Asia/Seoul'),
  ('HNY', 'Asia/Shanghai'),
  ('HOI', 'Pacific/Tahiti'),
  ('HPG', 'Asia/Shanghai'),
  ('HSM', 'Australia/Melbourne'),
  ('HTR', 'Asia/Tokyo'),
  ('HTT', 'Asia/Shanghai'),
  ('HTU', 'Australia/Melbourne'),
  ('HTV', 'America/Chicago'),
  ('HUO', 'Asia/Shanghai'),
  ('HVS', 'America/New_York'),
  ('HXD', 'Asia/Shanghai'),
  ('HXX', 'Australia/Sydney'),
  ('HYD', 'Asia/Kolkata'),
  ('HYR', 'America/Chicago'),
  ('HZP', 'America/Edmonton'),
  ('IDP', 'America/Chicago'),
  ('IEJ', 'Asia/Tokyo'),
  ('IFU', 'Indian/Maldives'),
  ('IKL', 'Africa/Kinshasa'),
  ('IKU', 'Asia/Bishkek'),
  ('ILA', 'Asia/Jayapura'),
  ('INA', 'Europe/Moscow'),
  ('ION', 'Africa/Brazzaville'),
  ('ISB', 'Asia/Karachi'),
  ('IST', 'Europe/Istanbul'),
  ('ITP', 'America/Sao_Paulo'),
  ('IWK', 'Asia/Tokyo'),
  ('IXT', 'Asia/Kolkata'),
  ('JAE', 'America/Lima'),
  ('JAM', 'Europe/Sofia'),
  ('JAS', 'America/Chicago'),
  ('JCT', 'America/Chicago'),
  ('JIA', 'America/Cuiaba'),
  ('JIC', 'Asia/Shanghai'),
  ('JJG', 'America/Sao_Paulo'),
  ('JMJ', 'Asia/Shanghai'),
  ('JOJ', 'America/Cambridge_Bay'),
  ('JRN', 'America/Cuiaba'),
  ('JSJ', 'Asia/Shanghai'),
  ('JSK', 'Asia/Tehran'),
  ('JUA', 'America/Cuiaba'),
  ('KAZ', 'Asia/Jayapura'),
  ('KBN', 'Africa/Lubumbashi'),
  ('KCF', 'Asia/Karachi'),
  ('KCS', 'Australia/Darwin'),
  ('KDA', 'Africa/Dakar'),
  ('KDC', 'Africa/Porto-Novo'),
  ('KEO', 'Africa/Abidjan'),
  ('KES', 'America/Winnipeg'),
  ('KGW', 'Pacific/Port_Moresby'),
  ('KGY', 'Australia/Brisbane'),
  ('KHZ', 'Pacific/Tahiti'),
  ('KIY', 'Africa/Dar_es_Salaam'),
  ('KJH', 'Asia/Shanghai'),
  ('KLJ', 'Europe/Vilnius'),
  ('KMX', 'Asia/Riyadh'),
  ('KNR', 'Asia/Tehran'),
  ('KOO', 'Africa/Lubumbashi'),
  ('KOX', 'Asia/Jayapura'),
  ('KPS', 'Australia/Sydney'),
  ('KQH', 'Asia/Kolkata'),
  ('KRA', 'Australia/Melbourne'),
  ('KRC', 'Asia/Jakarta'),
  ('KRQ', 'Europe/Kyiv'),
  ('KSE', 'Africa/Kampala'),
  ('KWB', 'Asia/Jakarta'),
  ('KZF', 'Pacific/Port_Moresby'),
  ('LDM', 'America/Detroit'),
  ('LEE', 'America/New_York'),
  ('LFQ', 'Asia/Shanghai'),
  ('LGD', 'America/Los_Angeles'),
  ('LHK', 'Asia/Shanghai'),
  ('LLB', 'Asia/Shanghai'),
  ('LMR', 'Africa/Johannesburg'),
  ('LNL', 'Asia/Shanghai'),
  ('LNX', 'Europe/Moscow'),
  ('LOL', 'America/Los_Angeles'),
  ('LPF', 'Asia/Shanghai'),
  ('LUC', 'Pacific/Fiji'),
  ('LXN', 'America/Chicago'),
  ('MAI', 'Africa/Blantyre'),
  ('MBG', 'America/Chicago'),
  ('MBI', 'Africa/Dar_es_Salaam'),
  ('MCB', 'America/Chicago'),
  ('MDH', 'America/Chicago'),
  ('MEQ', 'Asia/Jakarta'),
  ('MHE', 'America/Chicago'),
  ('MLZ', 'America/Montevideo'),
  ('MMT', 'America/New_York'),
  ('MNA', 'Asia/Makassar'),
  ('MNH', 'Asia/Muscat'),
  ('MNS', 'Africa/Lusaka'),
  ('MPO', 'America/New_York'),
  ('MRF', 'America/Chicago'),
  ('MRG', 'Australia/Brisbane'),
  ('MTG', 'America/Cuiaba'),
  ('MTP', 'America/New_York'),
  ('MVW', 'America/Los_Angeles'),
  ('MWE', 'Africa/Khartoum'),
  ('MXI', 'Asia/Manila'),
  ('MYZ', 'Africa/Blantyre'),
  ('NAC', 'Australia/Adelaide'),
  ('NAM', 'Asia/Jayapura'),
  ('NAU', 'Pacific/Tahiti'),
  ('NBN', 'Africa/Malabo'),
  ('NBW', 'America/New_York'),
  ('NCJ', 'America/Argentina/Cordoba'),
  ('NDD', 'Africa/Luanda'),
  ('NDN', 'Pacific/Port_Moresby'),
  ('NGA', 'Australia/Sydney'),
  ('NGD', 'America/Tortola'),
  ('NGK', 'Asia/Sakhalin'),
  ('NHZ', 'America/New_York'),
  ('NIS', 'Pacific/Port_Moresby'),
  ('NKB', 'Australia/Perth'),
  ('NLH', 'Asia/Shanghai'),
  ('NLI', 'Asia/Vladivostok'),
  ('NPR', 'America/Santarem'),
  ('NRB', 'America/New_York'),
  ('NRE', 'Asia/Jayapura'),
  ('NUK', 'Pacific/Tahiti'),
  ('NYR', 'Asia/Yakutsk'),
  ('NZE', 'Africa/Conakry'),
  ('NZL', 'Asia/Shanghai'),
  ('OCM', 'Australia/Perth'),
  ('OEL', 'Europe/Moscow'),
  ('OFK', 'America/Chicago'),
  ('OGB', 'America/New_York'),
  ('OGU', 'Europe/Istanbul'),
  ('OHS', 'Asia/Muscat'),
  ('OKK', 'America/Indiana/Indianapolis'),
  ('OKL', 'Asia/Jayapura'),
  ('OLL', 'Africa/Brazzaville'),
  ('OTJ', 'Africa/Windhoek'),
  ('OTM', 'America/Chicago'),
  ('OZR', 'America/Chicago'),
  ('PAL', 'America/Bogota'),
  ('PBQ', 'America/Porto_Velho'),
  ('PCD', 'America/Chicago'),
  ('PCQ', 'Asia/Vientiane'),
  ('PCS', 'America/Fortaleza'),
  ('PDU', 'America/Montevideo'),
  ('PGZ', 'America/Sao_Paulo'),
  ('PIW', 'America/Winnipeg'),
  ('PKO', 'Africa/Porto-Novo'),
  ('PKT', 'Australia/Darwin'),
  ('PKX', 'Asia/Shanghai'),
  ('PMH', 'America/New_York'),
  ('POU', 'America/New_York'),
  ('PPA', 'America/Chicago'),
  ('PPF', 'America/Chicago'),
  ('PPI', 'Australia/Adelaide'),
  ('PPR', 'Asia/Jakarta'),
  ('PPY', 'America/Sao_Paulo'),
  ('PQM', 'America/Mexico_City'),
  ('PRB', 'America/Los_Angeles'),
  ('PRX', 'America/Chicago'),
  ('PTT', 'America/Chicago'),
  ('PUK', 'Pacific/Tahiti'),
  ('PUT', 'Asia/Kolkata'),
  ('PWE', 'Asia/Anadyr'),
  ('PWY', 'America/Denver'),
  ('PYB', 'Asia/Kolkata'),
  ('PYK', 'Asia/Tehran'),
  ('PZA', 'America/Bogota'),
  ('PZL', 'Africa/Johannesburg'),
  ('QFG', 'America/Nuuk'),
  ('QGQ', 'America/Nuuk'),
  ('QHP', 'America/Sao_Paulo'),
  ('QJE', 'America/Nuuk'),
  ('QJI', 'America/Nuuk'),
  ('QKX', 'Europe/Oslo'),
  ('QLP', 'Europe/Rome'),
  ('QND', 'Europe/Belgrade'),
  ('QPW', 'America/Nuuk'),
  ('QQT', 'America/Nuuk'),
  ('QRM', 'Australia/Sydney'),
  ('QRR', 'Australia/Sydney'),
  ('QRY', 'America/Nuuk'),
  ('QSI', 'Africa/Dar_es_Salaam'),
  ('QSN', 'America/Havana'),
  ('QSZ', 'Asia/Shanghai'),
  ('QUG', 'Europe/London'),
  ('RAQ', 'Asia/Makassar'),
  ('RCM', 'Australia/Brisbane'),
  ('RDB', 'America/Nome'),
  ('RDP', 'Asia/Kolkata'),
  ('REA', 'Pacific/Tahiti'),
  ('REZ', 'America/Sao_Paulo'),
  ('RHT', 'Asia/Shanghai'),
  ('RHV', 'America/Los_Angeles'),
  ('RIH', 'America/Panama'),
  ('RIJ', 'America/Lima'),
  ('RIZ', 'Asia/Shanghai'),
  ('RJB', 'Asia/Kathmandu'),
  ('RKO', 'Asia/Jakarta'),
  ('RMT', 'Pacific/Tahiti'),
  ('RMU', 'Europe/Madrid'),
  ('RNZ', 'America/Chicago'),
  ('RPM', 'Australia/Darwin'),
  ('RQW', 'Asia/Baghdad'),
  ('RRR', 'Pacific/Tahiti'),
  ('RSL', 'America/Chicago'),
  ('RTC', 'Asia/Kolkata'),
  ('RTN', 'America/Denver'),
  ('RUG', 'Asia/Shanghai'),
  ('RUR', 'Pacific/Tahiti'),
  ('RUV', 'America/Guatemala'),
  ('RWF', 'America/Chicago'),
  ('RZS', 'Asia/Karachi'),
  ('SAG', 'Asia/Kolkata'),
  ('SBH', 'America/St_Barthelemy'),
  ('SBT', 'Asia/Yekaterinburg'),
  ('SFG', 'America/Marigot'),
  ('SGI', 'Asia/Karachi'),
  ('SGQ', 'Asia/Makassar'),
  ('SHO', 'Africa/Mbabane'),
  ('SIO', 'Australia/Hobart'),
  ('SMT', 'America/Cuiaba'),
  ('SNB', 'Australia/Darwin'),
  ('SNJ', 'America/Havana'),
  ('SNS', 'America/Los_Angeles'),
  ('SOV', 'America/Anchorage'),
  ('SPA', 'America/New_York'),
  ('SQA', 'America/Los_Angeles'),
  ('SQD', 'Asia/Shanghai'),
  ('SQJ', 'Asia/Shanghai'),
  ('SQN', 'Asia/Jayapura'),
  ('SQX', 'America/Sao_Paulo'),
  ('SSF', 'America/Chicago'),
  ('SUK', 'Asia/Yakutsk'),
  ('SUP', 'Asia/Jakarta'),
  ('SWC', 'Australia/Melbourne'),
  ('SWH', 'Australia/Melbourne'),
  ('SXE', 'Australia/Melbourne'),
  ('SXJ', 'Asia/Shanghai'),
  ('SXK', 'Asia/Jayapura'),
  ('SXN', 'Africa/Gaborone'),
  ('SZY', 'Europe/Warsaw'),
  ('TBF', 'Pacific/Tarawa'),
  ('TBR', 'America/New_York'),
  ('TDS', 'Pacific/Port_Moresby'),
  ('TEI', 'Asia/Kolkata'),
  ('TEV', 'Europe/Madrid'),
  ('TFL', 'America/Sao_Paulo'),
  ('TGN', 'Australia/Melbourne'),
  ('TGQ', 'America/Cuiaba'),
  ('TJB', 'Asia/Jakarta'),
  ('TKV', 'Pacific/Tahiti'),
  ('TLI', 'Asia/Makassar'),
  ('TLK', 'Asia/Yakutsk'),
  ('TLX', 'America/Santiago'),
  ('TMF', 'Indian/Maldives'),
  ('TMH', 'Asia/Jayapura'),
  ('TNW', 'America/Guayaquil'),
  ('TOI', 'America/Chicago'),
  ('TOQ', 'America/Santiago'),
  ('TPF', 'America/New_York'),
  ('TPH', 'America/Los_Angeles'),
  ('TQL', 'Asia/Yekaterinburg'),
  ('TQS', 'America/Bogota'),
  ('TSM', 'America/Denver'),
  ('TTC', 'America/Santiago'),
  ('TTL', 'Pacific/Fiji'),
  ('TUM', 'Australia/Sydney'),
  ('TXF', 'America/Bahia'),
  ('TYB', 'Australia/Sydney'),
  ('UBT', 'America/Sao_Paulo'),
  ('UCB', 'Asia/Shanghai'),
  ('UGU', 'Asia/Jayapura'),
  ('UKG', 'Asia/Vladivostok'),
  ('UKI', 'America/Los_Angeles'),
  ('UKT', 'America/New_York'),
  ('UOL', 'Asia/Makassar'),
  ('UOX', 'America/Chicago'),
  ('UPL', 'America/Costa_Rica'),
  ('UUN', 'Asia/Ulaanbaatar'),
  ('UZR', 'Asia/Almaty'),
  ('VDI', 'America/New_York'),
  ('VDY', 'Asia/Kolkata'),
  ('VHV', 'Asia/Yakutsk'),
  ('VHZ', 'Pacific/Tahiti'),
  ('VLK', 'Europe/Moscow'),
  ('VLP', 'America/Cuiaba'),
  ('VPZ', 'America/Chicago'),
  ('VTN', 'America/Chicago'),
  ('VYI', 'Asia/Yakutsk'),
  ('WDS', 'Asia/Shanghai'),
  ('WGN', 'Asia/Shanghai'),
  ('WGT', 'Australia/Melbourne'),
  ('WHU', 'Asia/Shanghai'),
  ('WIK', 'Pacific/Auckland'),
  ('WJF', 'America/Los_Angeles'),
  ('WKB', 'Australia/Melbourne'),
  ('WKI', 'Africa/Harare'),
  ('WKR', 'America/Nassau'),
  ('WMB', 'Australia/Melbourne'),
  ('WMC', 'America/Los_Angeles'),
  ('WMH', 'America/Chicago'),
  ('WMT', 'Asia/Shanghai'),
  ('WOS', 'Asia/Pyongyang'),
  ('WPC', 'America/Edmonton'),
  ('WUT', 'Asia/Shanghai'),
  ('WVI', 'America/Los_Angeles'),
  ('WWA', 'America/Anchorage'),
  ('WWR', 'America/Chicago'),
  ('WWY', 'Australia/Sydney'),
  ('XEN', 'Asia/Shanghai'),
  ('XIJ', 'Asia/Kuwait'),
  ('XIQ', 'America/Nuuk'),
  ('XPK', 'America/Winnipeg'),
  ('XPL', 'America/Tegucigalpa'),
  ('XPP', 'America/Winnipeg'),
  ('XRR', 'America/Whitehorse'),
  ('XTO', 'Australia/Brisbane'),
  ('XXN', 'Asia/Riyadh'),
  ('YAH', 'America/Toronto'),
  ('YAL', 'America/Vancouver'),
  ('YAS', 'Pacific/Fiji'),
  ('YBA', 'America/Edmonton'),
  ('YBS', 'America/Winnipeg'),
  ('YCE', 'America/Toronto'),
  ('YCQ', 'America/Dawson_Creek'),
  ('YDG', 'America/Halifax'),
  ('YDO', 'America/Toronto'),
  ('YEY', 'America/Toronto'),
  ('YHE', 'America/Vancouver'),
  ('YHT', 'America/Whitehorse'),
  ('YIE', 'Asia/Shanghai'),
  ('YJF', 'America/Inuvik'),
  ('YJP', 'America/Edmonton'),
  ('YKH', 'Asia/Shanghai'),
  ('YKJ', 'America/Regina'),
  ('YKO', 'Europe/Istanbul'),
  ('YLR', 'America/Winnipeg'),
  ('YME', 'America/Toronto'),
  ('YML', 'America/Toronto'),
  ('YOS', 'America/Toronto'),
  ('YPS', 'America/Glace_Bay'),
  ('YQS', 'America/Toronto'),
  ('YRO', 'America/Toronto'),
  ('YSE', 'America/Vancouver'),
  ('YSG', 'America/Edmonton'),
  ('YSH', 'America/Toronto'),
  ('YSK', 'America/Iqaluit'),
  ('YSL', 'America/Moncton'),
  ('YSN', 'America/Vancouver'),
  ('YSQ', 'Asia/Shanghai'),
  ('YTD', 'America/Winnipeg'),
  ('YUA', 'Asia/Shanghai'),
  ('YVE', 'America/Vancouver'),
  ('YXQ', 'America/Dawson'),
  ('ZBO', 'Australia/Brisbane'),
  ('ZBY', 'Asia/Vientiane'),
  ('ZCO', 'America/Santiago'),
  ('ZGF', 'America/Vancouver'),
  ('ZIC', 'America/Santiago'),
  ('ZIS', 'Africa/Tripoli'),
  ('ZIX', 'Asia/Yakutsk'),
  ('ZJG', 'America/Winnipeg'),
  ('ZQZ', 'Asia/Shanghai'),
  ('ZST', 'America/Vancouver'),
  ('ZTA', 'Pacific/Tahiti'),
  ('ZUC', 'America/Winnipeg'),
  ('ZXT', 'Asia/Baku'),
  ('ZZV', 'America/New_York')
) as v(iata, tz)
where a.iata = v.iata and a.timezone is null;

-- ---------------------------------------------------------------------------
-- Deliberately not changed
-- ---------------------------------------------------------------------------
--
-- China. Fifteen Xinjiang airports (URC, KHG, HTN, AKU, KRL, ...) are recorded as Asia/Shanghai
-- when they geographically fall in Asia/Urumqi, two hours behind. That is left exactly as it is.
-- China runs one official clock nationwide and airlines schedule, publish and board every domestic
-- flight in Beijing time. "Correcting" these would move a Urumqi departure two hours away from
-- what is printed on the passenger's boarding pass. Geographic correctness and flight correctness
-- are not the same thing here, and this app cares about the second one.
--
-- YEU (Eureka, Nunavut). An 80°N research station with no commercial service, whose zone is
-- genuinely disputed between sources. No flight in this app will ever touch it.
--
-- ~650 rows that differ in name only. Asia/Calcutta rather than Asia/Kolkata, Asia/Rangoon rather
-- than Asia/Yangon, Europe/Kiev rather than Europe/Kyiv, America/Godthab rather than America/Nuuk,
-- America/Buenos_Aires rather than America/Argentina/Buenos_Aires, and so on: deprecated aliases
-- that resolve to the identical zone. Also pairs like America/Anchorage against America/Nome, or
-- America/New_York against America/Detroit — distinct entries that have carried identical rules
-- for decades. Rewriting 650 production rows to change nothing observable is risk without benefit.

-- ---------------------------------------------------------------------------
-- flights: carry the corrections through to rows already saved
-- ---------------------------------------------------------------------------
--
-- Correcting the reference table does not move a flight that already copied a value out of it, and
-- nothing else revisits those rows — the poller only rewrites live-tracking fields. So the
-- corrections are pushed through by hand.
--
-- Matched on the OLD value, not just the airport code. A flight holding the stale string is one
-- that copied it from here; a flight holding anything else got its timezone from AeroAPI directly,
-- which is the live source and is left alone. Anything still null is picked up by the same
-- `airports` join the previous migration used, now that the gaps above are filled.

update public.flights f set origin_timezone = v.tz
from (values
  ('ACN', 'America/Mexico_City', 'America/Matamoros'),
  ('AKT', 'Europe/London', 'Asia/Nicosia'),
  ('AVV', 'Australia/Hobart', 'Australia/Melbourne'),
  ('AWK', 'Pacific/Johnston', 'Pacific/Wake'),
  ('BBA', 'America/Santiago', 'America/Coyhaique'),
  ('BSJ', 'Australia/Hobart', 'Australia/Melbourne'),
  ('BUA', 'Pacific/Port_Moresby', 'Pacific/Bougainville'),
  ('BWO', 'Europe/Moscow', 'Europe/Saratov'),
  ('BWT', 'Australia/Melbourne', 'Australia/Hobart'),
  ('BXG', 'Australia/Hobart', 'Australia/Melbourne'),
  ('CCH', 'America/Santiago', 'America/Coyhaique'),
  ('CJS', 'America/Mazatlan', 'America/Ciudad_Juarez'),
  ('CUU', 'America/Mazatlan', 'America/Chihuahua'),
  ('DPO', 'Australia/Melbourne', 'Australia/Hobart'),
  ('ERN', 'America/Boa_Vista', 'America/Eirunepe'),
  ('FEN', 'America/Fortaleza', 'America/Noronha'),
  ('FLS', 'Australia/Melbourne', 'Australia/Hobart'),
  ('GEX', 'Australia/Hobart', 'Australia/Melbourne'),
  ('GXQ', 'America/Santiago', 'America/Coyhaique'),
  ('HBA', 'Australia/Melbourne', 'Australia/Hobart'),
  ('HLT', 'Australia/Hobart', 'Australia/Melbourne'),
  ('KIF', 'America/Toronto', 'America/Winnipeg'),
  ('KNS', 'Australia/Melbourne', 'Australia/Hobart'),
  ('LST', 'Australia/Melbourne', 'Australia/Hobart'),
  ('MAM', 'America/Mexico_City', 'America/Matamoros'),
  ('MBW', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MEB', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MEL', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MHU', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MQL', 'Australia/Hobart', 'Australia/Melbourne'),
  ('NCG', 'America/Mazatlan', 'America/Chihuahua'),
  ('NLD', 'America/Mexico_City', 'America/Matamoros'),
  ('PDS', 'America/Mexico_City', 'America/Matamoros'),
  ('PNT', 'America/Santiago', 'America/Punta_Arenas'),
  ('PTJ', 'Australia/Hobart', 'Australia/Melbourne'),
  ('PUQ', 'America/Santiago', 'America/Punta_Arenas'),
  ('REX', 'America/Mexico_City', 'America/Matamoros'),
  ('RTW', 'Europe/Moscow', 'Europe/Saratov'),
  ('SHT', 'Australia/Hobart', 'Australia/Melbourne'),
  ('SRN', 'Australia/Melbourne', 'Australia/Hobart'),
  ('TBT', 'America/Boa_Vista', 'America/Eirunepe'),
  ('TNM', 'Antarctica/South_Pole', 'America/Punta_Arenas'),
  ('WNN', 'America/Toronto', 'America/Winnipeg'),
  ('WPR', 'America/Santiago', 'America/Punta_Arenas'),
  ('WPU', 'America/Santiago', 'America/Punta_Arenas'),
  ('XKS', 'America/Toronto', 'America/Winnipeg'),
  ('XMC', 'Australia/Hobart', 'Australia/Melbourne'),
  ('YBI', 'America/Halifax', 'America/St_Johns'),
  ('YDA', 'America/Vancouver', 'America/Dawson'),
  ('YDB', 'America/Vancouver', 'America/Dawson'),
  ('YGR', 'America/Toronto', 'America/Halifax'),
  ('YMA', 'America/Vancouver', 'America/Whitehorse'),
  ('YNA', 'America/Toronto', 'America/Blanc-Sablon'),
  ('YOC', 'America/Vancouver', 'America/Dawson'),
  ('YQH', 'America/Vancouver', 'America/Whitehorse'),
  ('YXY', 'America/Vancouver', 'America/Whitehorse'),
  ('YYE', 'America/Vancouver', 'America/Fort_Nelson'),
  ('YZW', 'America/Vancouver', 'America/Whitehorse'),
  ('ZFA', 'America/Vancouver', 'America/Whitehorse')
) as v(iata, old_tz, tz)
where f.origin_iata = v.iata and f.origin_timezone = v.old_tz;

update public.flights f set destination_timezone = v.tz
from (values
  ('ACN', 'America/Mexico_City', 'America/Matamoros'),
  ('AKT', 'Europe/London', 'Asia/Nicosia'),
  ('AVV', 'Australia/Hobart', 'Australia/Melbourne'),
  ('AWK', 'Pacific/Johnston', 'Pacific/Wake'),
  ('BBA', 'America/Santiago', 'America/Coyhaique'),
  ('BSJ', 'Australia/Hobart', 'Australia/Melbourne'),
  ('BUA', 'Pacific/Port_Moresby', 'Pacific/Bougainville'),
  ('BWO', 'Europe/Moscow', 'Europe/Saratov'),
  ('BWT', 'Australia/Melbourne', 'Australia/Hobart'),
  ('BXG', 'Australia/Hobart', 'Australia/Melbourne'),
  ('CCH', 'America/Santiago', 'America/Coyhaique'),
  ('CJS', 'America/Mazatlan', 'America/Ciudad_Juarez'),
  ('CUU', 'America/Mazatlan', 'America/Chihuahua'),
  ('DPO', 'Australia/Melbourne', 'Australia/Hobart'),
  ('ERN', 'America/Boa_Vista', 'America/Eirunepe'),
  ('FEN', 'America/Fortaleza', 'America/Noronha'),
  ('FLS', 'Australia/Melbourne', 'Australia/Hobart'),
  ('GEX', 'Australia/Hobart', 'Australia/Melbourne'),
  ('GXQ', 'America/Santiago', 'America/Coyhaique'),
  ('HBA', 'Australia/Melbourne', 'Australia/Hobart'),
  ('HLT', 'Australia/Hobart', 'Australia/Melbourne'),
  ('KIF', 'America/Toronto', 'America/Winnipeg'),
  ('KNS', 'Australia/Melbourne', 'Australia/Hobart'),
  ('LST', 'Australia/Melbourne', 'Australia/Hobart'),
  ('MAM', 'America/Mexico_City', 'America/Matamoros'),
  ('MBW', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MEB', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MEL', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MHU', 'Australia/Hobart', 'Australia/Melbourne'),
  ('MQL', 'Australia/Hobart', 'Australia/Melbourne'),
  ('NCG', 'America/Mazatlan', 'America/Chihuahua'),
  ('NLD', 'America/Mexico_City', 'America/Matamoros'),
  ('PDS', 'America/Mexico_City', 'America/Matamoros'),
  ('PNT', 'America/Santiago', 'America/Punta_Arenas'),
  ('PTJ', 'Australia/Hobart', 'Australia/Melbourne'),
  ('PUQ', 'America/Santiago', 'America/Punta_Arenas'),
  ('REX', 'America/Mexico_City', 'America/Matamoros'),
  ('RTW', 'Europe/Moscow', 'Europe/Saratov'),
  ('SHT', 'Australia/Hobart', 'Australia/Melbourne'),
  ('SRN', 'Australia/Melbourne', 'Australia/Hobart'),
  ('TBT', 'America/Boa_Vista', 'America/Eirunepe'),
  ('TNM', 'Antarctica/South_Pole', 'America/Punta_Arenas'),
  ('WNN', 'America/Toronto', 'America/Winnipeg'),
  ('WPR', 'America/Santiago', 'America/Punta_Arenas'),
  ('WPU', 'America/Santiago', 'America/Punta_Arenas'),
  ('XKS', 'America/Toronto', 'America/Winnipeg'),
  ('XMC', 'Australia/Hobart', 'Australia/Melbourne'),
  ('YBI', 'America/Halifax', 'America/St_Johns'),
  ('YDA', 'America/Vancouver', 'America/Dawson'),
  ('YDB', 'America/Vancouver', 'America/Dawson'),
  ('YGR', 'America/Toronto', 'America/Halifax'),
  ('YMA', 'America/Vancouver', 'America/Whitehorse'),
  ('YNA', 'America/Toronto', 'America/Blanc-Sablon'),
  ('YOC', 'America/Vancouver', 'America/Dawson'),
  ('YQH', 'America/Vancouver', 'America/Whitehorse'),
  ('YXY', 'America/Vancouver', 'America/Whitehorse'),
  ('YYE', 'America/Vancouver', 'America/Fort_Nelson'),
  ('YZW', 'America/Vancouver', 'America/Whitehorse'),
  ('ZFA', 'America/Vancouver', 'America/Whitehorse')
) as v(iata, old_tz, tz)
where f.destination_iata = v.iata and f.destination_timezone = v.old_tz;

update public.flights f set origin_timezone = a.timezone
from public.airports a
where f.origin_timezone is null and a.timezone is not null
  and (a.iata = f.origin_iata or a.icao = f.origin_icao);

update public.flights f set destination_timezone = a.timezone
from public.airports a
where f.destination_timezone is null and a.timezone is not null
  and (a.iata = f.destination_iata or a.icao = f.destination_icao);
