-- Adds 138 new Plus-tier "Who's More Likely To" prompts spread across the 10 shared topic categories.

insert into public.more_likely_prompts (prompt, category, tier) values
  ('Who is more likely to start singing along to a song within the first ten seconds?', 'Starters', 'plus'),
  ('Who is more likely to laugh at their own joke before finishing it?', 'Starters', 'plus'),
  ('Who is more likely to win a staring contest?', 'Starters', 'plus'),
  ('Who is more likely to fall asleep during a movie?', 'Starters', 'plus'),
  ('Who is more likely to talk to a pet like it understands full sentences?', 'Starters', 'plus'),
  ('Who is more likely to do a silly dance in the kitchen?', 'Starters', 'plus'),
  ('Who is more likely to lose track of time scrolling on their phone?', 'Starters', 'plus'),
  ('Who is more likely to answer a question with another question?', 'Starters', 'plus'),
  ('Who is more likely to hum without realizing it?', 'Starters', 'plus'),
  ('Who is more likely to jump at a loud noise?', 'Starters', 'plus'),
  ('Who is more likely to take the last slice without asking?', 'Starters', 'plus'),
  ('Who is more likely to win at a game of charades?', 'Starters', 'plus'),
  ('Who is more likely to burst out laughing at the wrong moment?', 'Starters', 'plus'),
  ('Who is more likely to talk with their hands?', 'Starters', 'plus'),
  ('Who is more likely to know all the words to a cheesy pop song?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to know their neighbors'' names?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to remember a stranger''s name after one meeting?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have a hidden talent nobody knows about?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to still be in touch with a childhood friend?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have a strong opinion about pineapple on pizza?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to know their own blood type off the top of their head?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have a favorite fictional character they still talk about?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to remember the plot of a movie they watched years ago?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have a go-to karaoke song ready at all times?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to correct someone''s grammar mid-conversation?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have strong feelings about the correct way to load a dishwasher?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to know their star sign and everyone else''s?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to have a secret talent for impressions?', 'Get to Know Each Other', 'plus'),
  ('Who is more likely to say "I love you" first?', 'Relationship', 'plus'),
  ('Who is more likely to initiate making up after a small disagreement?', 'Relationship', 'plus'),
  ('Who is more likely to plan a surprise for the other?', 'Relationship', 'plus'),
  ('Who is more likely to remember the exact date of your first date?', 'Relationship', 'plus'),
  ('Who is more likely to send a random "thinking of you" text mid-day?', 'Relationship', 'plus'),
  ('Who is more likely to steal the blankets at night?', 'Relationship', 'plus'),
  ('Who is more likely to fall asleep first during a movie night?', 'Relationship', 'plus'),
  ('Who is more likely to start a playful debate just for fun?', 'Relationship', 'plus'),
  ('Who is more likely to save a funny meme to send later?', 'Relationship', 'plus'),
  ('Who is more likely to suggest trying a new hobby together?', 'Relationship', 'plus'),
  ('Who is more likely to give an over-the-top compliment out of nowhere?', 'Relationship', 'plus'),
  ('Who is more likely to plan the perfect date night?', 'Relationship', 'plus'),
  ('Who is more likely to remember how you two met, down to the details?', 'Relationship', 'plus'),
  ('Who is more likely to want to slow dance in the kitchen for no reason?', 'Relationship', 'plus'),
  ('Who is more likely to keep an old ticket stub or memento from a trip?', 'Relationship', 'plus'),
  ('Who is more likely to insist on a window seat?', 'Travel', 'plus'),
  ('Who is more likely to pack snacks for everyone before a trip?', 'Travel', 'plus'),
  ('Who is more likely to build a color-coded itinerary?', 'Travel', 'plus'),
  ('Who is more likely to strike up a friendship with someone at the airport?', 'Travel', 'plus'),
  ('Who is more likely to check in online the second it opens?', 'Travel', 'plus'),
  ('Who is more likely to buy a souvenir magnet in every city?', 'Travel', 'plus'),
  ('Who is more likely to nap the moment the car starts moving?', 'Travel', 'plus'),
  ('Who is more likely to insist on visiting one more museum?', 'Travel', 'plus'),
  ('Who is more likely to lose the hotel key card?', 'Travel', 'plus'),
  ('Who is more likely to plan a whole day around finding one specific restaurant?', 'Travel', 'plus'),
  ('Who is more likely to keep every boarding pass as a keepsake?', 'Travel', 'plus'),
  ('Who is more likely to be ready to leave for the airport hours early?', 'Travel', 'plus'),
  ('Who is more likely to learn a few phrases of the local language before a trip?', 'Travel', 'plus'),
  ('Who is more likely to want to explore somewhere with no plan at all?', 'Travel', 'plus'),
  ('Who is more likely to ask for extra sauce on the side?', 'Food & Culture', 'plus'),
  ('Who is more likely to finish their plate before the other starts?', 'Food & Culture', 'plus'),
  ('Who is more likely to recreate a restaurant dish at home?', 'Food & Culture', 'plus'),
  ('Who is more likely to steal food off the other''s plate?', 'Food & Culture', 'plus'),
  ('Who is more likely to insist on trying the local specialty wherever you go?', 'Food & Culture', 'plus'),
  ('Who is more likely to have a go-to comfort food?', 'Food & Culture', 'plus'),
  ('Who is more likely to send back a dish that isn''t quite right?', 'Food & Culture', 'plus'),
  ('Who is more likely to spend twenty minutes deciding what to order?', 'Food & Culture', 'plus'),
  ('Who is more likely to know how to make a great cup of coffee?', 'Food & Culture', 'plus'),
  ('Who is more likely to add too much spice to a dish?', 'Food & Culture', 'plus'),
  ('Who is more likely to insist on cooking a fancy meal from scratch?', 'Food & Culture', 'plus'),
  ('Who is more likely to know the best local bakery in town?', 'Food & Culture', 'plus'),
  ('Who is more likely to remember everyone''s birthday without a reminder?', 'Family', 'plus'),
  ('Who is more likely to organize a family get-together?', 'Family', 'plus'),
  ('Who is more likely to be the favorite when visiting family?', 'Family', 'plus'),
  ('Who is more likely to call a parent just to chat?', 'Family', 'plus'),
  ('Who is more likely to bring a homemade dish to a family gathering?', 'Family', 'plus'),
  ('Who is more likely to remember a funny family story in perfect detail?', 'Family', 'plus'),
  ('Who is more likely to start a friendly game night with family?', 'Family', 'plus'),
  ('Who is more likely to take the most photos at a family event?', 'Family', 'plus'),
  ('Who is more likely to be roped into helping with a family project?', 'Family', 'plus'),
  ('Who is more likely to plan a family trip everyone actually enjoys?', 'Family', 'plus'),
  ('Who is more likely to know every family member''s favorite dessert?', 'Family', 'plus'),
  ('Who is more likely to keep old family photos organized?', 'Family', 'plus'),
  ('Who is more likely to be the go-to for family advice?', 'Family', 'plus'),
  ('Who is more likely to remember to send a thank-you card?', 'Family', 'plus'),
  ('Who is more likely to find a great deal while shopping?', 'Money & Finances', 'plus'),
  ('Who is more likely to keep a running mental list of what things cost?', 'Money & Finances', 'plus'),
  ('Who is more likely to treat the other to something unexpected?', 'Money & Finances', 'plus'),
  ('Who is more likely to compare prices across three different stores?', 'Money & Finances', 'plus'),
  ('Who is more likely to set up a savings goal for something fun?', 'Money & Finances', 'plus'),
  ('Who is more likely to use a coupon at checkout?', 'Money & Finances', 'plus'),
  ('Who is more likely to splurge on something small but nice?', 'Money & Finances', 'plus'),
  ('Who is more likely to track expenses in a spreadsheet just for fun?', 'Money & Finances', 'plus'),
  ('Who is more likely to suggest a fun but budget-friendly date idea?', 'Money & Finances', 'plus'),
  ('Who is more likely to spot a subscription that''s no longer being used?', 'Money & Finances', 'plus'),
  ('Who is more likely to round up a bill and leave a generous tip?', 'Money & Finances', 'plus'),
  ('Who is more likely to plan a surprise gift months in advance?', 'Money & Finances', 'plus'),
  ('Who is more likely to celebrate finding a bargain like it''s a big win?', 'Money & Finances', 'plus'),
  ('Who is more likely to return extra change a cashier gave by mistake?', 'Moral Values', 'plus'),
  ('Who is more likely to stop and help a stranger carry something heavy?', 'Moral Values', 'plus'),
  ('Who is more likely to speak up when someone is being treated unfairly?', 'Moral Values', 'plus'),
  ('Who is more likely to give up their seat on a crowded bus or train?', 'Moral Values', 'plus'),
  ('Who is more likely to hand in a lost wallet found on the street?', 'Moral Values', 'plus'),
  ('Who is more likely to compliment a stranger for no reason?', 'Moral Values', 'plus'),
  ('Who is more likely to volunteer for a good cause?', 'Moral Values', 'plus'),
  ('Who is more likely to hold the door for everyone in a long line?', 'Moral Values', 'plus'),
  ('Who is more likely to admit they were wrong first?', 'Moral Values', 'plus'),
  ('Who is more likely to leave a glowing review for a small local business?', 'Moral Values', 'plus'),
  ('Who is more likely to let someone go ahead of them in line?', 'Moral Values', 'plus'),
  ('Who is more likely to point out when a bill was undercharged?', 'Moral Values', 'plus'),
  ('Who is more likely to defend a friend who isn''t in the room?', 'Moral Values', 'plus'),
  ('Who is more likely to pick up litter on a walk without being asked?', 'Moral Values', 'plus'),
  ('Who is more likely to start a new hobby on a whim?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to go for an early morning run?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to binge an entire show in one weekend?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to have a growing collection of something quirky?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to try a DIY project without a tutorial?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to spend a whole afternoon reading?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to sign up for a random class just to try it?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to rearrange the furniture on a random Sunday?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to keep a journal or diary?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to know the lyrics to every song on their playlist?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to spend too long picking a paint color?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to get really into a new video game?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to take up gardening?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to plan a whole weekend around one hobby?', 'Hobbies & Lifestyle', 'plus'),
  ('Who is more likely to bring up a tough topic first?', 'Deep Conversations', 'plus'),
  ('Who is more likely to gently push for how the other is really feeling?', 'Deep Conversations', 'plus'),
  ('Who is more likely to remember a meaningful conversation from years ago?', 'Deep Conversations', 'plus'),
  ('Who is more likely to notice when the other is having an off day?', 'Deep Conversations', 'plus'),
  ('Who is more likely to bring up future goals during a quiet moment?', 'Deep Conversations', 'plus'),
  ('Who is more likely to sit with a hard feeling before talking about it?', 'Deep Conversations', 'plus'),
  ('Who is more likely to ask a big "what if" question out of nowhere?', 'Deep Conversations', 'plus'),
  ('Who is more likely to say what they''re grateful for unprompted?', 'Deep Conversations', 'plus'),
  ('Who is more likely to want to talk things through late into the night?', 'Deep Conversations', 'plus'),
  ('Who is more likely to reflect out loud after finishing a good book or film?', 'Deep Conversations', 'plus'),
  ('Who is more likely to bring up a childhood memory that shaped who they are?', 'Deep Conversations', 'plus'),
  ('Who is more likely to ask thoughtful follow-up questions in a conversation?', 'Deep Conversations', 'plus'),
  ('Who is more likely to notice a shift in the other''s mood before they say anything?', 'Deep Conversations', 'plus'),
  ('Who is more likely to bring up a dream they had and want to unpack it?', 'Deep Conversations', 'plus');
