-- Seed premium-tier discussion topics for "Discuss Before Travelling" / Daily Activity (140 rows across 10 categories)
insert into public.discussion_topics (topic, category, tier) values
  ('What''s a small moment from today that made you smile?', 'Starters', 'premium'),
  ('What''s one thing about our relationship you''d want a stranger to know?', 'Starters', 'premium'),
  ('What''s your favorite way to spend a lazy Sunday together?', 'Starters', 'premium'),
  ('What''s a song that instantly reminds you of us?', 'Starters', 'premium'),
  ('What''s something you''ve been looking forward to lately?', 'Starters', 'premium'),
  ('What''s a tradition, big or small, that we''ve created together?', 'Starters', 'premium'),
  ('What''s your favorite memory from the past month?', 'Starters', 'premium'),
  ('What''s one thing that always makes you laugh, no matter how many times you''ve heard it?', 'Starters', 'premium'),
  ('What''s a compliment you''ve received recently that stuck with you?', 'Starters', 'premium'),
  ('What''s something new you''d like to try together this year?', 'Starters', 'premium'),
  ('What''s your idea of a perfect low-key evening together?', 'Starters', 'premium'),
  ('What''s a smell or taste that instantly takes you back to a happy memory?', 'Starters', 'premium'),
  ('What''s something small I do that you don''t think I realize you notice?', 'Starters', 'premium'),
  ('What''s a word or phrase you think describes us as a couple?', 'Starters', 'premium'),
  ('What''s a belief you held strongly as a kid that you''ve since changed your mind about?', 'Get to Know Each Other', 'premium'),
  ('What part of your personality do you think comes from your upbringing?', 'Get to Know Each Other', 'premium'),
  ('What''s something you''re proud of that most people don''t know about?', 'Get to Know Each Other', 'premium'),
  ('What''s a skill you wish you''d learned earlier in life?', 'Get to Know Each Other', 'premium'),
  ('How would you describe yourself to someone who''s never met you?', 'Get to Know Each Other', 'premium'),
  ('What''s a fear you''ve overcome, and how did you do it?', 'Get to Know Each Other', 'premium'),
  ('What''s something you believed about love before we met that''s different now?', 'Get to Know Each Other', 'premium'),
  ('What''s a decision in your life you''re especially glad you made?', 'Get to Know Each Other', 'premium'),
  ('What''s a habit or quirk you''ve had since childhood?', 'Get to Know Each Other', 'premium'),
  ('What''s something about yourself you''re still figuring out?', 'Get to Know Each Other', 'premium'),
  ('What''s a story from your past that you think explains a lot about who you are?', 'Get to Know Each Other', 'premium'),
  ('What''s a value you inherited from your family that you want to keep?', 'Get to Know Each Other', 'premium'),
  ('What''s something you used to want out of life that you no longer want?', 'Get to Know Each Other', 'premium'),
  ('What''s a moment that changed how you see the world?', 'Get to Know Each Other', 'premium'),
  ('How do we each show love in ways the other might not immediately recognize?', 'Relationship', 'premium'),
  ('What helps you feel most understood when we disagree?', 'Relationship', 'premium'),
  ('How do we want to handle it when one of us needs space?', 'Relationship', 'premium'),
  ('What''s something you''ve learned about communication from being with me?', 'Relationship', 'premium'),
  ('How do we want to celebrate the milestones in our relationship?', 'Relationship', 'premium'),
  ('What does feeling secure in our relationship look like for you?', 'Relationship', 'premium'),
  ('How do we balance giving each other honesty and giving each other kindness?', 'Relationship', 'premium'),
  ('What''s a moment when you felt especially proud to be with me?', 'Relationship', 'premium'),
  ('How do we want to grow as a couple over the next few years?', 'Relationship', 'premium'),
  ('What''s something we do well as a team that we don''t give ourselves credit for?', 'Relationship', 'premium'),
  ('How do you like to be comforted when you''re having a hard day?', 'Relationship', 'premium'),
  ('What does trust look like to you in practice, day to day?', 'Relationship', 'premium'),
  ('How do we want to keep things playful as time goes on?', 'Relationship', 'premium'),
  ('What''s something you need from me during a conflict that you don''t always ask for?', 'Relationship', 'premium'),
  ('What does a "successful" trip look like to you, beyond just seeing the sights?', 'Travel', 'premium'),
  ('What''s a place you''ve always dreamed of going, and why does it call to you?', 'Travel', 'premium'),
  ('How do you like to feel during a trip — relaxed, adventurous, immersed, something else?', 'Travel', 'premium'),
  ('What''s a travel memory that changed how you see the world?', 'Travel', 'premium'),
  ('How do we want to balance planning ahead versus staying spontaneous?', 'Travel', 'premium'),
  ('What''s something about a different culture you''d love to experience firsthand together?', 'Travel', 'premium'),
  ('How do we want to document our trips so we remember them well?', 'Travel', 'premium'),
  ('What''s a type of trip we haven''t taken yet that you''d love to try?', 'Travel', 'premium'),
  ('How do you feel about traveling somewhere completely unfamiliar versus somewhere comfortable?', 'Travel', 'premium'),
  ('What''s a small travel ritual that would make trips feel more like "ours"?', 'Travel', 'premium'),
  ('How do we want to handle it when a trip doesn''t go as planned?', 'Travel', 'premium'),
  ('What''s a place from your past you''d love to show me one day?', 'Travel', 'premium'),
  ('How important is it to you to travel with a purpose, like volunteering or learning something new?', 'Travel', 'premium'),
  ('What would our dream once-in-a-lifetime trip look like?', 'Travel', 'premium'),
  ('What''s a meal that feels like home to you?', 'Food & Culture', 'premium'),
  ('What''s a family recipe or dish you''d want to pass down?', 'Food & Culture', 'premium'),
  ('What''s a food memory from your childhood that still means something to you?', 'Food & Culture', 'premium'),
  ('How do you like celebrating holidays that matter to your family or culture?', 'Food & Culture', 'premium'),
  ('What''s a cuisine you''d love for us to learn to cook together?', 'Food & Culture', 'premium'),
  ('What''s a cultural tradition of yours you''d want me to understand better?', 'Food & Culture', 'premium'),
  ('What role does food play in how your family shows love?', 'Food & Culture', 'premium'),
  ('What''s a dish you''d love to recreate from a trip we''ve taken?', 'Food & Culture', 'premium'),
  ('How do we want to blend or celebrate our different backgrounds together?', 'Food & Culture', 'premium'),
  ('What''s a meal or moment around food that felt especially meaningful with me?', 'Food & Culture', 'premium'),
  ('What''s something about your culture you''re proud of and want to share more of?', 'Food & Culture', 'premium'),
  ('What''s a food you disliked growing up that you''ve come to love?', 'Food & Culture', 'premium'),
  ('How do you like to celebrate a special occasion — with a big gathering or something quiet?', 'Food & Culture', 'premium'),
  ('What''s a tradition from either of our families we might want to create for ourselves?', 'Food & Culture', 'premium'),
  ('What''s a value from your family you''d want to carry into our life together?', 'Family', 'premium'),
  ('How has your relationship with your family shaped how you show up in ours?', 'Family', 'premium'),
  ('What does "family" mean to you beyond blood relatives?', 'Family', 'premium'),
  ('What''s a family tradition, or lack of one, you''d want us to think about together?', 'Family', 'premium'),
  ('How do we want to support each other''s families going forward?', 'Family', 'premium'),
  ('What''s something you admired about how you were raised?', 'Family', 'premium'),
  ('What''s something you''d want to do differently from how you were raised, if anything?', 'Family', 'premium'),
  ('How do you feel about the idea of building a family of our own, in whatever form that takes?', 'Family', 'premium'),
  ('What role do friends play in your idea of "family"?', 'Family', 'premium'),
  ('What''s a memory with your family that you cherish most?', 'Family', 'premium'),
  ('How do we want to navigate differences between our families'' expectations?', 'Family', 'premium'),
  ('What''s something you hope our life together looks like in terms of family closeness?', 'Family', 'premium'),
  ('How do you want us to handle holidays and time split between families?', 'Family', 'premium'),
  ('What''s a lesson a family member taught you that still guides you?', 'Family', 'premium'),
  ('What does financial security actually feel like to you, not just look like?', 'Money & Finances', 'premium'),
  ('How did the way your family talked, or didn''t talk, about money shape you?', 'Money & Finances', 'premium'),
  ('What''s a financial goal you''d love for us to work toward together?', 'Money & Finances', 'premium'),
  ('How do you feel about combining finances versus keeping things separate?', 'Money & Finances', 'premium'),
  ('What''s something you''d love to save up for as a couple?', 'Money & Finances', 'premium'),
  ('How do we want to handle it when one of us wants to spend and the other wants to save?', 'Money & Finances', 'premium'),
  ('What does financial freedom mean to you personally?', 'Money & Finances', 'premium'),
  ('How do you feel about debt, and how do you want us to approach it together?', 'Money & Finances', 'premium'),
  ('What''s a splurge you don''t regret, and why did it feel worth it?', 'Money & Finances', 'premium'),
  ('How do we want to think about generosity, like gifts or giving, as a couple?', 'Money & Finances', 'premium'),
  ('What''s your instinct when money feels tight — cut back or find more income?', 'Money & Finances', 'premium'),
  ('How important is financial independence to you within our relationship?', 'Money & Finances', 'premium'),
  ('What''s a money habit of mine you appreciate or would love for me to adopt?', 'Money & Finances', 'premium'),
  ('How do we want to plan for big future costs together?', 'Money & Finances', 'premium'),
  ('What''s a value you''d never want to compromise on, no matter the circumstances?', 'Moral Values', 'premium'),
  ('How do you decide what''s right when the answer isn''t obvious?', 'Moral Values', 'premium'),
  ('What''s a cause or issue you feel strongly about, and why?', 'Moral Values', 'premium'),
  ('How do you want us to handle it when we disagree on something important?', 'Moral Values', 'premium'),
  ('What does integrity mean to you in daily life?', 'Moral Values', 'premium'),
  ('What''s a time you stood up for something you believed in?', 'Moral Values', 'premium'),
  ('How do you want to raise the people around you up, in small everyday ways?', 'Moral Values', 'premium'),
  ('What''s something you think the world needs more of?', 'Moral Values', 'premium'),
  ('How do you decide when to speak up versus let something go?', 'Moral Values', 'premium'),
  ('What''s a principle you try to live by, even when it''s inconvenient?', 'Moral Values', 'premium'),
  ('How do you want us to model our values to the people around us?', 'Moral Values', 'premium'),
  ('What''s something you''ve changed your mind about after really listening to someone?', 'Moral Values', 'premium'),
  ('How do you think about forgiveness, both giving and receiving it?', 'Moral Values', 'premium'),
  ('What does living a good life mean to you?', 'Moral Values', 'premium'),
  ('What''s a hobby you''d love to get better at together?', 'Hobbies & Lifestyle', 'premium'),
  ('How do you like to unwind after a long week?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s something you do just for yourself that you''d love me to understand better?', 'Hobbies & Lifestyle', 'premium'),
  ('What does a balanced life look like to you?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s a skill or hobby from your past you''d love to pick back up?', 'Hobbies & Lifestyle', 'premium'),
  ('How do you feel about trying new hobbies versus sticking with what you know you enjoy?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s something creative you''d love to explore, even if you''re not "good" at it?', 'Hobbies & Lifestyle', 'premium'),
  ('How much downtime do you need to feel like yourself?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s a hobby of mine you''ve come to enjoy because of me?', 'Hobbies & Lifestyle', 'premium'),
  ('How do you like to spend a day with absolutely nothing planned?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s something physical or active you''d love for us to try together?', 'Hobbies & Lifestyle', 'premium'),
  ('How do we want to make space for our individual interests alongside shared ones?', 'Hobbies & Lifestyle', 'premium'),
  ('What''s a book, show, or piece of art that changed how you think?', 'Hobbies & Lifestyle', 'premium'),
  ('What does an ideal weekly rhythm look like for you?', 'Hobbies & Lifestyle', 'premium'),
  ('What does a meaningful life look like to you, ten years from now?', 'Deep Conversations', 'premium'),
  ('What''s something you''re still healing from, and how can I support that?', 'Deep Conversations', 'premium'),
  ('What''s a fear about the future you don''t talk about often?', 'Deep Conversations', 'premium'),
  ('What do you think you''ve taught me, just by being who you are?', 'Deep Conversations', 'premium'),
  ('What''s something about yourself you''re actively working to grow?', 'Deep Conversations', 'premium'),
  ('What does it mean to you to truly be seen by someone?', 'Deep Conversations', 'premium'),
  ('What''s a moment with me you''ll carry with you for the rest of your life?', 'Deep Conversations', 'premium'),
  ('What do you hope people remember about you?', 'Deep Conversations', 'premium'),
  ('What''s something you need to hear more often, from me or anyone?', 'Deep Conversations', 'premium'),
  ('How do you want to be supported when life feels overwhelming?', 'Deep Conversations', 'premium'),
  ('What''s a hope you have for us that you''ve never said out loud?', 'Deep Conversations', 'premium'),
  ('What does it mean to you to grow old together?', 'Deep Conversations', 'premium'),
  ('What''s something you''re grateful for about the timing of how we met?', 'Deep Conversations', 'premium'),
  ('What do you want our love to have meant, looking back on it someday?', 'Deep Conversations', 'premium');
