-- Another 450 daily questions, taking the bank past three years.
--
-- 20261103000000 brought it to 682, about one year and eleven months. This adds the rest of the
-- runway asked for: 1,132 in total, a little over three years at one a day, and long enough that
-- the repeat behaviour in get_daily_question_session is a genuine backstop rather than something
-- couples will meet.
--
-- Same constraints as that migration, and worth restating because they are what makes these usable
-- as *daily* questions rather than deck prompts:
--
--   * Each stands alone. Selection is random, so nothing can lean on a previous question. Two of
--     these were drafted as follow-ups and rewritten once the screen caught them, which is the same
--     mistake and the same count as last time — it is an easy one to make when writing in themed
--     runs.
--   * Both partners answer separately and compare, so nothing asks them to decide together.
--   * Nothing assumes being in the same place.
--
-- One new category: "Work & Purpose". Work is most of most people's waking life and the bank had
-- almost nothing on it — not ambition, not what a good day's work feels like, not how two careers
-- are supposed to fit around a relationship conducted across a distance.
--
-- Guarded on the question text, as before, so a re-run inserts nothing and a Studio edit survives a
-- later deploy.

insert into public.daily_questions (question, category)
select v.question, v.category
from (values
  ('What''s the worst bit of a travel day to see me?', 'Distance & Reunion'),
  ('What do you tell people who ask how we manage?', 'Distance & Reunion'),
  ('What''s a question about us you''re tired of being asked?', 'Distance & Reunion'),
  ('How do you feel in the days right after I leave?', 'Distance & Reunion'),
  ('What''s something you do differently when I''m visiting?', 'Distance & Reunion'),
  ('What would you want waiting for you when you arrive?', 'Distance & Reunion'),
  ('What''s a time zone problem we''ve never solved?', 'Distance & Reunion'),
  ('How do you feel about video calls, honestly?', 'Distance & Reunion'),
  ('What''s better said on a call than in a message?', 'Distance & Reunion'),
  ('What''s a plan we keep postponing?', 'Distance & Reunion'),
  ('What''s a practical obstacle to closing the distance that we avoid discussing?', 'Distance & Reunion'),
  ('Who would move, if it came to it?', 'Distance & Reunion'),
  ('What would you need from a city to be happy living there?', 'Distance & Reunion'),
  ('What''s the longest we should go without seeing each other?', 'Distance & Reunion'),
  ('What do you do with the space I''m not filling?', 'Distance & Reunion'),
  ('What''s a friendship that''s got stronger because I''m not around?', 'Distance & Reunion'),
  ('How do you want us to handle a visit that goes badly?', 'Distance & Reunion'),
  ('What''s something about my life here you''d like to understand better?', 'Distance & Reunion'),
  ('What''s the last thing you did that you knew I''d love?', 'Distance & Reunion'),
  ('What''s a milestone of yours I''ve missed that still stings?', 'Distance & Reunion'),
  ('What would make the goodbyes easier?', 'Distance & Reunion'),
  ('What''s your honest view of how much longer this should go on?', 'Distance & Reunion'),
  ('What''s a small object of mine you keep nearby?', 'Distance & Reunion'),
  ('How do you feel when I''m out and you''re not?', 'Distance & Reunion'),
  ('What''s something you want to do together that needs more than a weekend?', 'Distance & Reunion'),
  ('What''s the most romantic thing distance has made possible?', 'Distance & Reunion'),
  ('What''s a compromise on where we live you could genuinely accept?', 'Distance & Reunion'),
  ('What do you want our first shared home to have?', 'Distance & Reunion'),
  ('What''s a fear about living together you haven''t mentioned?', 'Distance & Reunion'),
  ('What would you miss about your own space?', 'Distance & Reunion'),
  ('What''s been the highlight of your week so far?', 'Starters'),
  ('What''s something you''re dreading slightly?', 'Starters'),
  ('What''s the weather doing where you are, and how''s it affecting you?', 'Starters'),
  ('What did you have for breakfast?', 'Starters'),
  ('What''s the last photo you took?', 'Starters'),
  ('What''s a small errand you''re glad you finally did?', 'Starters'),
  ('What''s on your list for this weekend?', 'Starters'),
  ('What''s a conversation you had today that stuck?', 'Starters'),
  ('What do you wish you''d said this week?', 'Starters'),
  ('What are you reading, watching or listening to?', 'Starters'),
  ('What''s a thing you''ve spent too long thinking about lately?', 'Starters'),
  ('Who did you speak to this week that you don''t often?', 'Starters'),
  ('What''s the state of your inbox?', 'Starters'),
  ('What''s something you bought recently that you''re pleased with?', 'Starters'),
  ('What time did you actually get up?', 'Starters'),
  ('What''s the best thing about today?', 'Starters'),
  ('What''s a plan you''re quietly hoping gets cancelled?', 'Starters'),
  ('What''s the nicest place you''ve been this week?', 'Starters'),
  ('What''s one thing you''d change about your routine right now?', 'Starters'),
  ('What made you sigh today?', 'Starters'),
  ('What''s a task you keep rewriting on your list?', 'Starters'),
  ('What are you eating too much of at the moment?', 'Starters'),
  ('What did you do yesterday that was just for you?', 'Starters'),
  ('What''s the last thing you learned by accident?', 'Starters'),
  ('What''s a person you''ve been meaning to message?', 'Starters'),
  ('What''s the mood of your week in one word?', 'Starters'),
  ('What''s something good coming up that you forgot about?', 'Starters'),
  ('What''s the last thing you finished?', 'Starters'),
  ('What''s the smallest thing that would improve tomorrow?', 'Starters'),
  ('What have you been putting off saying?', 'Starters'),
  ('What''s a place you''d go to be completely alone?', 'Get to Know Each Other'),
  ('What''s the thing you''re most stubborn about?', 'Get to Know Each Other'),
  ('How do you react when plans change at the last minute?', 'Get to Know Each Other'),
  ('What''s a subject you''d happily study for a year?', 'Get to Know Each Other'),
  ('What''s your relationship with being wrong?', 'Get to Know Each Other'),
  ('What''s a superstition or habit you can''t shake?', 'Get to Know Each Other'),
  ('What''s the first thing you notice about a room?', 'Get to Know Each Other'),
  ('What do you do when you can''t sleep?', 'Get to Know Each Other'),
  ('What''s the last time you cried, if you''re willing to say?', 'Get to Know Each Other'),
  ('What''s something you''ve never told anyone because it seemed too small?', 'Get to Know Each Other'),
  ('What kind of humour do you actually find funny?', 'Get to Know Each Other'),
  ('What''s a possession that means more than it should?', 'Get to Know Each Other'),
  ('How do you feel about surprises?', 'Get to Know Each Other'),
  ('What''s something you''d want a stranger to know about you?', 'Get to Know Each Other'),
  ('What''s a role you play that isn''t really you?', 'Get to Know Each Other'),
  ('What do you do to feel in control?', 'Get to Know Each Other'),
  ('What''s a compliment about your character you''d most like to hear?', 'Get to Know Each Other'),
  ('What''s an ordinary thing you find genuinely beautiful?', 'Get to Know Each Other'),
  ('How do you handle being disliked?', 'Get to Know Each Other'),
  ('What''s a sound or smell that changes your mood instantly?', 'Get to Know Each Other'),
  ('What''s your instinct in an emergency?', 'Get to Know Each Other'),
  ('What do you find hardest to say out loud?', 'Get to Know Each Other'),
  ('What''s an opinion of yours that''s got quieter over time?', 'Get to Know Each Other'),
  ('What''s something you''re secretly competitive about?', 'Get to Know Each Other'),
  ('What''s your relationship with routine?', 'Get to Know Each Other'),
  ('What''s a piece of advice you give often?', 'Get to Know Each Other'),
  ('Do you take it yourself?', 'Get to Know Each Other'),
  ('What''s a small act that makes you trust someone?', 'Get to Know Each Other'),
  ('What''s something you notice that most people don''t?', 'Get to Know Each Other'),
  ('What''s the thing you most want to be understood about?', 'Get to Know Each Other'),
  ('What''s something I worry about that you think I shouldn''t?', 'Relationship'),
  ('How do you want me to tell you when something''s bothering me?', 'Relationship'),
  ('What''s a way we could be kinder to each other when tired?', 'Relationship'),
  ('What do you think I misunderstand about you?', 'Relationship'),
  ('What''s a strength of mine you''d like me to use more?', 'Relationship'),
  ('When do you feel most like a team with me?', 'Relationship'),
  ('What''s a conversation we should have had by now?', 'Relationship'),
  ('What does commitment mean to you in practice, not in principle?', 'Relationship'),
  ('What''s something you do for me that you''d like noticed?', 'Relationship'),
  ('How should we handle it when one of us is doing much worse than the other?', 'Relationship'),
  ('What''s a habit of mine you''ve quietly got used to?', 'Relationship'),
  ('What''s a habit of mine you''d rather I dropped?', 'Relationship'),
  ('What do you need from me on a bad day that isn''t advice?', 'Relationship'),
  ('What''s a way we avoid conflict that isn''t healthy?', 'Relationship'),
  ('What would make you feel more secure with me?', 'Relationship'),
  ('What''s something we disagree on that we''ve stopped discussing?', 'Relationship'),
  ('How do you want us to handle money as things get more serious?', 'Relationship'),
  ('What''s the nicest thing anyone has said about us?', 'Relationship'),
  ('What''s a fear you have about us that you know is irrational?', 'Relationship'),
  ('How do you want to be told bad news?', 'Relationship'),
  ('What''s something I''ve changed my mind about that you noticed?', 'Relationship'),
  ('What do you think our biggest strength is?', 'Relationship'),
  ('What''s our biggest blind spot?', 'Relationship'),
  ('What would you like our arguments to look like?', 'Relationship'),
  ('What''s something you want us to do less of?', 'Relationship'),
  ('What do you want me to ask you more often?', 'Relationship'),
  ('How much of your day would you like me to know about?', 'Relationship'),
  ('What''s a moment where I got it right without realising?', 'Relationship'),
  ('What''s a small thing you''d like to be able to rely on from me?', 'Relationship'),
  ('What do you hope we''re still doing when we''re old?', 'Relationship'),
  ('What part of your work would you keep if you could drop the rest?', 'Work & Purpose'),
  ('What do you want from work that you''re not getting?', 'Work & Purpose'),
  ('What''s something you''re good at that your job doesn''t use?', 'Work & Purpose'),
  ('How do you know when you''ve done a good day''s work?', 'Work & Purpose'),
  ('What would you do differently if money weren''t the point?', 'Work & Purpose'),
  ('What''s a career decision you''d revisit?', 'Work & Purpose'),
  ('What''s the most you''ve learned from a difficult colleague?', 'Work & Purpose'),
  ('How much should work matter, in a good life?', 'Work & Purpose'),
  ('What''s a compliment about your work that stuck?', 'Work & Purpose'),
  ('What''s a criticism that changed how you work?', 'Work & Purpose'),
  ('What does ambition mean to you now versus at twenty-five?', 'Work & Purpose'),
  ('What kind of manager do you want to be, or have?', 'Work & Purpose'),
  ('What''s something you''d like to be known for professionally?', 'Work & Purpose'),
  ('How do you feel on a Sunday evening?', 'Work & Purpose'),
  ('What''s the best thing about what you do?', 'Work & Purpose'),
  ('What would make you leave a job you liked?', 'Work & Purpose'),
  ('What''s a skill you''ve built that surprised you?', 'Work & Purpose'),
  ('How do you want work to fit around us?', 'Work & Purpose'),
  ('What''s something you''d be willing to earn less to do?', 'Work & Purpose'),
  ('What does retirement mean to you, if anything?', 'Work & Purpose'),
  ('What''s a working habit you''d like to break?', 'Work & Purpose'),
  ('What''s a project you''re proud of that nobody saw?', 'Work & Purpose'),
  ('How do you handle a mistake at work?', 'Work & Purpose'),
  ('What do you want to be doing professionally in five years?', 'Work & Purpose'),
  ('What''s the hardest thing about your work that you rarely explain?', 'Work & Purpose'),
  ('Would you work with me, honestly?', 'Work & Purpose'),
  ('What''s something you want to learn for its own sake, not for work?', 'Work & Purpose'),
  ('What does a meaningful contribution look like to you?', 'Work & Purpose'),
  ('What would you want a younger version of you to know about work?', 'Work & Purpose'),
  ('What''s the boundary between your work and your life, and does it hold?', 'Work & Purpose'),
  ('What''s the first thing you remember thinking about me?', 'History'),
  ('What''s a time I surprised you early on?', 'History'),
  ('What did you get wrong about what you wanted, before us?', 'History'),
  ('What''s a moment you knew you''d tell people about?', 'History'),
  ('What was the first difficult thing we navigated?', 'History'),
  ('What''s the best advice anyone gave us?', 'History'),
  ('What''s something from our first year that would confuse us now?', 'History'),
  ('What''s a place we went that you''d like to go back to?', 'History'),
  ('What''s the most ordinary day of ours you remember clearly?', 'History'),
  ('What''s something you were embarrassed about early on?', 'History'),
  ('What''s the funniest thing that''s happened to us?', 'History'),
  ('What''s a photo of us that doesn''t capture it at all?', 'History'),
  ('What''s a conversation that changed the direction of things?', 'History'),
  ('What did you learn about me that took a long time?', 'History'),
  ('What''s a thing we used to do that we should start again?', 'History'),
  ('What''s the kindest thing I did before you were sure about me?', 'History'),
  ('What''s an argument we had that you''re glad about?', 'History'),
  ('What''s a detail about how we met that people always get wrong?', 'History'),
  ('What''s the first proper gift we exchanged?', 'History'),
  ('What''s the longest we''ve talked in one sitting?', 'History'),
  ('What''s a habit we developed without deciding to?', 'History'),
  ('When did you first feel at home with me?', 'History'),
  ('What''s something you noticed about my family or friends early?', 'History'),
  ('What''s a small promise we kept?', 'History'),
  ('What''s a moment of ours you''d want painted?', 'History'),
  ('What''s the hardest goodbye we''ve had?', 'History'),
  ('What did you think our chances were at the start?', 'History'),
  ('What''s something about our early messages that makes you laugh?', 'History'),
  ('What''s the first thing we disagreed about?', 'History'),
  ('What would surprise our past selves most about now?', 'History'),
  ('What''s a way your family shows love without saying it?', 'Family'),
  ('What did you learn about relationships from watching your parents?', 'Family'),
  ('What''s a family rule you thought was normal until you left?', 'Family'),
  ('How do you want to handle holidays when they clash?', 'Family'),
  ('What''s something your family does that you''d like us to do?', 'Family'),
  ('Who raised you, beyond your parents?', 'Family'),
  ('What''s a conversation with a family member you''ve been avoiding?', 'Family'),
  ('What would you want to say to a grandparent now?', 'Family'),
  ('How do you feel about being the one who organises everything?', 'Family'),
  ('What''s a family pattern you''re determined not to repeat?', 'Family'),
  ('What do you want your siblings, if any, to know?', 'Family'),
  ('How much do you tell your family about us?', 'Family'),
  ('What''s a family member you''d like to be closer to?', 'Family'),
  ('What''s a story about your childhood you love?', 'Family'),
  ('What do you want a child to call you, if we have one?', 'Family'),
  ('How would we divide the unglamorous parts of family life?', 'Family'),
  ('What''s your view on discipline?', 'Family'),
  ('What would you want a child to inherit from me?', 'Family'),
  ('What''s the hardest thing about your family right now?', 'Family'),
  ('How do you want us to handle a family member who disapproves?', 'Family'),
  ('What did home smell like growing up?', 'Family'),
  ('What''s a meal your family always made?', 'Family'),
  ('What''s something your parents did that you only appreciated later?', 'Family'),
  ('What would a good relationship with in-laws look like?', 'Family'),
  ('How involved do you want grandparents to be?', 'Family'),
  ('What''s a family expectation you feel the weight of?', 'Family'),
  ('What''s something about your family you''d want me to be gentle about?', 'Family'),
  ('What does a family Christmas or equivalent look like to you?', 'Family'),
  ('Who in your family are you most like?', 'Family'),
  ('What would you want our family to be known for?', 'Family'),
  ('What''s the first thing you''d buy if a big bill disappeared?', 'Money & Finances'),
  ('How do you decide something is worth the money?', 'Money & Finances'),
  ('What''s a price you''d never pay, on principle?', 'Money & Finances'),
  ('How do you feel when someone else pays?', 'Money & Finances'),
  ('What''s your instinct about splitting a bill with friends?', 'Money & Finances'),
  ('What would financial independence mean for you?', 'Money & Finances'),
  ('What''s a subscription you should cancel?', 'Money & Finances'),
  ('How much do you want to know about my finances?', 'Money & Finances'),
  ('What''s a money mistake you''d warn someone about?', 'Money & Finances'),
  ('What does generosity look like when money is tight?', 'Money & Finances'),
  ('Would you rather own or rent, and why?', 'Money & Finances'),
  ('What''s your view on inheritance?', 'Money & Finances'),
  ('What''s a thing you spend on that others would call a waste?', 'Money & Finances'),
  ('How would we decide whose career takes priority?', 'Money & Finances'),
  ('What would you want us to do with a joint account, if anything?', 'Money & Finances'),
  ('What''s the smallest amount of money that would change your week?', 'Money & Finances'),
  ('How do you feel about talking money with friends?', 'Money & Finances'),
  ('What would you save for if the future felt certain?', 'Money & Finances'),
  ('What''s a financial goal you''ve hit that felt good?', 'Money & Finances'),
  ('What''s your relationship with budgeting?', 'Money & Finances'),
  ('What would you spend on if you stopped feeling guilty?', 'Money & Finances'),
  ('What''s something you''d never buy second-hand?', 'Money & Finances'),
  ('What''s something you''d always buy second-hand?', 'Money & Finances'),
  ('How would we handle one of us supporting the other for a while?', 'Money & Finances'),
  ('What does being well off actually look like to you?', 'Money & Finances'),
  ('What''s a purchase that made a relationship better?', 'Money & Finances'),
  ('What do you want to be able to afford in ten years?', 'Money & Finances'),
  ('What''s the most useful thing you''ve spent money on this year?', 'Money & Finances'),
  ('How do you feel about giving to charity?', 'Money & Finances'),
  ('What''s a money value you want us to share?', 'Money & Finances'),
  ('What''s a place you''ve been that you''d never recommend?', 'Travel'),
  ('What do you want from a holiday that you rarely get?', 'Travel'),
  ('What''s the best thing you''ve done alone abroad?', 'Travel'),
  ('How do you feel about travelling with other people?', 'Travel'),
  ('What''s a journey worth taking for its own sake?', 'Travel'),
  ('What''s your view on going back to the same place every year?', 'Travel'),
  ('What''s the most uncomfortable thing you''d put up with for a good trip?', 'Travel'),
  ('What''s something you always do on the first day somewhere new?', 'Travel'),
  ('What''s a country whose food alone would justify the trip?', 'Travel'),
  ('What''s the best view you''ve woken up to?', 'Travel'),
  ('What do you miss when you''re away?', 'Travel'),
  ('What''s a trip you''d take if you had six months?', 'Travel'),
  ('What''s a place you''ve read about and never been?', 'Travel'),
  ('What''s your approach to museums and galleries, honestly?', 'Travel'),
  ('What''s the most overrated city you''ve visited?', 'Travel'),
  ('What''s a small town you loved?', 'Travel'),
  ('What would you want from a road trip together?', 'Travel'),
  ('What''s the best transport you''ve ever taken?', 'Travel'),
  ('What''s something that ruins a trip for you?', 'Travel'),
  ('What''s a place you''d want to see before it changes?', 'Travel'),
  ('How do you feel about tourist attractions?', 'Travel'),
  ('What''s your ideal length for a holiday?', 'Travel'),
  ('What''s a place that felt like somewhere you could belong?', 'Travel'),
  ('What''s the best conversation you''ve had with a stranger travelling?', 'Travel'),
  ('What would make a trip feel like a proper break?', 'Travel'),
  ('What''s a destination you''d save for a big occasion?', 'Travel'),
  ('What''s the worst accommodation you''ve stayed in?', 'Travel'),
  ('What would you pack for a year away?', 'Travel'),
  ('What''s a place you associate with a particular person?', 'Travel'),
  ('Where do you want to go next, realistically?', 'Travel'),
  ('What''s a meal you''d want on your last day?', 'Food & Culture'),
  ('What''s something you cook when nobody''s watching?', 'Food & Culture'),
  ('What''s a restaurant you''d fly for?', 'Food & Culture'),
  ('What''s your position on breakfast?', 'Food & Culture'),
  ('What''s a food you''ve pretended to like?', 'Food & Culture'),
  ('What would you cook to impress someone?', 'Food & Culture'),
  ('What''s the best market you''ve been to?', 'Food & Culture'),
  ('What''s a drink that means something to you?', 'Food & Culture'),
  ('What''s a dish from my culture you''d like to learn?', 'Food & Culture'),
  ('What''s the worst meal you''ve had to be polite about?', 'Food & Culture'),
  ('How do you feel about eating alone in a restaurant?', 'Food & Culture'),
  ('What''s a food memory tied to a specific person?', 'Food & Culture'),
  ('What''s your view on leftovers?', 'Food & Culture'),
  ('What''s a book that made you see something differently?', 'Food & Culture'),
  ('What''s a film you''d want us to watch together?', 'Food & Culture'),
  ('What''s a song you''d put on at the end of a good night?', 'Food & Culture'),
  ('What''s an artist or writer you''d defend?', 'Food & Culture'),
  ('What''s something you find beautiful that others find strange?', 'Food & Culture'),
  ('What''s a tradition you''d like to invent for us?', 'Food & Culture'),
  ('What''s the best live performance you''ve seen?', 'Food & Culture'),
  ('What''s a museum or place you''d go back to alone?', 'Food & Culture'),
  ('What language would you most like to speak fluently?', 'Food & Culture'),
  ('What''s a cultural habit from somewhere else you admire?', 'Food & Culture'),
  ('What did you grow up celebrating, and does it still matter?', 'Food & Culture'),
  ('What''s a food you''d travel a long way for?', 'Food & Culture'),
  ('What''s your comfort meal on a bad day?', 'Food & Culture'),
  ('What''s something you refuse to eat?', 'Food & Culture'),
  ('What''s a story your family tells at the table?', 'Food & Culture'),
  ('What''s the nicest thing anyone has cooked for you?', 'Food & Culture'),
  ('What would our signature dish be?', 'Food & Culture'),
  ('What did you do for fun at fifteen that you''d still enjoy?', 'Hobbies & Lifestyle'),
  ('What''s a hobby you''d like me to try with you?', 'Hobbies & Lifestyle'),
  ('How much of your week is yours, really?', 'Hobbies & Lifestyle'),
  ('What''s something you do badly and enjoy anyway?', 'Hobbies & Lifestyle'),
  ('What''s the last thing you got properly absorbed in?', 'Hobbies & Lifestyle'),
  ('What would you like your evenings to look like?', 'Hobbies & Lifestyle'),
  ('What''s your relationship with your phone in the morning?', 'Hobbies & Lifestyle'),
  ('What''s something you own that you use every single day?', 'Hobbies & Lifestyle'),
  ('What''s a way you look after yourself that isn''t obvious?', 'Hobbies & Lifestyle'),
  ('How do you feel about being outdoors?', 'Hobbies & Lifestyle'),
  ('What''s a sport or activity you''d like to be good at?', 'Hobbies & Lifestyle'),
  ('What''s the most peaceful hour of your week?', 'Hobbies & Lifestyle'),
  ('What''s a thing you collect, even accidentally?', 'Hobbies & Lifestyle'),
  ('What does a good night out look like to you now?', 'Hobbies & Lifestyle'),
  ('What does a good night in look like to you?', 'Hobbies & Lifestyle'),
  ('What''s a skill you''d teach someone?', 'Hobbies & Lifestyle'),
  ('What''s your relationship with music while working?', 'Hobbies & Lifestyle'),
  ('What''s a piece of clothing you feel most yourself in?', 'Hobbies & Lifestyle'),
  ('How do you feel about mess?', 'Hobbies & Lifestyle'),
  ('What''s a small ritual that starts your day properly?', 'Hobbies & Lifestyle'),
  ('What would you do with an extra hour every day?', 'Hobbies & Lifestyle'),
  ('What''s something you''ve done once and want to do again?', 'Hobbies & Lifestyle'),
  ('What''s a group or community you''d like to be part of?', 'Hobbies & Lifestyle'),
  ('How do you feel about competition?', 'Hobbies & Lifestyle'),
  ('What''s a habit you''ve kept for years?', 'Hobbies & Lifestyle'),
  ('What''s the last new thing you tried?', 'Hobbies & Lifestyle'),
  ('What''s a way you''d like to spend a birthday?', 'Hobbies & Lifestyle'),
  ('What''s something you do that nobody else you know does?', 'Hobbies & Lifestyle'),
  ('What would make your home feel more like yours?', 'Hobbies & Lifestyle'),
  ('What do you want more time for?', 'Hobbies & Lifestyle'),
  ('What''s a rule you''d break to help someone you love?', 'Moral Values'),
  ('How much do intentions matter compared to outcomes?', 'Moral Values'),
  ('What''s something you think is a private matter that others treat as public?', 'Moral Values'),
  ('When is it right to keep a secret for someone?', 'Moral Values'),
  ('What do you think you''d be willing to lose a friendship over?', 'Moral Values'),
  ('How do you feel about people who change their views for convenience?', 'Moral Values'),
  ('What''s a compromise you''d never make?', 'Moral Values'),
  ('How should someone make up for something they got badly wrong?', 'Moral Values'),
  ('What''s the most generous thing someone has done for you?', 'Moral Values'),
  ('Do you think people are mostly doing their best?', 'Moral Values'),
  ('What''s something you judge people for that you probably shouldn''t?', 'Moral Values'),
  ('When does confidence become arrogance?', 'Moral Values'),
  ('What''s a duty you feel that nobody imposed on you?', 'Moral Values'),
  ('How do you decide who deserves your time?', 'Moral Values'),
  ('What''s a cause you''d give money to without thinking?', 'Moral Values'),
  ('What''s the right response to someone being unfair to you?', 'Moral Values'),
  ('How much should the past count against someone?', 'Moral Values'),
  ('What''s something you believe that would be unpopular at a dinner party?', 'Moral Values'),
  ('What does fairness look like when resources are limited?', 'Moral Values'),
  ('When is walking away the right thing to do?', 'Moral Values'),
  ('What''s the difference between a boundary and a grudge?', 'Moral Values'),
  ('How do you think about power in relationships generally?', 'Moral Values'),
  ('What''s something you think everyone should have to learn?', 'Moral Values'),
  ('What responsibility do we have to future generations?', 'Moral Values'),
  ('What would you do if honesty cost you something real?', 'Moral Values'),
  ('How do you feel about rules you disagree with?', 'Moral Values'),
  ('What''s a lie told to spare feelings that you''d still call wrong?', 'Moral Values'),
  ('What makes someone trustworthy to you?', 'Moral Values'),
  ('What''s a value you''ve had to defend recently?', 'Moral Values'),
  ('What do you want to be less judgemental about?', 'Moral Values'),
  ('What''s something you''ve wanted to ask me and haven''t?', 'Edgy Questions'),
  ('What''s the most jealous you''ve ever been?', 'Edgy Questions'),
  ('What''s a thought about me you''d never say?', 'Edgy Questions'),
  ('What''s something you find attractive that has nothing to do with looks?', 'Edgy Questions'),
  ('When did you last feel genuinely desired?', 'Edgy Questions'),
  ('What''s a fantasy that''s more about closeness than anything else?', 'Edgy Questions'),
  ('What''s the most vulnerable you''ve let yourself be with me?', 'Edgy Questions'),
  ('What''s something you''d change about our physical relationship?', 'Edgy Questions'),
  ('What''s a compliment that would embarrass you to receive?', 'Edgy Questions'),
  ('What''s the worst thing you''ve done in a relationship?', 'Edgy Questions'),
  ('What''s something you''ve forgiven me for that I don''t know about?', 'Edgy Questions'),
  ('What would make you end this?', 'Edgy Questions'),
  ('What''s a conversation about the future that frightens you?', 'Edgy Questions'),
  ('What do you think I''d struggle to forgive?', 'Edgy Questions'),
  ('What''s the most honest answer you''ve given on this app?', 'Edgy Questions'),
  ('What''s something you''ve exaggerated about yourself?', 'Edgy Questions'),
  ('What would you want to know about my past, if I promised to answer?', 'Edgy Questions'),
  ('What''s a habit of mine that quietly irritates you?', 'Edgy Questions'),
  ('What''s something you want that you feel guilty for wanting?', 'Edgy Questions'),
  ('What''s the closest you''ve come to lying to me?', 'Edgy Questions'),
  ('What''s a part of yourself you keep from almost everyone?', 'Edgy Questions'),
  ('What do you think about when you can''t sleep and I''m not there?', 'Edgy Questions'),
  ('What''s a memory of us you''d never share with anyone?', 'Edgy Questions'),
  ('What''s something you''d like to be braver about with me?', 'Edgy Questions'),
  ('What''s a compliment you''ve wanted to give and felt too shy to?', 'Edgy Questions'),
  ('What''s the most reckless thing you''ve done for love?', 'Edgy Questions'),
  ('What''s a rule in your head about relationships that you''d like to break?', 'Edgy Questions'),
  ('What''s something you need that''s hard to admit needing?', 'Edgy Questions'),
  ('What would you do with a day where nothing counted?', 'Edgy Questions'),
  ('What''s the truest thing you could tell me right now?', 'Edgy Questions'),
  ('What''s the hardest feedback you''ve acted on?', 'Growth & Change'),
  ('What are you better at saying no to than you used to be?', 'Growth & Change'),
  ('What''s a fear that used to run your decisions?', 'Growth & Change'),
  ('What''s a relationship that changed how you see yourself?', 'Growth & Change'),
  ('What would you like to be less reactive about?', 'Growth & Change'),
  ('What''s a habit you keep restarting?', 'Growth & Change'),
  ('What does self-discipline look like for you when it''s working?', 'Growth & Change'),
  ('What''s a thing you''ve accepted about yourself rather than fixed?', 'Growth & Change'),
  ('What''s something you used to need that you don''t now?', 'Growth & Change'),
  ('What''s a compliment you''d have dismissed five years ago?', 'Growth & Change'),
  ('How do you handle envy?', 'Growth & Change'),
  ('What''s something you''re deliberately practising?', 'Growth & Change'),
  ('What''s a belief you''re testing at the moment?', 'Growth & Change'),
  ('What would you like to be better at listening to?', 'Growth & Change'),
  ('What''s the last time you changed a long-held opinion?', 'Growth & Change'),
  ('What''s a fear you''d like to face this year?', 'Growth & Change'),
  ('What have you got braver about?', 'Growth & Change'),
  ('What''s a lesson you keep having to relearn?', 'Growth & Change'),
  ('What''s a story you tell about yourself that might not be true any more?', 'Growth & Change'),
  ('What''s a way you''ve disappointed yourself that you''ve moved past?', 'Growth & Change'),
  ('What''s a small discipline that''s changed something big?', 'Growth & Change'),
  ('What would growth look like for us, not just for you?', 'Growth & Change'),
  ('What''s something you want to stop caring about?', 'Growth & Change'),
  ('What''s a strength you''ve had to learn to use carefully?', 'Growth & Change'),
  ('What do you want to have let go of in a year?', 'Growth & Change'),
  ('What''s a change in you that others noticed first?', 'Growth & Change'),
  ('What''s a question you''re currently sitting with?', 'Growth & Change'),
  ('What would the most honest version of you do differently?', 'Growth & Change'),
  ('What are you learning right now, even if slowly?', 'Growth & Change'),
  ('What do you want to be able to say about this year?', 'Growth & Change'),
  ('What''s a life you sometimes imagine that isn''t this one?', 'Dreams & Future'),
  ('What would you want a normal week to contain, in ten years?', 'Dreams & Future'),
  ('What''s a thing you want to be old enough to have done?', 'Dreams & Future'),
  ('What would you want to be doing the year you turn fifty?', 'Dreams & Future'),
  ('What''s a place you''d want to grow old in?', 'Dreams & Future'),
  ('What would enough look like, so you could stop chasing?', 'Dreams & Future'),
  ('What''s something you want to make or write or build?', 'Dreams & Future'),
  ('What do you want us to be like when things are hard?', 'Dreams & Future'),
  ('What''s a tradition you want us to have in twenty years?', 'Dreams & Future'),
  ('What would you like to have learned by then?', 'Dreams & Future'),
  ('What''s a risk you want to take while you still can?', 'Dreams & Future'),
  ('What would you want said at a party for you?', 'Dreams & Future'),
  ('What''s a dream that''s shifted rather than disappeared?', 'Dreams & Future'),
  ('What would a brave next five years look like?', 'Dreams & Future'),
  ('What do you want our weekends to be like eventually?', 'Dreams & Future'),
  ('What''s something you want to be able to give someone?', 'Dreams & Future'),
  ('What would you want to stop worrying about by forty?', 'Dreams & Future'),
  ('What''s an experience you want us to have once?', 'Dreams & Future'),
  ('What do you want to be curious about for the rest of your life?', 'Dreams & Future'),
  ('What would make you proud of the life you built?', 'Dreams & Future'),
  ('What''s a small future pleasure you think about?', 'Dreams & Future'),
  ('What would you want us to do the year everything goes right?', 'Dreams & Future'),
  ('What''s a version of home you''re aiming at?', 'Dreams & Future'),
  ('What do you want to have stopped doing?', 'Dreams & Future'),
  ('What''s something you''d like to be famous for among ten people?', 'Dreams & Future'),
  ('What''s a plan you''re superstitious about discussing?', 'Dreams & Future'),
  ('What do you hope we''re brave enough to do?', 'Dreams & Future'),
  ('What''s the future you''d choose if both of us could choose freely?', 'Dreams & Future'),
  ('What would you want to be true on our tenth anniversary?', 'Dreams & Future'),
  ('What''s the next thing worth working towards?', 'Dreams & Future')) as v(question, category)
where not exists (
  select 1 from public.daily_questions d where lower(trim(d.question)) = lower(trim(v.question))
);
