-- Seed content: premium-tier prompts for the "Who's More Likely To" couples game (More Likely game), covering all 10 categories.
insert into public.more_likely_prompts (prompt, category, tier) values
  ('Who is more likely to sing in the shower?', 'Starters', 'premium'),
  ('Who is more likely to talk to strangers while waiting in line?', 'Starters', 'premium'),
  ('Who is more likely to forget where they parked the car?', 'Starters', 'premium'),
  ('Who is more likely to laugh at their own jokes?', 'Starters', 'premium'),
  ('Who is more likely to take the last slice of pizza?', 'Starters', 'premium'),
  ('Who is more likely to fall asleep during a movie?', 'Starters', 'premium'),
  ('Who is more likely to lose their phone somewhere in the house?', 'Starters', 'premium'),
  ('Who is more likely to hit snooze more than three times?', 'Starters', 'premium'),
  ('Who is more likely to dance when no one is watching?', 'Starters', 'premium'),
  ('Who is more likely to talk to a pet like it''s a tiny person?', 'Starters', 'premium'),
  ('Who is more likely to take forever to pick a restaurant?', 'Starters', 'premium'),
  ('Who is more likely to wear socks that don''t match?', 'Starters', 'premium'),
  ('Who is more likely to cry during a commercial?', 'Starters', 'premium'),
  ('Who is more likely to get lost even with GPS on?', 'Starters', 'premium'),
  ('Who is more likely to leave the fridge door open?', 'Starters', 'premium'),
  ('Who is more likely to sing the wrong lyrics with total confidence?', 'Starters', 'premium'),
  ('Who is more likely to forget what they were saying mid-sentence?', 'Starters', 'premium'),
  ('Who is more likely to jaywalk when no cars are around?', 'Starters', 'premium'),
  ('Who is more likely to hum a tune all day without noticing?', 'Starters', 'premium'),
  ('Who is more likely to trip over absolutely nothing?', 'Starters', 'premium'),
  ('Who is more likely to take a selfie in an awkward spot?', 'Starters', 'premium'),
  ('Who is more likely to forget an umbrella on a cloudy day?', 'Starters', 'premium'),
  ('Who is more likely to talk during a movie at the theater?', 'Starters', 'premium'),
  ('Who is more likely to leave a text on read for days?', 'Starters', 'premium'),
  ('Who is more likely to eat cereal for dinner?', 'Starters', 'premium'),
  ('Who is more likely to wear pajamas out to the mailbox?', 'Starters', 'premium'),
  ('Who is more likely to lose an argument with a vending machine?', 'Starters', 'premium'),
  ('Who is more likely to clap at the wrong moment in public?', 'Starters', 'premium'),
  ('Who is more likely to take a nap in the middle of the day?', 'Starters', 'premium'),
  ('Who is more likely to get the giggles at the worst possible time?', 'Starters', 'premium'),
  ('Who is more likely to accidentally like an old photo while scrolling?', 'Starters', 'premium'),
  ('Who is more likely to forget someone''s name right after meeting them?', 'Starters', 'premium'),
  ('Who is more likely to sneeze loud enough to startle someone?', 'Starters', 'premium'),
  ('Who is more likely to leave the TV on and fall asleep?', 'Starters', 'premium'),
  ('Who is more likely to talk with their hands?', 'Starters', 'premium'),
  ('Who is more likely to get excited about free samples?', 'Starters', 'premium'),
  ('Who is more likely to lose track of time scrolling their phone?', 'Starters', 'premium'),
  ('Who is more likely to answer a rhetorical question out loud?', 'Starters', 'premium'),
  ('Who is more likely to mispronounce a common word confidently?', 'Starters', 'premium'),
  ('Who is more likely to drop their phone on their face in bed?', 'Starters', 'premium'),
  ('Who is more likely to start humming the elevator music?', 'Starters', 'premium'),
  ('Who is more likely to wave back at someone who wasn''t waving at them?', 'Starters', 'premium'),
  ('Who is more likely to burn popcorn in the microwave?', 'Starters', 'premium'),
  ('Who is more likely to forget why they walked into a room?', 'Starters', 'premium'),
  ('Who is more likely to take the wrong exit on a familiar road?', 'Starters', 'premium'),
  ('Who is more likely to break into a random dance move in the kitchen?', 'Starters', 'premium'),
  ('Who is more likely to be a morning person?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to check their phone first thing after waking up?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to make the bed every single day?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a strict skincare routine?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep a running to-do list?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to show up early to appointments?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to remember people''s birthdays without a reminder?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know their own blood type off the top of their head?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a favorite pen they always hunt for?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to organize their closet by color?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep receipts for absolutely everything?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know their neighbors'' names?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a reliable go-to karaoke song?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to plan a whole weekend on a whim?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep a journal?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know their own coffee order by heart?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to be superstitious about small things?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to remember song lyrics from decades ago?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to still have a favorite childhood toy around?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to hang on to old t-shirts for sentimental reasons?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to always know the weather forecast before checking?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have strong opinions about which way toilet paper should hang?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep old birthday cards?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know their own personality type off by heart?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to be the friend everyone calls for advice?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to always remember exactly where they left their keys?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a favorite word they overuse?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to recite an entire movie word for word?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to carry a lucky item around with them?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep a running list of books to read?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know how to change a tire?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have the messiest handwriting?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to remember their dreams in vivid detail?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a strong opinion on pineapple on pizza?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep old concert tickets as souvenirs?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to have a weird party trick?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know all the words to the national anthem?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to always have gum or mints on hand?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to read the instructions before using something new?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to still go by a childhood nickname that stuck?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to keep their phone on silent all the time?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to make new friends easily?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to remember exactly what they wore on the first day of school?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to always carry a backup phone charger?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to know their own love language?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to talk in their sleep?', 'Get to Know Each Other', 'premium'),
  ('Who is more likely to say "I love you" first each day?', 'Relationship', 'premium'),
  ('Who is more likely to plan a surprise date out of nowhere?', 'Relationship', 'premium'),
  ('Who is more likely to initiate a hug after a long day?', 'Relationship', 'premium'),
  ('Who is more likely to remember the exact date they first met?', 'Relationship', 'premium'),
  ('Who is more likely to save a funny voicemail from their partner?', 'Relationship', 'premium'),
  ('Who is more likely to text "good morning" without fail?', 'Relationship', 'premium'),
  ('Who is more likely to suggest trying a new hobby together?', 'Relationship', 'premium'),
  ('Who is more likely to take the blame first after a small disagreement?', 'Relationship', 'premium'),
  ('Who is more likely to plan the next date night?', 'Relationship', 'premium'),
  ('Who is more likely to keep a photo of their partner as their phone background?', 'Relationship', 'premium'),
  ('Who is more likely to leave a sweet note somewhere unexpected?', 'Relationship', 'premium'),
  ('Who is more likely to still bring up an inside joke from years ago?', 'Relationship', 'premium'),
  ('Who is more likely to suggest a couples photo shoot?', 'Relationship', 'premium'),
  ('Who is more likely to say sorry first, even for small things?', 'Relationship', 'premium'),
  ('Who is more likely to plan a cozy night in?', 'Relationship', 'premium'),
  ('Who is more likely to bring home a small treat for no reason?', 'Relationship', 'premium'),
  ('Who is more likely to want to slow dance in the kitchen?', 'Relationship', 'premium'),
  ('Who is more likely to keep ticket stubs from a date?', 'Relationship', 'premium'),
  ('Who is more likely to suggest a regular relationship check-in chat?', 'Relationship', 'premium'),
  ('Who is more likely to compliment their partner in front of others?', 'Relationship', 'premium'),
  ('Who is more likely to remember exactly how their partner takes their coffee?', 'Relationship', 'premium'),
  ('Who is more likely to plan a themed date night?', 'Relationship', 'premium'),
  ('Who is more likely to want to redo their first date years later?', 'Relationship', 'premium'),
  ('Who is more likely to keep an old greeting card from their partner?', 'Relationship', 'premium'),
  ('Who is more likely to suggest making a couples'' bucket list?', 'Relationship', 'premium'),
  ('Who is more likely to handle the anniversary dinner reservations?', 'Relationship', 'premium'),
  ('Who is more likely to text "thinking of you" out of the blue?', 'Relationship', 'premium'),
  ('Who is more likely to want to hold hands in public?', 'Relationship', 'premium'),
  ('Who is more likely to remember their partner''s favorite flower?', 'Relationship', 'premium'),
  ('Who is more likely to suggest matching outfits for an event?', 'Relationship', 'premium'),
  ('Who is more likely to plan a scavenger hunt for a special occasion?', 'Relationship', 'premium'),
  ('Who is more likely to keep a shared playlist updated?', 'Relationship', 'premium'),
  ('Who is more likely to want to try a couples cooking class?', 'Relationship', 'premium'),
  ('Who is more likely to compliment their partner''s outfit unprompted?', 'Relationship', 'premium'),
  ('Who is more likely to take candid photos of their partner?', 'Relationship', 'premium'),
  ('Who is more likely to suggest a phone-free date night?', 'Relationship', 'premium'),
  ('Who is more likely to remember to ask how a big meeting went?', 'Relationship', 'premium'),
  ('Who is more likely to plan a spontaneous road trip together?', 'Relationship', 'premium'),
  ('Who is more likely to keep a scrapbook of the relationship?', 'Relationship', 'premium'),
  ('Who is more likely to want to write a letter to open on a future anniversary?', 'Relationship', 'premium'),
  ('Who is more likely to suggest reenacting their very first date?', 'Relationship', 'premium'),
  ('Who is more likely to learn their partner''s favorite song on an instrument?', 'Relationship', 'premium'),
  ('Who is more likely to plan a picnic out of nowhere?', 'Relationship', 'premium'),
  ('Who is more likely to build a road-trip playlist for the two of them?', 'Relationship', 'premium'),
  ('Who is more likely to suggest a weekly date-night ritual?', 'Relationship', 'premium'),
  ('Who is more likely to remember small details from a chat weeks later?', 'Relationship', 'premium'),
  ('Who is more likely to pack far too many shoes?', 'Travel', 'premium'),
  ('Who is more likely to forget their passport at home?', 'Travel', 'premium'),
  ('Who is more likely to arrive at the airport absurdly early?', 'Travel', 'premium'),
  ('Who is more likely to fall asleep before the plane even takes off?', 'Travel', 'premium'),
  ('Who is more likely to plan out the entire itinerary?', 'Travel', 'premium'),
  ('Who is more likely to buy an unmistakably touristy souvenir?', 'Travel', 'premium'),
  ('Who is more likely to get turned around in a new city?', 'Travel', 'premium'),
  ('Who is more likely to order the strangest item on a foreign menu?', 'Travel', 'premium'),
  ('Who is more likely to take a dozen photos of the exact same view?', 'Travel', 'premium'),
  ('Who is more likely to forget to charge their phone before a flight?', 'Travel', 'premium'),
  ('Who is more likely to haggle at a local market?', 'Travel', 'premium'),
  ('Who is more likely to sleep straight through a hotel wake-up call?', 'Travel', 'premium'),
  ('Who is more likely to ask locals for restaurant recommendations?', 'Travel', 'premium'),
  ('Who is more likely to overpack the carry-on?', 'Travel', 'premium'),
  ('Who is more likely to get carsick or seasick on a trip?', 'Travel', 'premium'),
  ('Who is more likely to want to visit every museum in a city?', 'Travel', 'premium'),
  ('Who is more likely to bring home way too many snacks from abroad?', 'Travel', 'premium'),
  ('Who is more likely to misplace the hotel key card?', 'Travel', 'premium'),
  ('Who is more likely to always claim the window seat?', 'Travel', 'premium'),
  ('Who is more likely to attempt the local language, however badly?', 'Travel', 'premium'),
  ('Who is more likely to forget sunscreen and get sunburned?', 'Travel', 'premium'),
  ('Who is more likely to want to try street food first thing?', 'Travel', 'premium'),
  ('Who is more likely to suggest a spontaneous detour off the itinerary?', 'Travel', 'premium'),
  ('Who is more likely to tear up watching a sunset on vacation?', 'Travel', 'premium'),
  ('Who is more likely to keep every boarding pass as a memento?', 'Travel', 'premium'),
  ('Who is more likely to insist on reading a paper map just for fun?', 'Travel', 'premium'),
  ('Who is more likely to want to rent a scooter in a new city?', 'Travel', 'premium'),
  ('Who is more likely to set an alarm in the wrong time zone?', 'Travel', 'premium'),
  ('Who is more likely to prefer a hostel over a hotel?', 'Travel', 'premium'),
  ('Who is more likely to get unreasonably excited about airport lounges?', 'Travel', 'premium'),
  ('Who is more likely to keep a travel journal?', 'Travel', 'premium'),
  ('Who is more likely to want to skip the tourist traps for hidden gems?', 'Travel', 'premium'),
  ('Who is more likely to pack snacks for the flight?', 'Travel', 'premium'),
  ('Who is more likely to want to go camping instead of booking a hotel?', 'Travel', 'premium'),
  ('Who is more likely to take the scenic route on a road trip?', 'Travel', 'premium'),
  ('Who is more likely to forget to exchange currency before landing?', 'Travel', 'premium'),
  ('Who is more likely to get overly excited about the hotel breakfast buffet?', 'Travel', 'premium'),
  ('Who is more likely to learn a few local phrases before a trip?', 'Travel', 'premium'),
  ('Who is more likely to end up as the trip''s unofficial photographer?', 'Travel', 'premium'),
  ('Who is more likely to want to extend a trip at the last minute?', 'Travel', 'premium'),
  ('Who is more likely to get nervous during turbulence?', 'Travel', 'premium'),
  ('Who is more likely to want to try every gelato flavor in a new city?', 'Travel', 'premium'),
  ('Who is more likely to bring back a fridge magnet from every trip?', 'Travel', 'premium'),
  ('Who is more likely to plan an entire vacation around food?', 'Travel', 'premium'),
  ('Who is more likely to want to revisit the same destination again and again?', 'Travel', 'premium'),
  ('Who is more likely to leave a charger behind in a hotel room?', 'Travel', 'premium'),
  ('Who is more likely to order dessert before the main course?', 'Food & Culture', 'premium'),
  ('Who is more likely to order the spiciest dish on the menu?', 'Food & Culture', 'premium'),
  ('Who is more likely to steal food off their partner''s plate?', 'Food & Culture', 'premium'),
  ('Who is more likely to care exactly where the napkins go on a table?', 'Food & Culture', 'premium'),
  ('Who is more likely to finish their plate even when they''re stuffed?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest trying a completely new cuisine?', 'Food & Culture', 'premium'),
  ('Who is more likely to follow a recipe to the letter versus improvising?', 'Food & Culture', 'premium'),
  ('Who is more likely to order the same dish every single time?', 'Food & Culture', 'premium'),
  ('Who is more likely to pick a food truck over a sit-down restaurant?', 'Food & Culture', 'premium'),
  ('Who is more likely to binge an entire season of a cooking show?', 'Food & Culture', 'premium'),
  ('Who is more likely to insist on cooking a big meal from scratch?', 'Food & Culture', 'premium'),
  ('Who is more likely to know the difference between obscure spices?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to learn to make pasta from scratch?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest brunch on a lazy weekend?', 'Food & Culture', 'premium'),
  ('Who is more likely to eat dessert before finishing dinner?', 'Food & Culture', 'premium'),
  ('Who is more likely to try an exotic fruit they''ve never seen before?', 'Food & Culture', 'premium'),
  ('Who is more likely to be picky about how their coffee is made?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to host a dinner party?', 'Food & Culture', 'premium'),
  ('Who is more likely to cook a recipe the same night they saw it online?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest a themed dinner, like taco night?', 'Food & Culture', 'premium'),
  ('Who is more likely to know the best hole-in-the-wall restaurant in town?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to grow their own herbs?', 'Food & Culture', 'premium'),
  ('Who is more likely to take charge of the grill at a barbecue?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to go to a wine or cheese tasting?', 'Food & Culture', 'premium'),
  ('Who is more likely to get weirdly competitive during a cooking challenge?', 'Food & Culture', 'premium'),
  ('Who is more likely to read restaurant reviews obsessively before choosing one?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to check out a food festival?', 'Food & Culture', 'premium'),
  ('Who is more likely to insist on trying the local delicacy while traveling?', 'Food & Culture', 'premium'),
  ('Who is more likely to bake something from scratch on a rainy day?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest ordering takeout on a lazy night?', 'Food & Culture', 'premium'),
  ('Who is more likely to know how to pair food and drinks well?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to browse a farmers market on the weekend?', 'Food & Culture', 'premium'),
  ('Who is more likely to try a recipe from another culture just for fun?', 'Food & Culture', 'premium'),
  ('Who is more likely to over-season pretty much everything they cook?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to recreate a grandparent''s recipe?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest a potluck with friends?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to try pickling or fermenting something at home?', 'Food & Culture', 'premium'),
  ('Who is more likely to bring the one dish to a party nobody else thought of?', 'Food & Culture', 'premium'),
  ('Who is more likely to pick a new coffee shop over their usual spot?', 'Food & Culture', 'premium'),
  ('Who is more likely to know the full story behind a family recipe?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest celebrating a holiday with traditional food?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to try making cocktails or mocktails at home?', 'Food & Culture', 'premium'),
  ('Who is more likely to always ask for extra sauce on the side?', 'Food & Culture', 'premium'),
  ('Who is more likely to want to explore a cultural food market in a new city?', 'Food & Culture', 'premium'),
  ('Who is more likely to suggest trying a fusion restaurant?', 'Food & Culture', 'premium'),
  ('Who is more likely to can''t resist the smell of a bakery?', 'Food & Culture', 'premium'),
  ('Who is more likely to call their parents just to check in?', 'Family', 'premium'),
  ('Who is more likely to remember every family member''s birthday?', 'Family', 'premium'),
  ('Who is more likely to plan the next family reunion?', 'Family', 'premium'),
  ('Who is more likely to volunteer to host the holidays?', 'Family', 'premium'),
  ('Who is more likely to tell embarrassing stories about their own childhood?', 'Family', 'premium'),
  ('Who is more likely to be the favorite among nieces and nephews?', 'Family', 'premium'),
  ('Who is more likely to keep old family photos neatly organized?', 'Family', 'premium'),
  ('Who is more likely to plan a surprise visit to family?', 'Family', 'premium'),
  ('Who is more likely to want to start a brand-new family tradition?', 'Family', 'premium'),
  ('Who is more likely to know all the family recipes by heart?', 'Family', 'premium'),
  ('Who is more likely to play peacekeeper during family disagreements?', 'Family', 'premium'),
  ('Who is more likely to call a sibling just to chat?', 'Family', 'premium'),
  ('Who is more likely to remember the names of distant relatives?', 'Family', 'premium'),
  ('Who is more likely to want to host a big family dinner?', 'Family', 'premium'),
  ('Who is more likely to run the family group chat?', 'Family', 'premium'),
  ('Who is more likely to plan a family game night?', 'Family', 'premium'),
  ('Who is more likely to want to dig into the family tree?', 'Family', 'premium'),
  ('Who is more likely to keep in touch with cousins who live far away?', 'Family', 'premium'),
  ('Who is more likely to bring the camera to family gatherings?', 'Family', 'premium'),
  ('Who is more likely to suggest a family trip?', 'Family', 'premium'),
  ('Who is more likely to still repeat a grandparent''s favorite saying?', 'Family', 'premium'),
  ('Who is more likely to get sentimental about family heirlooms?', 'Family', 'premium'),
  ('Who is more likely to want to pass down family recipes?', 'Family', 'premium'),
  ('Who is more likely to plan a surprise party for a family member?', 'Family', 'premium'),
  ('Who is more likely to be the go-to for family advice?', 'Family', 'premium'),
  ('Who is more likely to want to video call family regularly?', 'Family', 'premium'),
  ('Who is more likely to curate the family photo albums?', 'Family', 'premium'),
  ('Who is more likely to remember tiny details from family stories at dinner?', 'Family', 'premium'),
  ('Who is more likely to want to visit family more than planned?', 'Family', 'premium'),
  ('Who is more likely to always run late to family gatherings?', 'Family', 'premium'),
  ('Who is more likely to bring a homemade dish to a family potluck?', 'Family', 'premium'),
  ('Who is more likely to want to start a family scrapbook?', 'Family', 'premium'),
  ('Who is more likely to tear up watching old home videos?', 'Family', 'premium'),
  ('Who is more likely to suggest a family movie night?', 'Family', 'premium'),
  ('Who is more likely to remember the family''s favorite holiday traditions?', 'Family', 'premium'),
  ('Who is more likely to plan a family member''s milestone celebration?', 'Family', 'premium'),
  ('Who is more likely to want to teach a niece or nephew a new skill?', 'Family', 'premium'),
  ('Who is more likely to keep family recipe cards in a special box?', 'Family', 'premium'),
  ('Who is more likely to call to wish a relative a happy anniversary?', 'Family', 'premium'),
  ('Who is more likely to want to plan a big multigenerational trip?', 'Family', 'premium'),
  ('Who is more likely to get sentimental about a childhood home?', 'Family', 'premium'),
  ('Who is more likely to remember the funniest things said at family dinners?', 'Family', 'premium'),
  ('Who is more likely to want to carry on traditions from their own upbringing?', 'Family', 'premium'),
  ('Who is more likely to be the family''s go-to for tech help?', 'Family', 'premium'),
  ('Who is more likely to plan a family cookout in summer?', 'Family', 'premium'),
  ('Who is more likely to want to keep family traditions alive for the next generation?', 'Family', 'premium'),
  ('Who is more likely to use a budgeting app?', 'Money & Finances', 'premium'),
  ('Who is more likely to make a spontaneous splurge purchase?', 'Money & Finances', 'premium'),
  ('Who is more likely to hunt down the best deal before buying anything?', 'Money & Finances', 'premium'),
  ('Who is more likely to keep receipts in case of a warranty claim?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to split a bill down to the exact cent?', 'Money & Finances', 'premium'),
  ('Who is more likely to come up with a fun way to save for a trip?', 'Money & Finances', 'premium'),
  ('Who is more likely to get excited over a good coupon?', 'Money & Finances', 'premium'),
  ('Who is more likely to round up purchases for a savings challenge?', 'Money & Finances', 'premium'),
  ('Who is more likely to keep spare change in a jar?', 'Money & Finances', 'premium'),
  ('Who is more likely to set a savings goal for something fun?', 'Money & Finances', 'premium'),
  ('Who is more likely to compare prices across three different stores?', 'Money & Finances', 'premium'),
  ('Who is more likely to track the shared grocery budget?', 'Money & Finances', 'premium'),
  ('Who is more likely to wait patiently for a sale before buying something?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to try a no-spend month?', 'Money & Finances', 'premium'),
  ('Who is more likely to know exactly what they spent this week?', 'Money & Finances', 'premium'),
  ('Who is more likely to get excited about opening a high-interest savings account?', 'Money & Finances', 'premium'),
  ('Who is more likely to try to negotiate a better price?', 'Money & Finances', 'premium'),
  ('Who is more likely to plan a budget-friendly date night?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to try meal prepping to save money?', 'Money & Finances', 'premium'),
  ('Who is more likely to remember to use a gift card before it expires?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest splitting a subscription to save money?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to sell old clothes online?', 'Money & Finances', 'premium'),
  ('Who is more likely to keep tabs on small subscriptions to avoid waste?', 'Money & Finances', 'premium'),
  ('Who is more likely to get excited about cashback rewards?', 'Money & Finances', 'premium'),
  ('Who is more likely to set up a fun fund for weekend activities?', 'Money & Finances', 'premium'),
  ('Who is more likely to propose a friendly savings competition?', 'Money & Finances', 'premium'),
  ('Who is more likely to plan ahead for holiday gift budgets?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to try couponing for groceries?', 'Money & Finances', 'premium'),
  ('Who is more likely to keep loyalty cards neatly organized?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest a joint savings jar for a big trip?', 'Money & Finances', 'premium'),
  ('Who is more likely to get excited finding a bargain at a thrift store?', 'Money & Finances', 'premium'),
  ('Who is more likely to track spending in a spreadsheet for fun?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest cooking at home to save money that week?', 'Money & Finances', 'premium'),
  ('Who is more likely to remember exactly when a bill is due?', 'Money & Finances', 'premium'),
  ('Who is more likely to set up automatic transfers to savings?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest a garage sale to declutter and earn cash?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to celebrate a work bonus?', 'Money & Finances', 'premium'),
  ('Who is more likely to plan a low-cost weekend getaway?', 'Money & Finances', 'premium'),
  ('Who is more likely to keep a running list of things to save up for?', 'Money & Finances', 'premium'),
  ('Who is more likely to double-check a receipt for errors?', 'Money & Finances', 'premium'),
  ('Who is more likely to want to try a cash-only week just for fun?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest splitting future big purchases evenly?', 'Money & Finances', 'premium'),
  ('Who is more likely to get excited about using airline miles or points?', 'Money & Finances', 'premium'),
  ('Who is more likely to set a fun money goal, like a new gadget?', 'Money & Finances', 'premium'),
  ('Who is more likely to suggest a home-cooked date instead of dining out?', 'Money & Finances', 'premium'),
  ('Who is more likely to plan the budget for a big celebration?', 'Money & Finances', 'premium'),
  ('Who is more likely to return extra change if a cashier makes a mistake?', 'Moral Values', 'premium'),
  ('Who is more likely to hold the door open for a stranger?', 'Moral Values', 'premium'),
  ('Who is more likely to give up their seat on public transport?', 'Moral Values', 'premium'),
  ('Who is more likely to hand in a lost wallet found on the street?', 'Moral Values', 'premium'),
  ('Who is more likely to help a stranger carry their groceries?', 'Moral Values', 'premium'),
  ('Who is more likely to speak up for someone being treated unfairly?', 'Moral Values', 'premium'),
  ('Who is more likely to donate old clothes instead of tossing them?', 'Moral Values', 'premium'),
  ('Who is more likely to volunteer for a local cause?', 'Moral Values', 'premium'),
  ('Who is more likely to tip generously?', 'Moral Values', 'premium'),
  ('Who is more likely to pick up litter that isn''t theirs?', 'Moral Values', 'premium'),
  ('Who is more likely to let someone go ahead of them in line?', 'Moral Values', 'premium'),
  ('Who is more likely to write a genuine thank-you note?', 'Moral Values', 'premium'),
  ('Who is more likely to compliment a stranger''s outfit out loud?', 'Moral Values', 'premium'),
  ('Who is more likely to stop to help someone who dropped their things?', 'Moral Values', 'premium'),
  ('Who is more likely to give directions to a lost tourist?', 'Moral Values', 'premium'),
  ('Who is more likely to adopt a pet instead of buying one?', 'Moral Values', 'premium'),
  ('Who is more likely to leave a glowing review for a small business?', 'Moral Values', 'premium'),
  ('Who is more likely to share credit for a group achievement?', 'Moral Values', 'premium'),
  ('Who is more likely to check in on a friend who seems down?', 'Moral Values', 'premium'),
  ('Who is more likely to return a shopping cart to the corral?', 'Moral Values', 'premium'),
  ('Who is more likely to give up a great parking spot for someone who needs it more?', 'Moral Values', 'premium'),
  ('Who is more likely to speak up against a rude comment made to someone else?', 'Moral Values', 'premium'),
  ('Who is more likely to offer to help a neighbor with yard work?', 'Moral Values', 'premium'),
  ('Who is more likely to give a stranger the benefit of the doubt?', 'Moral Values', 'premium'),
  ('Who is more likely to remember to say please and thank you?', 'Moral Values', 'premium'),
  ('Who is more likely to help a coworker without expecting credit?', 'Moral Values', 'premium'),
  ('Who is more likely to donate to a cause they truly believe in?', 'Moral Values', 'premium'),
  ('Who is more likely to apologize first, even when it''s not their fault?', 'Moral Values', 'premium'),
  ('Who is more likely to let a stranger''s small mistake slide with grace?', 'Moral Values', 'premium'),
  ('Who is more likely to offer their umbrella to someone caught in the rain?', 'Moral Values', 'premium'),
  ('Who is more likely to speak kindly about people who aren''t in the room?', 'Moral Values', 'premium'),
  ('Who is more likely to help someone practice for a big interview?', 'Moral Values', 'premium'),
  ('Who is more likely to offer to babysit for a friend in need?', 'Moral Values', 'premium'),
  ('Who is more likely to stay patient with someone learning something new?', 'Moral Values', 'premium'),
  ('Who is more likely to stick up for the underdog?', 'Moral Values', 'premium'),
  ('Who is more likely to give an honest but kind opinion when asked?', 'Moral Values', 'premium'),
  ('Who is more likely to help a stranger whose car broke down?', 'Moral Values', 'premium'),
  ('Who is more likely to respect a differing opinion during a debate?', 'Moral Values', 'premium'),
  ('Who is more likely to keep a promise even when it''s inconvenient?', 'Moral Values', 'premium'),
  ('Who is more likely to thank a service worker by name?', 'Moral Values', 'premium'),
  ('Who is more likely to make a point to include someone being left out?', 'Moral Values', 'premium'),
  ('Who is more likely to offer a comforting word to a crying stranger?', 'Moral Values', 'premium'),
  ('Who is more likely to flag it when a cashier forgets to charge for something?', 'Moral Values', 'premium'),
  ('Who is more likely to give credit to someone else''s idea in a meeting?', 'Moral Values', 'premium'),
  ('Who is more likely to offer to switch seats so a family can sit together?', 'Moral Values', 'premium'),
  ('Who is more likely to handle a bad day with grace instead of taking it out on others?', 'Moral Values', 'premium'),
  ('Who is more likely to try a brand-new hobby on a whim?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to binge an entire TV series in one weekend?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to go for a run at 6am?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to keep a slightly quirky collection of something?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to start a DIY home project?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to read three books at once?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn an instrument?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to spend hours wandering a hardware store?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to try out a new workout class?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get really into a video game?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to try painting or drawing?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to keep a thriving plant collection?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to always be up for a hike?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get hooked on a new podcast?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn photography?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to keep up a regular yoga or meditation practice?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to rearrange the furniture just for fun?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to try rock climbing?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to binge a new true-crime series?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to spend a whole weekend thrifting?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to try pottery or ceramics?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to keep a daily journaling habit?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get fiercely competitive during board game night?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn a new language for fun?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get into birdwatching or nature walks?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to try a recipe just because they saw it online?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to start a garden?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get really into fantasy football or sports stats?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to try woodworking as a hobby?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn to surf or skateboard?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to keep an extensive movie watchlist?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to read their horoscope daily?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to try stand-up paddleboarding?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get really into a fitness tracking app?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn calligraphy?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to spend a Saturday reorganizing a closet for fun?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to collect vinyl records or old music formats?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to try an escape room?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get obsessed with a new hobby for exactly one month?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to always have a puzzle going somewhere in the house?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn to knit or crochet?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to sign up for a triathlon or fitness challenge?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get into home brewing or making their own drinks?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to start a book club?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to get really into speedrunning a video game?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to want to learn to scuba dive or snorkel?', 'Hobbies & Lifestyle', 'premium'),
  ('Who is more likely to bring up a deep question during a car ride?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about childhood memories before bed?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask playful "what if" questions?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to unpack a thought-provoking documentary afterward?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a favorite life lesson unprompted?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about future goals over dinner?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner is most grateful for?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to reflect on how far they''ve come this year?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a philosophical question out of nowhere?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about dreams and aspirations late at night?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask about their partner''s proudest moment?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to discuss what happiness really means?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a meaningful quote they just read?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about personal growth?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner would do with a completely free year?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to reflect on lessons learned from a hard experience?', 'Deep Conversations', 'premium'),
  ('Who is more likely to pose a "what would you do" hypothetical?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about what they''d want to be remembered for?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask about their partner''s biggest inspiration?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to discuss the values that matter most to them?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a meaningful conversation from years ago?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about what makes a good life?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner''s younger self would think of them now?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to discuss a book that changed how they see things?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a question about what success really means?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about gratitude before falling asleep?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner is most curious about?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to reflect on a shared memory that shaped them?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a question about legacy or purpose?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk through their bucket list dreams?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner would tell their younger self?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to discuss what makes them feel most alive?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a conversation about values after watching a movie?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about what "home" really means to them?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask their partner what they''re most proud of this year?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to reflect on how they''ve grown together as a couple?', 'Deep Conversations', 'premium'),
  ('Who is more likely to pose an existential question during a long drive?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about what they''d do if fear wasn''t a factor?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask about a lesson their partner learned the hard way?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to discuss what a perfect ordinary day looks like?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a conversation about what truly matters in life?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk about their proudest personal-growth moment?', 'Deep Conversations', 'premium'),
  ('Who is more likely to ask what their partner hopes for in the next five years?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to reflect on a moment that changed their outlook?', 'Deep Conversations', 'premium'),
  ('Who is more likely to bring up a conversation about what kindness means to them?', 'Deep Conversations', 'premium'),
  ('Who is more likely to want to talk deeply about their hopes for the future?', 'Deep Conversations', 'premium');
