-- 420 daily questions, so the bank is a bank rather than a few months.
--
-- 20261102000000 created the table and seeded it from the existing deep-conversation topics, which
-- was enough to keep the feature working but left it where it had been: 262 questions, about eight
-- months at one a day. This is the content that makes it a real pool — 682 in total, closer to two
-- years, and worth topping up long before anyone reaches the end.
--
-- Written for how the daily question is actually used, which is not how a deck is used:
--
--   * Each one stands alone. Selection is random, so a question cannot lean on the one before it.
--     Nine of these were drafted as follow-ups ("What''s one you''d like to change?") and rewritten
--     once that was obvious, because out of context they are unanswerable.
--   * Both partners answer independently and then compare, so nothing asks a couple to decide
--     something together or to act in the same room.
--   * Nothing assumes co-location. "What should we cook tonight" is not a question this app can
--     ask most of its users.
--
-- Three categories are new. "Distance & Reunion" is the conspicuous one: the app is built for
-- couples living apart and the bank had nothing about the distance itself — not the goodbyes, not
-- the countdowns, not the question of closing it. "Growth & Change" and "Dreams & Future" cover the
-- forward-looking half that the deck topics, written for themed sessions, mostly skip.
--
-- Guarded on the question text so a re-run inserts nothing, and so an edit made in the Studio is
-- never overwritten by a later deploy.

insert into public.daily_questions (question, category)
select v.question, v.category
from (values
  ('What''s the first thing you want to do when we''re next in the same room?', 'Distance & Reunion'),
  ('What part of the distance has got easier than you expected?', 'Distance & Reunion'),
  ('What part of the distance has never got easier?', 'Distance & Reunion'),
  ('What''s a small ritual of ours that makes the distance feel shorter?', 'Distance & Reunion'),
  ('When do you miss me most — a time of day, or a kind of moment?', 'Distance & Reunion'),
  ('What''s something you''ve learned about yourself from being apart?', 'Distance & Reunion'),
  ('What do you wish I understood about your days without me?', 'Distance & Reunion'),
  ('What''s the hardest part of saying goodbye at an airport?', 'Distance & Reunion'),
  ('What''s something you''ve started doing alone that you''d like us to do together?', 'Distance & Reunion'),
  ('How do you want to spend our first evening back together — out, or in?', 'Distance & Reunion'),
  ('What''s a moment from a past reunion you still think about?', 'Distance & Reunion'),
  ('What would make the last week before we see each other feel better?', 'Distance & Reunion'),
  ('What''s something you save up to tell me rather than texting?', 'Distance & Reunion'),
  ('How do you want me to check in when you''re having a hard week?', 'Distance & Reunion'),
  ('What''s a place near you that you want to show me first?', 'Distance & Reunion'),
  ('What do you do on the days the distance feels pointless?', 'Distance & Reunion'),
  ('What''s one thing about long distance you''d genuinely miss?', 'Distance & Reunion'),
  ('What''s a photo of me you keep coming back to?', 'Distance & Reunion'),
  ('How has being apart changed how you argue with me?', 'Distance & Reunion'),
  ('What''s something you want us to plan before the next goodbye?', 'Distance & Reunion'),
  ('What''s the last thing that made you wish I''d been there?', 'Distance & Reunion'),
  ('Do you prefer a countdown to the next visit, or not thinking about it?', 'Distance & Reunion'),
  ('What''s something small I do from far away that lands more than I know?', 'Distance & Reunion'),
  ('What''s a fear about the distance you haven''t said out loud?', 'Distance & Reunion'),
  ('What would closing the distance actually look like, practically?', 'Distance & Reunion'),
  ('What are you most looking forward to about ordinary days together?', 'Distance & Reunion'),
  ('What''s a habit you''d have to give up if we lived together?', 'Distance & Reunion'),
  ('What''s the best conversation we''ve had over a bad connection?', 'Distance & Reunion'),
  ('When we''re apart, what makes you feel most chosen?', 'Distance & Reunion'),
  ('What''s something you want to be true of us a year from now?', 'Distance & Reunion'),
  ('What''s the best thing that happened to you this week?', 'Starters'),
  ('What are you looking forward to in the next month?', 'Starters'),
  ('What''s something small that made you smile today?', 'Starters'),
  ('What''s on your mind that you haven''t mentioned?', 'Starters'),
  ('How are you, actually?', 'Starters'),
  ('What''s been taking up the most space in your head lately?', 'Starters'),
  ('What did you need more of this week?', 'Starters'),
  ('What''s a small win you haven''t told anyone about?', 'Starters'),
  ('What''s something you''re avoiding right now?', 'Starters'),
  ('What''s the last thing that genuinely surprised you?', 'Starters'),
  ('What are you proud of this week?', 'Starters'),
  ('What''s something you want to do differently next week?', 'Starters'),
  ('What''s the best thing you''ve eaten recently?', 'Starters'),
  ('What''s a song you''ve had on repeat?', 'Starters'),
  ('What made you laugh most recently?', 'Starters'),
  ('What''s been draining you lately?', 'Starters'),
  ('What''s something you''re curious about at the moment?', 'Starters'),
  ('What''s the nicest thing someone did for you recently?', 'Starters'),
  ('What would have made today better?', 'Starters'),
  ('What''s a decision you''re sitting on?', 'Starters'),
  ('What''s something you''ve been putting off that would only take an hour?', 'Starters'),
  ('What''s the last thing you changed your mind about?', 'Starters'),
  ('What''s something you''d like to be asked more often?', 'Starters'),
  ('What''s your honest energy level this week, out of ten?', 'Starters'),
  ('What do you want the rest of this month to feel like?', 'Starters'),
  ('What''s a small thing you''re grateful for right now?', 'Starters'),
  ('What''s the best message you received this week?', 'Starters'),
  ('What''s something you''re looking forward to that''s far off?', 'Starters'),
  ('What''s a tiny thing that''s been annoying you?', 'Starters'),
  ('What would a genuinely good day look like tomorrow?', 'Starters'),
  ('What''s a belief you held strongly at twenty that you''ve dropped?', 'Get to Know Each Other'),
  ('What''s something you''re good at that rarely comes up?', 'Get to Know Each Other'),
  ('What kind of praise actually lands for you?', 'Get to Know Each Other'),
  ('What''s a compliment you''ve never quite believed?', 'Get to Know Each Other'),
  ('What do you do when you''re overwhelmed and nobody''s watching?', 'Get to Know Each Other'),
  ('What''s a part of your personality you had to learn, rather than had?', 'Get to Know Each Other'),
  ('What did you want to be when you were ten, and why?', 'Get to Know Each Other'),
  ('What''s a subject you could talk about for an hour without preparing?', 'Get to Know Each Other'),
  ('What''s something you pretend to enjoy more than you do?', 'Get to Know Each Other'),
  ('How do you know when you actually trust someone?', 'Get to Know Each Other'),
  ('What''s a small thing that instantly puts you in a bad mood?', 'Get to Know Each Other'),
  ('What''s the most useful thing a stranger ever said to you?', 'Get to Know Each Other'),
  ('What''s a risk you took that shaped you?', 'Get to Know Each Other'),
  ('What do you think people misread about you at first?', 'Get to Know Each Other'),
  ('What''s something you''ve never been able to explain well to anyone?', 'Get to Know Each Other'),
  ('What kind of tired are you most often?', 'Get to Know Each Other'),
  ('What''s a fear you''ve mostly outgrown?', 'Get to Know Each Other'),
  ('What''s your relationship with being alone?', 'Get to Know Each Other'),
  ('What''s something you own that you''d genuinely struggle to replace?', 'Get to Know Each Other'),
  ('How do you make a decision you can''t research your way out of?', 'Get to Know Each Other'),
  ('What''s a thing you do purely because you enjoy it?', 'Get to Know Each Other'),
  ('What did you believe about love before you''d been in it?', 'Get to Know Each Other'),
  ('What''s the last skill you tried to learn?', 'Get to Know Each Other'),
  ('What''s something you find easy that others seem to find hard?', 'Get to Know Each Other'),
  ('What''s a memory you return to when you need to feel like yourself?', 'Get to Know Each Other'),
  ('What''s your instinct when someone criticises you fairly?', 'Get to Know Each Other'),
  ('What''s a rule you live by that you''ve never written down?', 'Get to Know Each Other'),
  ('What kind of person do you become when you''re stressed?', 'Get to Know Each Other'),
  ('What''s something you''ve forgiven yourself for?', 'Get to Know Each Other'),
  ('What''s a question you wish people asked you?', 'Get to Know Each Other'),
  ('What do I do that makes you feel most looked after?', 'Relationship'),
  ('What''s something you need from me that you find hard to ask for?', 'Relationship'),
  ('When was the last time you felt really proud of us?', 'Relationship'),
  ('What''s a pattern we fall into that you''d like to change?', 'Relationship'),
  ('How do you want to be comforted when you''re upset?', 'Relationship'),
  ('What''s something I''ve said that stayed with you?', 'Relationship'),
  ('What does a good apology look like to you?', 'Relationship'),
  ('What do we do well that we never talk about?', 'Relationship'),
  ('What''s a small kindness of mine you notice every time?', 'Relationship'),
  ('How do you want us to handle it when one of us is jealous?', 'Relationship'),
  ('What''s something you''d like us to be better at?', 'Relationship'),
  ('What does feeling safe with someone actually mean to you?', 'Relationship'),
  ('When do you feel most distant from me, even when things are fine?', 'Relationship'),
  ('What''s a way I could support your independence better?', 'Relationship'),
  ('What do you think we''d argue about if we lived together?', 'Relationship'),
  ('What''s a compromise we''ve made that you''re glad about?', 'Relationship'),
  ('What''s a compromise we''ve made that you''d like to revisit?', 'Relationship'),
  ('How do you want us to make big decisions together?', 'Relationship'),
  ('What''s something you admire about how I handle hard things?', 'Relationship'),
  ('What''s a version of us you''d like us to grow into?', 'Relationship'),
  ('What do you need after we argue, before we talk it through?', 'Relationship'),
  ('What''s something you''ve stopped doing for me that you''d like to start again?', 'Relationship'),
  ('How do you know when I''m not okay?', 'Relationship'),
  ('What''s a boundary of yours I should understand better?', 'Relationship'),
  ('What''s the kindest thing I''ve done that I probably forgot?', 'Relationship'),
  ('What are we like at our best?', 'Relationship'),
  ('What do you want more of from me this month?', 'Relationship'),
  ('What''s something about us you''d defend to anyone?', 'Relationship'),
  ('What''s a small tradition we should start?', 'Relationship'),
  ('What do you hope hasn''t changed about us in ten years?', 'Relationship'),
  ('What''s a moment from our first month you still think about?', 'History'),
  ('When did you first think this might be serious?', 'History'),
  ('What did you assume about me that turned out to be wrong?', 'History'),
  ('What''s the best conversation we''ve ever had?', 'History'),
  ('What''s a day together you''d relive exactly as it was?', 'History'),
  ('What was the hardest thing we''ve got through?', 'History'),
  ('What did you think of me before we spoke properly?', 'History'),
  ('What''s a photo of us you''d put on a wall?', 'History'),
  ('What''s something from early on that you miss?', 'History'),
  ('What''s a joke of ours nobody else would understand?', 'History'),
  ('What''s the first thing you told a friend about me?', 'History'),
  ('What''s a small moment that meant more than the big ones?', 'History'),
  ('When did you last feel that early-days nervousness with me?', 'History'),
  ('What''s a plan we made that never happened?', 'History'),
  ('What''s the most nervous you''ve been around me?', 'History'),
  ('What''s changed most about how we talk?', 'History'),
  ('What was the first meal we shared that you remember?', 'History'),
  ('What''s a gift between us you still have?', 'History'),
  ('What did our first goodbye feel like?', 'History'),
  ('What''s something you almost said early on but didn''t?', 'History'),
  ('Which trip of ours would you do again first?', 'History'),
  ('What''s a habit of mine you noticed immediately?', 'History'),
  ('What''s the bravest thing either of us has done for the other?', 'History'),
  ('What''s a song that belongs to a specific week of ours?', 'History'),
  ('What''s the funniest misunderstanding we''ve had?', 'History'),
  ('When did you realise we could handle a hard conversation?', 'History'),
  ('What''s a place that means something only to us?', 'History'),
  ('What''s the story of us you tell most often?', 'History'),
  ('What''s a detail from our beginning you''re afraid you''ll forget?', 'History'),
  ('What would you tell us on our first day together?', 'History'),
  ('What''s something from your upbringing you want to keep?', 'Family'),
  ('What''s something you want to leave behind?', 'Family'),
  ('How did your family handle disagreement?', 'Family'),
  ('What did affection look like in your house growing up?', 'Family'),
  ('What do you wish your family understood about you?', 'Family'),
  ('How do you want us to spend holidays long term?', 'Family'),
  ('What''s a family tradition you''d like to continue with me?', 'Family'),
  ('What''s your honest feeling about living near family one day?', 'Family'),
  ('What did your parents get right that you''d copy?', 'Family'),
  ('What''s something you find hard about my family, kindly put?', 'Family'),
  ('How much do you want family involved in our decisions?', 'Family'),
  ('What''s a role you''ve always played in your family?', 'Family'),
  ('Do you want children, and has that answer ever moved?', 'Family'),
  ('What kind of parent do you think you''d be?', 'Family'),
  ('What kind of parent do you think I''d be?', 'Family'),
  ('What would you want a child of ours to learn from you?', 'Family'),
  ('What''s the hardest thing about your family that you rarely say?', 'Family'),
  ('How did your family talk about money?', 'Family'),
  ('What''s something you needed as a child and didn''t get?', 'Family'),
  ('Who in your family do you most want me to know properly?', 'Family'),
  ('What''s a family story you love telling?', 'Family'),
  ('How do you want us to handle it if our families disagree with us?', 'Family'),
  ('What does chosen family mean to you?', 'Family'),
  ('What''s a relative you''ve become more like than you expected?', 'Family'),
  ('What do you want our home to feel like to visitors?', 'Family'),
  ('What''s something about family you''ve changed your mind on?', 'Family'),
  ('How do you want to care for our parents as they age?', 'Family'),
  ('What''s a boundary with family you''ve found hard to hold?', 'Family'),
  ('What would make you feel properly part of my family?', 'Family'),
  ('What''s a family expectation you''ve quietly let go of?', 'Family'),
  ('What did money feel like in your house growing up?', 'Money & Finances'),
  ('What''s a purchase you''ve never regretted?', 'Money & Finances'),
  ('What''s a purchase you regret and still think about?', 'Money & Finances'),
  ('What does financial security actually look like to you?', 'Money & Finances'),
  ('How much should we know about each other''s spending?', 'Money & Finances'),
  ('What would you do with a completely unexpected windfall?', 'Money & Finances'),
  ('What''s something you happily spend more on than most people?', 'Money & Finances'),
  ('What''s something you refuse to pay full price for?', 'Money & Finances'),
  ('How do you feel about debt, honestly?', 'Money & Finances'),
  ('What''s a money habit of yours you''d defend?', 'Money & Finances'),
  ('What''s a money habit of yours you''d like to change?', 'Money & Finances'),
  ('Would you rather earn more or work less?', 'Money & Finances'),
  ('What does ''enough'' look like in numbers, roughly?', 'Money & Finances'),
  ('How should we split things when we earn differently?', 'Money & Finances'),
  ('What''s a financial decision you''re glad you made young?', 'Money & Finances'),
  ('What would you want us to save for first?', 'Money & Finances'),
  ('How do you feel about lending money to family?', 'Money & Finances'),
  ('What''s the most useful money advice you''ve been given?', 'Money & Finances'),
  ('What do you want retirement to look like?', 'Money & Finances'),
  ('What would you cut first if things got tight?', 'Money & Finances'),
  ('How much risk are you comfortable with?', 'Money & Finances'),
  ('What''s something you bought that improved your daily life?', 'Money & Finances'),
  ('Do you think about money more or less than you''d like to?', 'Money & Finances'),
  ('What''s a money conversation we''ve been avoiding?', 'Money & Finances'),
  ('What would you do if you didn''t need to work?', 'Money & Finances'),
  ('How do you want us to handle a big purchase disagreement?', 'Money & Finances'),
  ('What''s your instinct — save it or use it?', 'Money & Finances'),
  ('What did you waste money on in your twenties?', 'Money & Finances'),
  ('What would make you feel generous rather than anxious about spending?', 'Money & Finances'),
  ('What''s a cost of the distance you wish we talked about?', 'Money & Finances'),
  ('What''s a place you''d go back to immediately?', 'Travel'),
  ('What''s somewhere you''ve no interest in, despite everyone loving it?', 'Travel'),
  ('Do you plan a trip or improvise it?', 'Travel'),
  ('What''s the best day you''ve ever had abroad?', 'Travel'),
  ('What kind of accommodation actually matters to you?', 'Travel'),
  ('What''s a trip that changed how you see things?', 'Travel'),
  ('Would you rather one long trip or several short ones?', 'Travel'),
  ('What do you always pack that others wouldn''t?', 'Travel'),
  ('What''s the worst travel day you''ve survived?', 'Travel'),
  ('What''s a city you could live in for a year?', 'Travel'),
  ('What''s your ideal pace on holiday?', 'Travel'),
  ('What''s something you want to see before you''re sixty?', 'Travel'),
  ('Beach, mountains, or a city you can walk?', 'Travel'),
  ('What''s a trip you''d take alone, even now?', 'Travel'),
  ('What''s the best meal you''ve had travelling?', 'Travel'),
  ('What do you find exhausting about travelling that people don''t admit?', 'Travel'),
  ('What''s a place that disappointed you?', 'Travel'),
  ('Where would you take me if I had 48 hours in your favourite country?', 'Travel'),
  ('What''s the furthest you''d go for a long weekend?', 'Travel'),
  ('What''s a journey you''d rather take than fly?', 'Travel'),
  ('What souvenir do you actually keep?', 'Travel'),
  ('What''s the most beautiful thing you''ve seen in person?', 'Travel'),
  ('Where were you happiest on a trip, and why?', 'Travel'),
  ('What would our perfect first proper holiday look like?', 'Travel'),
  ('What''s a trip you regret not taking?', 'Travel'),
  ('How do you feel about going somewhere twice versus somewhere new?', 'Travel'),
  ('What''s the best thing about coming home?', 'Travel'),
  ('What''s a language you''d learn for a place?', 'Travel'),
  ('What''s a travel habit of mine you''d change?', 'Travel'),
  ('Where should we go when we have no constraints at all?', 'Travel'),
  ('What''s a meal that tastes like your childhood?', 'Food & Culture'),
  ('What''s a dish you''d want to learn to make properly?', 'Food & Culture'),
  ('What food do you find genuinely overrated?', 'Food & Culture'),
  ('What''s your order at a place you''ve never been?', 'Food & Culture'),
  ('What''s a food you were made to eat that you now love?', 'Food & Culture'),
  ('What''s the best thing you can cook?', 'Food & Culture'),
  ('What would you eat every day without getting bored?', 'Food & Culture'),
  ('What''s a meal you''d want on a hard day?', 'Food & Culture'),
  ('How important is eating together to you?', 'Food & Culture'),
  ('What''s a tradition around food in your family?', 'Food & Culture'),
  ('What''s a cuisine you''d like us to explore together?', 'Food & Culture'),
  ('What''s the best restaurant meal you''ve had?', 'Food & Culture'),
  ('What do you always keep in the fridge?', 'Food & Culture'),
  ('What''s a film or book that shaped how you see things?', 'Food & Culture'),
  ('What''s a piece of art that''s stayed with you?', 'Food & Culture'),
  ('What''s something popular you''ve never got into?', 'Food & Culture'),
  ('What''s a cultural difference you found surprising?', 'Food & Culture'),
  ('What music did you love at fifteen?', 'Food & Culture'),
  ('What''s a song that still sounds as good as it did when you were fifteen?', 'Food & Culture'),
  ('What''s a book you''d want me to read to understand you?', 'Food & Culture'),
  ('What''s your comfort watch?', 'Food & Culture'),
  ('What''s a celebration from another culture you''d like to try?', 'Food & Culture'),
  ('What''s a food you''d refuse politely at someone''s house?', 'Food & Culture'),
  ('What''s the ritual around your morning drink?', 'Food & Culture'),
  ('What''s the best thing you''ve cooked for someone else?', 'Food & Culture'),
  ('What would be on the menu at our ideal dinner party?', 'Food & Culture'),
  ('Who would you invite to a dinner party of any five people, living or dead?', 'Food & Culture'),
  ('What''s something you loved as a teenager that you''d defend now?', 'Food & Culture'),
  ('What''s a festival or holiday that actually means something to you?', 'Food & Culture'),
  ('What''s a taste you associate with being happy?', 'Food & Culture'),
  ('What do you do that makes time disappear?', 'Hobbies & Lifestyle'),
  ('What''s a hobby you''ve quietly given up on?', 'Hobbies & Lifestyle'),
  ('What would you take up if nobody could see you being bad at it?', 'Hobbies & Lifestyle'),
  ('What does a genuinely restful day look like?', 'Hobbies & Lifestyle'),
  ('Are you a morning person, or have you just adapted?', 'Hobbies & Lifestyle'),
  ('What''s something you do purely for your own head?', 'Hobbies & Lifestyle'),
  ('How do you actually unwind, as opposed to how you say you do?', 'Hobbies & Lifestyle'),
  ('What''s a routine you''d be reluctant to give up?', 'Hobbies & Lifestyle'),
  ('What''s your relationship with exercise right now?', 'Hobbies & Lifestyle'),
  ('What do you want your weekends to feel like?', 'Hobbies & Lifestyle'),
  ('What''s a skill you''d like to have in five years?', 'Hobbies & Lifestyle'),
  ('How much time alone do you need to feel normal?', 'Hobbies & Lifestyle'),
  ('What''s the last thing you made with your hands?', 'Hobbies & Lifestyle'),
  ('What''s your phone habit you''d change if it were easy?', 'Hobbies & Lifestyle'),
  ('What would you do with an unexpected free Saturday?', 'Hobbies & Lifestyle'),
  ('What''s something you enjoy that other people find boring?', 'Hobbies & Lifestyle'),
  ('How do you decide what''s worth your attention?', 'Hobbies & Lifestyle'),
  ('What''s a small luxury you''d struggle to give up?', 'Hobbies & Lifestyle'),
  ('What''s your ideal balance of planned and unplanned time?', 'Hobbies & Lifestyle'),
  ('What''s something you''d like us to do together regularly?', 'Hobbies & Lifestyle'),
  ('What kind of home environment helps you think?', 'Hobbies & Lifestyle'),
  ('What''s a thing you''ve been meaning to fix for months?', 'Hobbies & Lifestyle'),
  ('What''s your relationship with sleep?', 'Hobbies & Lifestyle'),
  ('What would a healthier week actually look like for you?', 'Hobbies & Lifestyle'),
  ('What''s a hobby of mine you''d like to understand better?', 'Hobbies & Lifestyle'),
  ('What do you do when you''re bored?', 'Hobbies & Lifestyle'),
  ('What''s something you used to love that you''d like back?', 'Hobbies & Lifestyle'),
  ('How do you feel about being busy?', 'Hobbies & Lifestyle'),
  ('What''s a place near you where you feel most yourself?', 'Hobbies & Lifestyle'),
  ('What would you do with a whole month off?', 'Hobbies & Lifestyle'),
  ('What''s a principle you wouldn''t bend, even under pressure?', 'Moral Values'),
  ('When is it right to break a promise?', 'Moral Values'),
  ('What''s something widely accepted that you think is wrong?', 'Moral Values'),
  ('How do you decide whether to tell someone a hard truth?', 'Moral Values'),
  ('What''s the difference between kindness and niceness to you?', 'Moral Values'),
  ('When have you changed your mind about something important?', 'Moral Values'),
  ('What do you owe a stranger?', 'Moral Values'),
  ('How much should someone be judged by their worst day?', 'Moral Values'),
  ('What''s a small dishonesty you think is fine?', 'Moral Values'),
  ('What''s a dishonesty you can''t accept?', 'Moral Values'),
  ('When is loyalty the wrong instinct?', 'Moral Values'),
  ('What would you do if you saw a friend behaving badly?', 'Moral Values'),
  ('What''s something you do that you''d be uncomfortable explaining?', 'Moral Values'),
  ('How do you think about giving money away?', 'Moral Values'),
  ('What responsibility do we have for people far away from us?', 'Moral Values'),
  ('What''s a fair way to handle an apology you don''t believe?', 'Moral Values'),
  ('What''s something you''ve forgiven that surprised you?', 'Moral Values'),
  ('What''s something you don''t think you could forgive?', 'Moral Values'),
  ('When does honesty become cruelty?', 'Moral Values'),
  ('What would you risk your comfort for?', 'Moral Values'),
  ('How do you tell the difference between a boundary and a punishment?', 'Moral Values'),
  ('What''s a value you were raised with that you''ve rejected?', 'Moral Values'),
  ('What''s a value you rejected and later came back to?', 'Moral Values'),
  ('What does integrity look like when nobody''s checking?', 'Moral Values'),
  ('How should we treat people who can do nothing for us?', 'Moral Values'),
  ('What''s the most ethical thing you''ve seen someone do quietly?', 'Moral Values'),
  ('When is it right to intervene in someone else''s business?', 'Moral Values'),
  ('What do you think you''d be willing to protest about?', 'Moral Values'),
  ('What''s a moral question you genuinely don''t know the answer to?', 'Moral Values'),
  ('What do you want to be known for standing for?', 'Moral Values'),
  ('What''s something you want more of that you''ve never asked for?', 'Edgy Questions'),
  ('What''s the most attracted you''ve ever been to me?', 'Edgy Questions'),
  ('What''s a fantasy you''d only admit to me?', 'Edgy Questions'),
  ('What do you find attractive that surprises people?', 'Edgy Questions'),
  ('What''s something I do that you find unreasonably appealing?', 'Edgy Questions'),
  ('What''s a compliment you wish I''d give more often?', 'Edgy Questions'),
  ('What''s the boldest thing you''ve ever done for someone?', 'Edgy Questions'),
  ('What''s something you''ve never told me about an ex?', 'Edgy Questions'),
  ('What''s a jealousy you''ve felt and not mentioned?', 'Edgy Questions'),
  ('What''s a hard truth about us you think we could handle?', 'Edgy Questions'),
  ('What''s something you''ve wanted to say during an argument and didn''t?', 'Edgy Questions'),
  ('What''s the closest you''ve come to walking away from something good?', 'Edgy Questions'),
  ('What do you think I''d be shocked to learn about you?', 'Edgy Questions'),
  ('What''s a rule you''d break with me?', 'Edgy Questions'),
  ('What''s the most reckless thing you''d still do?', 'Edgy Questions'),
  ('What''s something about intimacy you wish were easier to talk about?', 'Edgy Questions'),
  ('What''s a part of your body you wish you liked more?', 'Edgy Questions'),
  ('What''s a part of mine you like most?', 'Edgy Questions'),
  ('What''s something you want us to try?', 'Edgy Questions'),
  ('What''s a moment you replay in your head?', 'Edgy Questions'),
  ('What''s the most honest thing you''ve ever said to someone?', 'Edgy Questions'),
  ('What do you hide best?', 'Edgy Questions'),
  ('What''s a lie you''ve told that you''d tell again?', 'Edgy Questions'),
  ('What''s a thought you''ve had about our future that scared you?', 'Edgy Questions'),
  ('What''s something you''d change about how we are together?', 'Edgy Questions'),
  ('What''s the angriest you''ve been with me, and did I know?', 'Edgy Questions'),
  ('What do you need to feel wanted?', 'Edgy Questions'),
  ('What''s a secret you''d take to the grave, in general terms?', 'Edgy Questions'),
  ('What''s something you''re embarrassed to find funny?', 'Edgy Questions'),
  ('What would you do differently if nobody would ever find out?', 'Edgy Questions'),
  ('What''s something you''re working on about yourself right now?', 'Growth & Change'),
  ('What''s a habit you''ve broken that you''re proud of?', 'Growth & Change'),
  ('How have you changed in the last three years?', 'Growth & Change'),
  ('What''s a criticism you''ve received that turned out to be right?', 'Growth & Change'),
  ('What do you want to be less afraid of?', 'Growth & Change'),
  ('What''s something you''ve outgrown but still catch yourself doing?', 'Growth & Change'),
  ('What would the you of ten years ago find hardest to believe?', 'Growth & Change'),
  ('What''s a goal you''ve quietly abandoned, and was that right?', 'Growth & Change'),
  ('What does progress look like when it''s slow?', 'Growth & Change'),
  ('What''s something you''re better at than you were a year ago?', 'Growth & Change'),
  ('What do you avoid because you might not be good at it?', 'Growth & Change'),
  ('What''s a belief you''re holding loosely at the moment?', 'Growth & Change'),
  ('Who has changed you most, and how?', 'Growth & Change'),
  ('What''s a mistake you''d make again?', 'Growth & Change'),
  ('What are you still learning how to do?', 'Growth & Change'),
  ('What would you like to have made peace with by this time next year?', 'Growth & Change'),
  ('What''s the most useful thing failure has taught you?', 'Growth & Change'),
  ('What''s a compliment you''ve had to grow into?', 'Growth & Change'),
  ('What''s something you''ve had to unlearn?', 'Growth & Change'),
  ('Where do you want to be braver?', 'Growth & Change'),
  ('What''s a version of yourself you''re glad you left behind?', 'Growth & Change'),
  ('What are you curious about that you never pursue?', 'Growth & Change'),
  ('What would you attempt if you knew it would take five years?', 'Growth & Change'),
  ('What''s something small you''ve changed that made a real difference?', 'Growth & Change'),
  ('How do you know when you''ve genuinely grown rather than just coped?', 'Growth & Change'),
  ('What do you want to have more patience for?', 'Growth & Change'),
  ('What''s a hard thing that turned out to be good for you?', 'Growth & Change'),
  ('What''s a strength of yours that''s also a problem?', 'Growth & Change'),
  ('What do you want to stop apologising for?', 'Growth & Change'),
  ('What''s the next honest step for you?', 'Growth & Change'),
  ('What does your ideal ordinary Tuesday look like in five years?', 'Dreams & Future'),
  ('Where do you want to be living, honestly?', 'Dreams & Future'),
  ('What''s an ambition you''ve never said out loud?', 'Dreams & Future'),
  ('What do you want our home to be like?', 'Dreams & Future'),
  ('What would make you feel your life had gone well?', 'Dreams & Future'),
  ('What''s something you want to build?', 'Dreams & Future'),
  ('What do you hope is still true about you at seventy?', 'Dreams & Future'),
  ('What would you do with a year and no obligations?', 'Dreams & Future'),
  ('What''s a milestone you''re quietly working towards?', 'Dreams & Future'),
  ('What do you want us to have done together by this time next year?', 'Dreams & Future'),
  ('What''s a dream you''ve let go of, and do you miss it?', 'Dreams & Future'),
  ('How do you feel about growing older?', 'Dreams & Future'),
  ('What''s something you want to be brave enough to try?', 'Dreams & Future'),
  ('What kind of work would feel worth doing?', 'Dreams & Future'),
  ('What do you want more of in your life generally?', 'Dreams & Future'),
  ('What''s a place you''d want to end up?', 'Dreams & Future'),
  ('What would you want written about us?', 'Dreams & Future'),
  ('What''s a promise you''d like us to make?', 'Dreams & Future'),
  ('What are you most hopeful about?', 'Dreams & Future'),
  ('What''s the version of the future that worries you?', 'Dreams & Future'),
  ('What would you do if this all worked out?', 'Dreams & Future'),
  ('What''s something you want to own one day?', 'Dreams & Future'),
  ('What do you want to be doing on an ordinary Sunday at sixty?', 'Dreams & Future'),
  ('What''s a legacy that would mean something to you?', 'Dreams & Future'),
  ('What would you want us to be known for as a couple?', 'Dreams & Future'),
  ('What''s a small future thing you''re looking forward to?', 'Dreams & Future'),
  ('What''s the first big thing we should do once we''re in the same place?', 'Dreams & Future'),
  ('What do you hope never changes?', 'Dreams & Future'),
  ('What would you regret not trying?', 'Dreams & Future'),
  ('What does a good life look like, in your own words?', 'Dreams & Future')) as v(question, category)
where not exists (
  select 1 from public.daily_questions d where lower(trim(d.question)) = lower(trim(v.question))
);
