-- Seeds the premium-tier "This or That" prompt bank: 460 varied preference pairs across 10 categories.
insert into public.this_or_that_prompts (option_a, option_b, category, tier) values
  ('Morning person', 'Night owl', 'Starters', 'premium'),
  ('Coffee', 'Tea', 'Starters', 'premium'),
  ('Sweet snacks', 'Salty snacks', 'Starters', 'premium'),
  ('Summer', 'Winter', 'Starters', 'premium'),
  ('Mountains', 'Ocean', 'Starters', 'premium'),
  ('Dogs', 'Cats', 'Starters', 'premium'),
  ('Books', 'Movies', 'Starters', 'premium'),
  ('Texting', 'Calling', 'Starters', 'premium'),
  ('Window seat', 'Aisle seat', 'Starters', 'premium'),
  ('Early dinner', 'Late night dinner', 'Starters', 'premium'),
  ('Sunrise', 'Sunset', 'Starters', 'premium'),
  ('Pizza', 'Burgers', 'Starters', 'premium'),
  ('Rain', 'Snow', 'Starters', 'premium'),
  ('Board games', 'Video games', 'Starters', 'premium'),
  ('Comedy', 'Drama', 'Starters', 'premium'),
  ('Chocolate', 'Vanilla', 'Starters', 'premium'),
  ('Warm shower', 'Cold plunge', 'Starters', 'premium'),
  ('Handwritten notes', 'Text messages', 'Starters', 'premium'),
  ('Music on', 'Silence', 'Starters', 'premium'),
  ('Big parties', 'Small gatherings', 'Starters', 'premium'),
  ('Sneakers', 'Sandals', 'Starters', 'premium'),
  ('Fiction', 'Non-fiction', 'Starters', 'premium'),
  ('Camping', 'Hotel stays', 'Starters', 'premium'),
  ('Spontaneous plans', 'Planned schedules', 'Starters', 'premium'),
  ('Blankets', 'Air conditioning', 'Starters', 'premium'),
  ('Podcasts', 'Playlists', 'Starters', 'premium'),
  ('Sparkling water', 'Still water', 'Starters', 'premium'),
  ('Museums', 'Amusement parks', 'Starters', 'premium'),
  ('City lights', 'Starry skies', 'Starters', 'premium'),
  ('Popcorn', 'Candy', 'Starters', 'premium'),
  ('Long showers', 'Quick showers', 'Starters', 'premium'),
  ('Autumn leaves', 'Spring blossoms', 'Starters', 'premium'),
  ('Puzzles', 'Card games', 'Starters', 'premium'),
  ('Naps', 'Walks', 'Starters', 'premium'),
  ('Bright colors', 'Neutral tones', 'Starters', 'premium'),
  ('Street food', 'Sit-down restaurants', 'Starters', 'premium'),
  ('Early flights', 'Late flights', 'Starters', 'premium'),
  ('Soft pillows', 'Firm pillows', 'Starters', 'premium'),
  ('Handshake hello', 'Hug hello', 'Starters', 'premium'),
  ('Weekend lie-in', 'Weekend early start', 'Starters', 'premium'),
  ('Fresh fruit', 'Ice cream', 'Starters', 'premium'),
  ('Sunny days', 'Cloudy days', 'Starters', 'premium'),
  ('Crossword puzzles', 'Sudoku', 'Starters', 'premium'),
  ('Umbrellas', 'Raincoats', 'Starters', 'premium'),
  ('Elevators', 'Stairs', 'Starters', 'premium'),
  ('Fireplace nights', 'Beach bonfires', 'Starters', 'premium'),
  ('Introvert energy', 'Extrovert energy', 'Get to Know Each Other', 'premium'),
  ('Planner', 'Free spirit', 'Get to Know Each Other', 'premium'),
  ('Optimist', 'Realist', 'Get to Know Each Other', 'premium'),
  ('Early riser', 'Night owl by nature', 'Get to Know Each Other', 'premium'),
  ('Big dreamer', 'Practical thinker', 'Get to Know Each Other', 'premium'),
  ('Leader in a group', 'Supporter in a group', 'Get to Know Each Other', 'premium'),
  ('Talk it out', 'Think it through alone', 'Get to Know Each Other', 'premium'),
  ('Collector of hobbies', 'Master of one hobby', 'Get to Know Each Other', 'premium'),
  ('Rule follower', 'Rule bender', 'Get to Know Each Other', 'premium'),
  ('Loud laugher', 'Quiet chuckler', 'Get to Know Each Other', 'premium'),
  ('Neat and tidy', 'Organised chaos', 'Get to Know Each Other', 'premium'),
  ('Deep thinker', 'Live in the moment', 'Get to Know Each Other', 'premium'),
  ('Competitive', 'Easygoing', 'Get to Know Each Other', 'premium'),
  ('Detail-oriented', 'Big picture thinker', 'Get to Know Each Other', 'premium'),
  ('Homebody', 'Always out and about', 'Get to Know Each Other', 'premium'),
  ('Risk-taker', 'Cautious planner', 'Get to Know Each Other', 'premium'),
  ('Multitasker', 'One thing at a time', 'Get to Know Each Other', 'premium'),
  ('Storyteller', 'Good listener', 'Get to Know Each Other', 'premium'),
  ('Adventurous eater', 'Creature of habit', 'Get to Know Each Other', 'premium'),
  ('Logical decisions', 'Gut-feeling decisions', 'Get to Know Each Other', 'premium'),
  ('List-maker', 'Mental notes', 'Get to Know Each Other', 'premium'),
  ('Early adopter of trends', 'Wait and see', 'Get to Know Each Other', 'premium'),
  ('Group project lead', 'Behind the scenes worker', 'Get to Know Each Other', 'premium'),
  ('Bold with new people', 'Slow to warm up', 'Get to Know Each Other', 'premium'),
  ('Loves surprises', 'Prefers a heads-up', 'Get to Know Each Other', 'premium'),
  ('Talks with hands', 'Calm and still', 'Get to Know Each Other', 'premium'),
  ('Collects stories', 'Collects facts', 'Get to Know Each Other', 'premium'),
  ('Sings in the shower', 'Hums quietly', 'Get to Know Each Other', 'premium'),
  ('Overpacks for trips', 'Packs light', 'Get to Know Each Other', 'premium'),
  ('Says yes to everything', 'Weighs it first', 'Get to Know Each Other', 'premium'),
  ('Thrives under pressure', 'Prefers a steady pace', 'Get to Know Each Other', 'premium'),
  ('Improviser', 'Rehearser', 'Get to Know Each Other', 'premium'),
  ('Dreams big', 'Sets small steps', 'Get to Know Each Other', 'premium'),
  ('Bounces back fast', 'Needs time to process', 'Get to Know Each Other', 'premium'),
  ('Curious about everything', 'Focused on interests', 'Get to Know Each Other', 'premium'),
  ('Direct communicator', 'Diplomatic communicator', 'Get to Know Each Other', 'premium'),
  ('Quick to commit', 'Keeps options open', 'Get to Know Each Other', 'premium'),
  ('Loves routine', 'Craves variety', 'Get to Know Each Other', 'premium'),
  ('Natural motivator', 'Quiet encourager', 'Get to Know Each Other', 'premium'),
  ('Thinks out loud', 'Thinks in silence', 'Get to Know Each Other', 'premium'),
  ('Texts the joke', 'Tells it in person', 'Get to Know Each Other', 'premium'),
  ('Chases new hobbies', 'Perfects old ones', 'Get to Know Each Other', 'premium'),
  ('Trusts instructions', 'Figures it out solo', 'Get to Know Each Other', 'premium'),
  ('Energised by crowds', 'Energised by quiet', 'Get to Know Each Other', 'premium'),
  ('Plans the trip', 'Goes with the flow', 'Get to Know Each Other', 'premium'),
  ('Journals thoughts', 'Talks them through', 'Get to Know Each Other', 'premium'),
  ('Date night in', 'Date night out', 'Relationship', 'premium'),
  ('Surprise gestures', 'Planned gestures', 'Relationship', 'premium'),
  ('Slow dancing in the kitchen', 'Dancing at a concert', 'Relationship', 'premium'),
  ('Matching outfits', 'Individual styles', 'Relationship', 'premium'),
  ('Cooking together', 'Ordering in together', 'Relationship', 'premium'),
  ('Long hugs', 'Quick kisses', 'Relationship', 'premium'),
  ('Love notes', 'Voice messages', 'Relationship', 'premium'),
  ('Couple''s playlist', 'Couple''s photo album', 'Relationship', 'premium'),
  ('Weekend adventures', 'Weekend relaxing', 'Relationship', 'premium'),
  ('Talking it through right away', 'Cooling off first', 'Relationship', 'premium'),
  ('Affection in public', 'Affection in private', 'Relationship', 'premium'),
  ('Anniversary dinner out', 'Anniversary trip away', 'Relationship', 'premium'),
  ('Shared morning coffee', 'Shared evening walk', 'Relationship', 'premium'),
  ('Team in the kitchen', 'Team on chores', 'Relationship', 'premium'),
  ('Deep talks before bed', 'Comfortable silence before bed', 'Relationship', 'premium'),
  ('Pet names', 'First names', 'Relationship', 'premium'),
  ('Couple''s workout', 'Couple''s cooking class', 'Relationship', 'premium'),
  ('Handwritten love letters', 'Thoughtful gifts', 'Relationship', 'premium'),
  ('Movie night cuddles', 'Board game night banter', 'Relationship', 'premium'),
  ('Big milestone celebrations', 'Quiet milestone moments', 'Relationship', 'premium'),
  ('Same hobbies together', 'Separate hobbies apart', 'Relationship', 'premium'),
  ('Planning the future together', 'Taking it day by day', 'Relationship', 'premium'),
  ('Inside jokes', 'Shared playlists', 'Relationship', 'premium'),
  ('Morning texts', 'Evening calls', 'Relationship', 'premium'),
  ('Couple''s photo shoots', 'Candid everyday photos', 'Relationship', 'premium'),
  ('Reminiscing about the past', 'Talking about the future', 'Relationship', 'premium'),
  ('Spontaneous weekend trip', 'Cosy weekend at home', 'Relationship', 'premium'),
  ('Compliments often', 'Actions over words', 'Relationship', 'premium'),
  ('Debrief the day at dinner', 'Debrief the day in bed', 'Relationship', 'premium'),
  ('Shared bucket list', 'Individual bucket lists', 'Relationship', 'premium'),
  ('Slow mornings together', 'Energetic mornings together', 'Relationship', 'premium'),
  ('Couple''s book club', 'Couple''s series binge', 'Relationship', 'premium'),
  ('Dancing in the living room', 'Singing in the car', 'Relationship', 'premium'),
  ('Saying sorry first', 'Talking it out together', 'Relationship', 'premium'),
  ('Celebrating small wins', 'Saving it for the big ones', 'Relationship', 'premium'),
  ('Couple selfies', 'Couple videos', 'Relationship', 'premium'),
  ('Planning dates a week ahead', 'Deciding on the day', 'Relationship', 'premium'),
  ('Shared calendar', 'Shared notebook', 'Relationship', 'premium'),
  ('Long weekend getaways', 'Day trips', 'Relationship', 'premium'),
  ('Cuddling on the couch', 'Holding hands on a walk', 'Relationship', 'premium'),
  ('Giving each other space', 'Doing everything together', 'Relationship', 'premium'),
  ('Recreating the first date', 'Trying something brand new', 'Relationship', 'premium'),
  ('Gifts for anniversaries', 'Experiences for anniversaries', 'Relationship', 'premium'),
  ('Quiet nights at home', 'Nights out with friends together', 'Relationship', 'premium'),
  ('Texting throughout the day', 'Catching up when together', 'Relationship', 'premium'),
  ('Planning the surprise', 'Asking what they want', 'Relationship', 'premium'),
  ('Beach holiday', 'City break', 'Travel', 'premium'),
  ('Backpacking', 'Luxury resort', 'Travel', 'premium'),
  ('Road trip', 'Flight', 'Travel', 'premium'),
  ('Mountains', 'Countryside', 'Travel', 'premium'),
  ('Guided tours', 'Exploring alone', 'Travel', 'premium'),
  ('All-inclusive resort', 'Local homestay', 'Travel', 'premium'),
  ('Packed itinerary', 'Open schedule', 'Travel', 'premium'),
  ('Solo museum visit', 'Group excursion', 'Travel', 'premium'),
  ('Camping under stars', 'Boutique hotel', 'Travel', 'premium'),
  ('Cruise ship', 'Overland adventure', 'Travel', 'premium'),
  ('Historic old town', 'Modern skyline', 'Travel', 'premium'),
  ('Island hopping', 'One destination deep dive', 'Travel', 'premium'),
  ('Street markets', 'Shopping malls', 'Travel', 'premium'),
  ('Hiking trails', 'Beach lounging', 'Travel', 'premium'),
  ('New country every trip', 'Return to a favourite spot', 'Travel', 'premium'),
  ('Early check-in', 'Late checkout', 'Travel', 'premium'),
  ('Street food tour', 'Fine dining abroad', 'Travel', 'premium'),
  ('Snorkeling', 'Sightseeing', 'Travel', 'premium'),
  ('Train travel', 'Road trip driving', 'Travel', 'premium'),
  ('Winter ski trip', 'Summer beach trip', 'Travel', 'premium'),
  ('National parks', 'National monuments', 'Travel', 'premium'),
  ('Photography-focused trip', 'Relaxation-focused trip', 'Travel', 'premium'),
  ('Big city nightlife', 'Quiet countryside evenings', 'Travel', 'premium'),
  ('Detailed travel plan', 'Rough idea and see what happens', 'Travel', 'premium'),
  ('Souvenir shopping', 'Collecting experiences', 'Travel', 'premium'),
  ('Off the beaten path', 'Popular tourist spots', 'Travel', 'premium'),
  ('Van life', 'Five-star hotel', 'Travel', 'premium'),
  ('Language immersion trip', 'Comfortable English-speaking trip', 'Travel', 'premium'),
  ('Desert safari', 'Rainforest trek', 'Travel', 'premium'),
  ('Wine country tour', 'Craft beer trail', 'Travel', 'premium'),
  ('Weekend city break', 'Two-week deep dive', 'Travel', 'premium'),
  ('Travel light with a backpack', 'Travel prepared with a suitcase', 'Travel', 'premium'),
  ('Night markets', 'Morning markets', 'Travel', 'premium'),
  ('Cultural festivals', 'Nature reserves', 'Travel', 'premium'),
  ('Volunteering abroad', 'Sightseeing abroad', 'Travel', 'premium'),
  ('Beach resort all week', 'Multi-city hopping', 'Travel', 'premium'),
  ('Local buses and trains', 'Private transfers', 'Travel', 'premium'),
  ('Cooking class abroad', 'Cocktail class abroad', 'Travel', 'premium'),
  ('Coastal drive', 'Mountain pass drive', 'Travel', 'premium'),
  ('Historic castles', 'Modern architecture', 'Travel', 'premium'),
  ('Farmers markets abroad', 'Boutique shops abroad', 'Travel', 'premium'),
  ('Adventure sports on holiday', 'Spa days on holiday', 'Travel', 'premium'),
  ('Camper van trip', 'Chartered boat trip', 'Travel', 'premium'),
  ('Off-season travel', 'Peak-season travel', 'Travel', 'premium'),
  ('Foodie city trip', 'Nature retreat', 'Travel', 'premium'),
  ('Travel app for everything', 'Paper map and instinct', 'Travel', 'premium'),
  ('Fancy dinner', 'Cosy night in', 'Food & Culture', 'premium'),
  ('Spicy food', 'Mild food', 'Food & Culture', 'premium'),
  ('Home-cooked meal', 'Restaurant meal', 'Food & Culture', 'premium'),
  ('Brunch', 'Late dinner', 'Food & Culture', 'premium'),
  ('Street food stalls', 'Fine dining', 'Food & Culture', 'premium'),
  ('Sushi', 'Tacos', 'Food & Culture', 'premium'),
  ('Wine pairing', 'Craft beer pairing', 'Food & Culture', 'premium'),
  ('Buffet', 'A la carte', 'Food & Culture', 'premium'),
  ('Family-style sharing plates', 'Individual plates', 'Food & Culture', 'premium'),
  ('Dessert first', 'Dessert last', 'Food & Culture', 'premium'),
  ('Cooking from scratch', 'Meal kits', 'Food & Culture', 'premium'),
  ('Farmers market produce', 'Grocery store convenience', 'Food & Culture', 'premium'),
  ('Barbecue', 'Stovetop cooking', 'Food & Culture', 'premium'),
  ('Coffee shop breakfast', 'Home breakfast', 'Food & Culture', 'premium'),
  ('Food truck', 'Sit-down cafe', 'Food & Culture', 'premium'),
  ('Curry night', 'Pasta night', 'Food & Culture', 'premium'),
  ('Fresh baked bread', 'Store-bought bread', 'Food & Culture', 'premium'),
  ('Tasting menu', 'Comfort food classics', 'Food & Culture', 'premium'),
  ('Cheese board', 'Charcuterie board', 'Food & Culture', 'premium'),
  ('Grilled', 'Fried', 'Food & Culture', 'premium'),
  ('Homemade pizza', 'Delivery pizza', 'Food & Culture', 'premium'),
  ('Cooking together', 'Someone else cooks', 'Food & Culture', 'premium'),
  ('Traditional recipes', 'Fusion cuisine', 'Food & Culture', 'premium'),
  ('Picnic outdoors', 'Dinner table indoors', 'Food & Culture', 'premium'),
  ('Baking sweets', 'Baking bread', 'Food & Culture', 'premium'),
  ('Espresso', 'Filter coffee', 'Food & Culture', 'premium'),
  ('Craft cocktails', 'Classic cocktails', 'Food & Culture', 'premium'),
  ('Family recipes', 'Trying new recipes', 'Food & Culture', 'premium'),
  ('Street tacos', 'Gourmet burgers', 'Food & Culture', 'premium'),
  ('Slow-cooked stews', 'Quick stir-fry', 'Food & Culture', 'premium'),
  ('Local specialty dish', 'Familiar favourite dish', 'Food & Culture', 'premium'),
  ('Breakfast for dinner', 'Dinner for breakfast', 'Food & Culture', 'premium'),
  ('Vegetarian night', 'Meat and potatoes night', 'Food & Culture', 'premium'),
  ('Michelin star splurge', 'Hidden gem hole-in-the-wall', 'Food & Culture', 'premium'),
  ('Homemade sauce', 'Jarred sauce', 'Food & Culture', 'premium'),
  ('Big holiday feast', 'Simple quiet meal', 'Food & Culture', 'premium'),
  ('Ice cream sundae', 'Warm apple pie', 'Food & Culture', 'premium'),
  ('Fine wine', 'Signature cocktail', 'Food & Culture', 'premium'),
  ('Long dinner conversation', 'Quick casual bite', 'Food & Culture', 'premium'),
  ('Cultural food festival', 'Neighbourhood restaurant week', 'Food & Culture', 'premium'),
  ('Grazing all day', 'Three set meals', 'Food & Culture', 'premium'),
  ('Homegrown herbs', 'Store-bought spices', 'Food & Culture', 'premium'),
  ('Dining with a view', 'Dining in a cosy corner', 'Food & Culture', 'premium'),
  ('Surprise set menu', 'Choosing every dish yourself', 'Food & Culture', 'premium'),
  ('Late-night snack run', 'Early bedtime, no snacks', 'Food & Culture', 'premium'),
  ('Learning a new cuisine', 'Perfecting a favourite dish', 'Food & Culture', 'premium'),
  ('Big family gatherings', 'Small family visits', 'Family', 'premium'),
  ('Sunday family dinners', 'Casual family catch-ups', 'Family', 'premium'),
  ('Hosting the holidays', 'Travelling to family for holidays', 'Family', 'premium'),
  ('Family group chat', 'One-on-one calls', 'Family', 'premium'),
  ('Big family reunions', 'Close-knit family circle', 'Family', 'premium'),
  ('Family recipes passed down', 'Starting new traditions', 'Family', 'premium'),
  ('Weekend family visits', 'Occasional family visits', 'Family', 'premium'),
  ('Loud family gatherings', 'Quiet family gatherings', 'Family', 'premium'),
  ('Family game nights', 'Family movie nights', 'Family', 'premium'),
  ('Living near family', 'Living far from family', 'Family', 'premium'),
  ('Family photo albums', 'Family video calls', 'Family', 'premium'),
  ('Big holiday celebrations', 'Low-key holiday celebrations', 'Family', 'premium'),
  ('Family road trips', 'Family fly-in visits', 'Family', 'premium'),
  ('Sharing news right away', 'Sharing news in person later', 'Family', 'premium'),
  ('Same traditions every year', 'New traditions each year', 'Family', 'premium'),
  ('Extended family close by', 'Close friends as family', 'Family', 'premium'),
  ('Family text threads', 'Family phone calls', 'Family', 'premium'),
  ('Hosting family at home', 'Visiting family at their place', 'Family', 'premium'),
  ('Family barbecues', 'Family potlucks', 'Family', 'premium'),
  ('Keeping old family traditions', 'Blending in new ones', 'Family', 'premium'),
  ('Family heirlooms', 'Family stories', 'Family', 'premium'),
  ('Big cousin gatherings', 'Sibling-only catch-ups', 'Family', 'premium'),
  ('Family vacations together', 'Separate family and couple trips', 'Family', 'premium'),
  ('Sunday phone call home', 'Daily text check-ins', 'Family', 'premium'),
  ('Big family birthdays', 'Simple family birthdays', 'Family', 'premium'),
  ('Family recipe nights', 'Family game tournaments', 'Family', 'premium'),
  ('Visiting grandparents often', 'Visiting grandparents on holidays', 'Family', 'premium'),
  ('Family reunions abroad', 'Family reunions at home', 'Family', 'premium'),
  ('Planning family events together', 'Letting one person organise', 'Family', 'premium'),
  ('Family photos on the wall', 'Family photos in an album', 'Family', 'premium'),
  ('Sharing chores at family gatherings', 'Everyone brings a dish', 'Family', 'premium'),
  ('Long family phone calls', 'Quick family updates', 'Family', 'premium'),
  ('Family holiday cards', 'Family holiday calls', 'Family', 'premium'),
  ('Family board game marathons', 'Family outdoor activities', 'Family', 'premium'),
  ('Staying close to hometown family', 'Building a life elsewhere', 'Family', 'premium'),
  ('Family movie marathons', 'Family outdoor picnics', 'Family', 'premium'),
  ('Weekly family dinners', 'Monthly family dinners', 'Family', 'premium'),
  ('Family group trip planning', 'Family surprise visits', 'Family', 'premium'),
  ('Talking family history', 'Making new family memories', 'Family', 'premium'),
  ('Family holiday baking', 'Family holiday decorating', 'Family', 'premium'),
  ('Big loud holiday tables', 'Small intimate holiday tables', 'Family', 'premium'),
  ('Family pets as part of the family', 'A family without pets', 'Family', 'premium'),
  ('Sibling banter', 'Sibling deep talks', 'Family', 'premium'),
  ('Traditions from your side', 'Traditions from theirs', 'Family', 'premium'),
  ('Family camping trips', 'Family beach trips', 'Family', 'premium'),
  ('Keeping family close-knit', 'Giving family space', 'Family', 'premium'),
  ('Saving for later', 'Spending on today', 'Money & Finances', 'premium'),
  ('Budget tracking app', 'Simple mental math', 'Money & Finances', 'premium'),
  ('Splurge on experiences', 'Splurge on things', 'Money & Finances', 'premium'),
  ('Save first', 'Save what''s left', 'Money & Finances', 'premium'),
  ('Cash in hand', 'Card for everything', 'Money & Finances', 'premium'),
  ('Investing steadily', 'Keeping cash accessible', 'Money & Finances', 'premium'),
  ('Treat yourself often', 'Treat yourself rarely', 'Money & Finances', 'premium'),
  ('Splitting bills evenly', 'Taking turns paying', 'Money & Finances', 'premium'),
  ('Planning a big purchase', 'Deciding on impulse', 'Money & Finances', 'premium'),
  ('Coupons and deals', 'Convenience over discounts', 'Money & Finances', 'premium'),
  ('Saving for a house', 'Saving for travel', 'Money & Finances', 'premium'),
  ('Budget for the month', 'Budget for the week', 'Money & Finances', 'premium'),
  ('Discount shopping', 'Quality over price', 'Money & Finances', 'premium'),
  ('Emergency fund first', 'Fun fund first', 'Money & Finances', 'premium'),
  ('DIY to save money', 'Paying for convenience', 'Money & Finances', 'premium'),
  ('Comparing prices online', 'Buying in person', 'Money & Finances', 'premium'),
  ('Saving spare change', 'Rounding up to invest', 'Money & Finances', 'premium'),
  ('Generous with gifts', 'Practical with gifts', 'Money & Finances', 'premium'),
  ('Buying in bulk', 'Buying as needed', 'Money & Finances', 'premium'),
  ('Detailed spreadsheets', 'Simple gut-check budgeting', 'Money & Finances', 'premium'),
  ('Splurge vacations', 'Budget-friendly vacations', 'Money & Finances', 'premium'),
  ('Paying off debt fast', 'Steady manageable payments', 'Money & Finances', 'premium'),
  ('New purchases', 'Second-hand finds', 'Money & Finances', 'premium'),
  ('Subscriptions for convenience', 'Cancelling to save', 'Money & Finances', 'premium'),
  ('Saving for retirement early', 'Enjoying money now', 'Money & Finances', 'premium'),
  ('Negotiating prices', 'Paying the sticker price', 'Money & Finances', 'premium'),
  ('Joint savings goals', 'Individual savings goals', 'Money & Finances', 'premium'),
  ('Big one-time purchases', 'Small frequent treats', 'Money & Finances', 'premium'),
  ('Tracking every expense', 'Trusting the big picture', 'Money & Finances', 'premium'),
  ('Rainy day fund', 'Spend it while you can', 'Money & Finances', 'premium'),
  ('Cooking at home to save', 'Takeout for convenience', 'Money & Finances', 'premium'),
  ('Buying quality once', 'Buying budget and replacing', 'Money & Finances', 'premium'),
  ('Financial planning nights', 'Winging it as it comes', 'Money & Finances', 'premium'),
  ('Setting a strict budget', 'Keeping it flexible', 'Money & Finances', 'premium'),
  ('Saving bonuses', 'Spending bonuses', 'Money & Finances', 'premium'),
  ('Loyalty points and rewards', 'Simplicity over points', 'Money & Finances', 'premium'),
  ('Splitting the bill down the middle', 'Alternating who pays', 'Money & Finances', 'premium'),
  ('Investing in stocks', 'Investing in property', 'Money & Finances', 'premium'),
  ('Frugal on daily spending', 'Frugal on big spending', 'Money & Finances', 'premium'),
  ('Automatic savings transfers', 'Manual saving habits', 'Money & Finances', 'premium'),
  ('Experiences as gifts', 'Items as gifts', 'Money & Finances', 'premium'),
  ('Paying bills the day they arrive', 'Paying bills before the due date', 'Money & Finances', 'premium'),
  ('Window shopping for fun', 'Avoiding stores to save', 'Money & Finances', 'premium'),
  ('Splurging on dinner out', 'Saving by cooking at home', 'Money & Finances', 'premium'),
  ('Saving for a rainy day', 'Living for today', 'Money & Finances', 'premium'),
  ('Money talks openly shared', 'Money handled separately', 'Money & Finances', 'premium'),
  ('Brutal honesty', 'Kind white lies', 'Moral Values', 'premium'),
  ('Helping a stranger', 'Minding your own business', 'Moral Values', 'premium'),
  ('Speaking up', 'Keeping the peace', 'Moral Values', 'premium'),
  ('Fairness for everyone', 'Loyalty to your own', 'Moral Values', 'premium'),
  ('Following the rules', 'Using common sense', 'Moral Values', 'premium'),
  ('Benefit of the doubt', 'Judging by actions', 'Moral Values', 'premium'),
  ('Volunteering time', 'Donating money', 'Moral Values', 'premium'),
  ('Recycling diligently', 'Not stressing about it', 'Moral Values', 'premium'),
  ('Returning extra change', 'Assuming it evens out', 'Moral Values', 'premium'),
  ('Standing up for a stranger', 'Staying out of it', 'Moral Values', 'premium'),
  ('Telling a hard truth', 'Softening the blow', 'Moral Values', 'premium'),
  ('Punctuality matters', 'Flexibility matters more', 'Moral Values', 'premium'),
  ('Keeping promises no matter what', 'Adjusting when circumstances change', 'Moral Values', 'premium'),
  ('Buying local', 'Buying cheapest', 'Moral Values', 'premium'),
  ('Forgive and forget', 'Forgive but remember', 'Moral Values', 'premium'),
  ('Sharing credit generously', 'Taking credit when due', 'Moral Values', 'premium'),
  ('Apologising first', 'Waiting to see who''s right', 'Moral Values', 'premium'),
  ('Trusting your conscience', 'Trusting the rules', 'Moral Values', 'premium'),
  ('Helping family first', 'Helping whoever needs it most', 'Moral Values', 'premium'),
  ('Respecting tradition', 'Embracing change', 'Moral Values', 'premium'),
  ('Speaking your mind', 'Choosing your battles', 'Moral Values', 'premium'),
  ('Second chances freely given', 'Trust earned back slowly', 'Moral Values', 'premium'),
  ('Doing the right thing quietly', 'Doing the right thing publicly', 'Moral Values', 'premium'),
  ('Consistency above all', 'Adapting to the moment', 'Moral Values', 'premium'),
  ('Standing firm on principles', 'Staying open to persuasion', 'Moral Values', 'premium'),
  ('Honesty over comfort', 'Comfort over blunt honesty', 'Moral Values', 'premium'),
  ('Community first', 'Self-reliance first', 'Moral Values', 'premium'),
  ('Sustainable choices', 'Convenient choices', 'Moral Values', 'premium'),
  ('Giving generously', 'Giving thoughtfully and sparingly', 'Moral Values', 'premium'),
  ('Owning up immediately', 'Taking time to process first', 'Moral Values', 'premium'),
  ('Fair but firm', 'Kind and flexible', 'Moral Values', 'premium'),
  ('Respecting everyone''s opinion', 'Debating to find the truth', 'Moral Values', 'premium'),
  ('Choosing kindness', 'Choosing honesty', 'Moral Values', 'premium'),
  ('Setting boundaries firmly', 'Staying flexible for others', 'Moral Values', 'premium'),
  ('Doing chores your way', 'Compromising on the process', 'Moral Values', 'premium'),
  ('Ethical brands even if pricier', 'Practical choices regardless of brand', 'Moral Values', 'premium'),
  ('Trusting people until proven wrong', 'Being cautious until trust is earned', 'Moral Values', 'premium'),
  ('Speaking up in the moment', 'Reflecting before responding', 'Moral Values', 'premium'),
  ('Sharing your true opinion', 'Keeping the peace with silence', 'Moral Values', 'premium'),
  ('Helping without being asked', 'Waiting to be asked', 'Moral Values', 'premium'),
  ('Standing by your word', 'Staying open to changing your mind', 'Moral Values', 'premium'),
  ('Leading by example', 'Leading by encouragement', 'Moral Values', 'premium'),
  ('Giving anonymously', 'Giving openly', 'Moral Values', 'premium'),
  ('Prioritising the environment', 'Prioritising convenience', 'Moral Values', 'premium'),
  ('Owning a mistake publicly', 'Fixing it quietly', 'Moral Values', 'premium'),
  ('Patience as a virtue', 'Honesty as a virtue', 'Moral Values', 'premium'),
  ('Gym workouts', 'Outdoor runs', 'Hobbies & Lifestyle', 'premium'),
  ('Painting', 'Photography', 'Hobbies & Lifestyle', 'premium'),
  ('Gardening', 'Cooking', 'Hobbies & Lifestyle', 'premium'),
  ('True crime podcasts', 'Mystery novels', 'Hobbies & Lifestyle', 'premium'),
  ('Yoga', 'Weightlifting', 'Hobbies & Lifestyle', 'premium'),
  ('Hiking', 'Cycling', 'Hobbies & Lifestyle', 'premium'),
  ('Playing an instrument', 'Singing', 'Hobbies & Lifestyle', 'premium'),
  ('Journaling', 'Sketching', 'Hobbies & Lifestyle', 'premium'),
  ('DIY projects', 'Buying finished pieces', 'Hobbies & Lifestyle', 'premium'),
  ('Team sports', 'Solo sports', 'Hobbies & Lifestyle', 'premium'),
  ('Video games', 'Board games', 'Hobbies & Lifestyle', 'premium'),
  ('Crafting', 'Collecting', 'Hobbies & Lifestyle', 'premium'),
  ('Swimming', 'Dancing', 'Hobbies & Lifestyle', 'premium'),
  ('Cooking new recipes', 'Perfecting old favourites', 'Hobbies & Lifestyle', 'premium'),
  ('Pottery classes', 'Painting classes', 'Hobbies & Lifestyle', 'premium'),
  ('Rock climbing', 'Kayaking', 'Hobbies & Lifestyle', 'premium'),
  ('Home improvement projects', 'Relaxing weekends', 'Hobbies & Lifestyle', 'premium'),
  ('Learning an instrument', 'Learning a language', 'Hobbies & Lifestyle', 'premium'),
  ('Fitness classes', 'Home workouts', 'Hobbies & Lifestyle', 'premium'),
  ('Golf', 'Tennis', 'Hobbies & Lifestyle', 'premium'),
  ('Photography walks', 'Nature walks', 'Hobbies & Lifestyle', 'premium'),
  ('Growing a vegetable garden', 'Growing a flower garden', 'Hobbies & Lifestyle', 'premium'),
  ('Baking', 'Brewing', 'Hobbies & Lifestyle', 'premium'),
  ('Chess', 'Card games', 'Hobbies & Lifestyle', 'premium'),
  ('Trail running', 'Studio workouts', 'Hobbies & Lifestyle', 'premium'),
  ('Model building', 'Puzzle building', 'Hobbies & Lifestyle', 'premium'),
  ('Thrifting', 'Shopping new', 'Hobbies & Lifestyle', 'premium'),
  ('Home theatre nights', 'Cinema outings', 'Hobbies & Lifestyle', 'premium'),
  ('Sketchbook doodling', 'Digital art', 'Hobbies & Lifestyle', 'premium'),
  ('Meditation', 'Long walks', 'Hobbies & Lifestyle', 'premium'),
  ('Bird watching', 'Stargazing', 'Hobbies & Lifestyle', 'premium'),
  ('Vinyl records', 'Streaming playlists', 'Hobbies & Lifestyle', 'premium'),
  ('Scrapbooking', 'Digital photo albums', 'Hobbies & Lifestyle', 'premium'),
  ('Fishing', 'Boating', 'Hobbies & Lifestyle', 'premium'),
  ('Martial arts', 'Dance classes', 'Hobbies & Lifestyle', 'premium'),
  ('Home barista setup', 'Coffee shop visits', 'Hobbies & Lifestyle', 'premium'),
  ('Woodworking', 'Knitting', 'Hobbies & Lifestyle', 'premium'),
  ('Trivia nights', 'Karaoke nights', 'Hobbies & Lifestyle', 'premium'),
  ('Marathon training', 'Casual jogging', 'Hobbies & Lifestyle', 'premium'),
  ('Skateboarding', 'Rollerblading', 'Hobbies & Lifestyle', 'premium'),
  ('Interior decorating', 'Minimalist living', 'Hobbies & Lifestyle', 'premium'),
  ('Plant collecting', 'Art collecting', 'Hobbies & Lifestyle', 'premium'),
  ('Cooking shows', 'Travel documentaries', 'Hobbies & Lifestyle', 'premium'),
  ('Escape rooms', 'Arcade games', 'Hobbies & Lifestyle', 'premium'),
  ('Surfing', 'Snowboarding', 'Hobbies & Lifestyle', 'premium'),
  ('Journaling by hand', 'Voice memo journaling', 'Hobbies & Lifestyle', 'premium'),
  ('Living in the moment', 'Planning for the future', 'Deep Conversations', 'premium'),
  ('Following your heart', 'Following your head', 'Deep Conversations', 'premium'),
  ('Chasing big dreams', 'Finding contentment now', 'Deep Conversations', 'premium'),
  ('Learning from mistakes', 'Avoiding them altogether', 'Deep Conversations', 'premium'),
  ('Knowing the future', 'Being surprised by it', 'Deep Conversations', 'premium'),
  ('Deep roots in one place', 'A life of movement', 'Deep Conversations', 'premium'),
  ('A quiet meaningful life', 'A big memorable life', 'Deep Conversations', 'premium'),
  ('Wisdom from experience', 'Wisdom from books', 'Deep Conversations', 'premium'),
  ('Doing what you love for less', 'Doing what pays more', 'Deep Conversations', 'premium'),
  ('Growing through comfort', 'Growing through challenge', 'Deep Conversations', 'premium'),
  ('A long life', 'A full life', 'Deep Conversations', 'premium'),
  ('Being understood', 'Being free', 'Deep Conversations', 'premium'),
  ('Chasing purpose', 'Chasing peace', 'Deep Conversations', 'premium'),
  ('Changing the world', 'Changing your corner of it', 'Deep Conversations', 'premium'),
  ('Living without regrets', 'Learning from every regret', 'Deep Conversations', 'premium'),
  ('Certainty', 'Adventure', 'Deep Conversations', 'premium'),
  ('A simple life', 'An extraordinary life', 'Deep Conversations', 'premium'),
  ('Following tradition', 'Forging your own path', 'Deep Conversations', 'premium'),
  ('Remembered for your work', 'Remembered for your kindness', 'Deep Conversations', 'premium'),
  ('Inner peace', 'Outer achievement', 'Deep Conversations', 'premium'),
  ('Trusting the plan', 'Trusting the journey', 'Deep Conversations', 'premium'),
  ('Time to reflect', 'Time to act', 'Deep Conversations', 'premium'),
  ('A life well-planned', 'A life lived spontaneously', 'Deep Conversations', 'premium'),
  ('Knowing yourself fully', 'Always discovering something new', 'Deep Conversations', 'premium'),
  ('Contentment with less', 'Ambition for more', 'Deep Conversations', 'premium'),
  ('A short thrilling ride', 'A long gentle one', 'Deep Conversations', 'premium'),
  ('Being right', 'Being kind', 'Deep Conversations', 'premium'),
  ('Solitude for clarity', 'Connection for clarity', 'Deep Conversations', 'premium'),
  ('Facing fears head-on', 'Easing into them slowly', 'Deep Conversations', 'premium'),
  ('Legacy through achievements', 'Legacy through relationships', 'Deep Conversations', 'premium'),
  ('Living for today', 'Living for tomorrow', 'Deep Conversations', 'premium'),
  ('A mind full of questions', 'A heart full of answers', 'Deep Conversations', 'premium'),
  ('Freedom to roam', 'Comfort of home', 'Deep Conversations', 'premium'),
  ('Meaning found in struggle', 'Meaning found in ease', 'Deep Conversations', 'premium'),
  ('Growing old together slowly', 'Making the most of now', 'Deep Conversations', 'premium'),
  ('A life of many chapters', 'One long steady story', 'Deep Conversations', 'premium'),
  ('Chasing curiosity', 'Chasing mastery', 'Deep Conversations', 'premium'),
  ('Letting go easily', 'Holding on to what matters', 'Deep Conversations', 'premium'),
  ('Finding peace in silence', 'Finding peace in conversation', 'Deep Conversations', 'premium'),
  ('Being challenged daily', 'Being at ease daily', 'Deep Conversations', 'premium'),
  ('A path with certainty', 'A path with mystery', 'Deep Conversations', 'premium'),
  ('Success measured by growth', 'Success measured by happiness', 'Deep Conversations', 'premium'),
  ('Living boldly', 'Living gently', 'Deep Conversations', 'premium'),
  ('Trusting time to heal', 'Actively working through it', 'Deep Conversations', 'premium'),
  ('A life of exploration', 'A life of depth', 'Deep Conversations', 'premium'),
  ('Choosing joy', 'Choosing meaning', 'Deep Conversations', 'premium');
